# 목표

연말정산 신고 안내 문서 활용 RAG 시스템 구현

In [1]:
# 기본 경로 설정
# ===============================================================
import os
import requests

PROJECT_NUM = "14"

ROOT_DIR = os.getcwd()


try:
    from google.colab import drive, userdata
    IS_COLAB_MODE = True
    print("코랩 모드")

except ModuleNotFoundError as e:
    IS_COLAB_MODE = False
    ROOT_DIR = os.path.abspath(os.path.join(ROOT_DIR, ".."))
    os.environ["KMP_DUPLICATE_LIB_OK"] = "True"
    os.environ["TOKENIZERS_PARALLELISM"] = "false"
    print(f"로컬 모드")


DATA_DIR = os.path.join(ROOT_DIR, "data")
RAW_DIR = os.path.join(DATA_DIR, "raw")
os.makedirs(DATA_DIR, exist_ok=True)


# 환경변수 로드 설정
def get_secret(key_name: str):
    if IS_COLAB_MODE:
        return userdata.get(key_name)
    else:
        from dotenv import load_dotenv
        load_dotenv(dotenv_path=os.path.join(ROOT_DIR, ".env"))
        return os.getenv(key_name)


if IS_COLAB_MODE:
    import subprocess

    drive.mount('/content/drive')

    # 압축 파일 확보
    if "raw.tar.gz" not in os.listdir():

        headers = {
            "Authorization": f"token {get_secret('GITHUB_PAT')}",
            "Accept": "application/vnd.github.v3+json"
        }

        release_url = f"https://api.github.com/repos/wonbywondev/ML-DL-data/releases/tags/data-v{PROJECT_NUM}"

        response = requests.get(release_url, headers=headers)
        asset_id = response.json().get('assets', [])[0]["id"]

        download_url = f"https://api.github.com/repos/wonbywondev/ML-DL-data/releases/assets/{asset_id}"
        download_headers = headers.copy()
        download_headers["Accept"] = "application/octet-stream"

        with requests.get(download_url, headers=download_headers, stream=True) as r:
            r.raise_for_status()
            with open("raw.tar.gz", 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)

    print("· 압축 파일 있음")


    # 압축 해제 및 경로 처리
    if not os.path.exists(RAW_DIR):
        subprocess.run(["tar", "-xzvf", "raw.tar.gz", "-C", DATA_DIR], check=True)

    print("· 압축 해제 완료")
    print("· 환경 세팅 완료")


    DRIVE_DIR = os.path.join(ROOT_DIR, "drive", "MyDrive")
    SAVE_DIR = os.path.join(DRIVE_DIR, "runs", PROJECT_NUM)

    os.makedirs(SAVE_DIR, exist_ok=True)

PDF_PATH = os.path.join(RAW_DIR, "2024년+원천징수의무자를+위한+연말정산+신고안내.pdf")

로컬 모드

In [8]:
from langchain_community.document_loaders import PyPDFLoader
loader = PyPDFLoader(PDF_PATH)
docs = loader.load()

In [16]:
X = docs[2]
print(X.page_content)

국세청
연말정산 서비스
이용자 서비스 내 용 접근 경로
공통
  원천징수(연말정산)안내 홈페이지 국세청 홈페이지(www.nts.go.kr) 
국세신고안내  개인 또는 법인  연말정산
  연말정산 관련 질의회신 및 판례 조회 국세법령정보시스템
(www.hometax.go.kr  법령정보)
  인터넷 상담 및 회신 국세청 국세상담센터
(www.hometax.go.kr  상담/제보)
근로자
소득공제
자료조회
  연말정산 소득·세액공제 자료 조회
홈택스  장려금·연말정산·기부금 
연말정산간소화
[ 안내 ]    126-내선1-5번
  현금영수증 발행금액 조회
현금영수증
(홈택스  전자(세금)계산서·현금영수증·
신용카드  현금영수증(근로자·소비자))
[ 안내 ]    126-내선1-1번
공제신고서
작성   간소화자료 선택 후 신고서 자동 반영
홈택스  장려금·연말정산·기부금 
편리한 연말정산
[ 안내 ]    126-내선1-5번
간편제출     작성된 공제신고서 및 증명자료
온라인 제출
홈택스  장려금·연말정산·기부금 
편리한 연말정산
[ 안내 ]    126-내선1-5번
신고결과
조회
  과거 원천징수 영수증(지급명세서)조회
*   ’19년~’24년 및 ’25년 중 제출한
’25년 귀속분(중도퇴사자 등)은 조회 가능
*   ’25.8월 수시오픈 이후부터는
’19년 귀속 확인 불가
    제출된 연말정산 신고사항은 제출
다음날부터 조회 가능
홈택스  My홈택스  연말정산 
지급명세서 등 제출내역
[ 안내 ]    126-내선1-3번
안내책자
및 영상
  「근로자를 위한 연말정산 안내」 책자
  「근로자를 위한 연말정산」 동영상
  「편리한 연말정산 이용방법」 동영상
국세청 홈페이지(www.nts.go.kr) 
국세신고안내  개인 또는 법인  연말정산
프로그램   연말정산 모의계산 서비스
국세청 홈택스(www.hometax.go.kr) 
장려금·연말정산·기부금  편리한
연말정산  (모의계산) 연말정산 자동계산
원천징수
의무자
(회사 등)
전자신고
  원천징수이행상황신고 및 환급신청
  원천세 전자신고 설명서
  지급명세서 제출
  지급명세서 전자제출 사용자 설명서
  홈택스 연말정산 프로그램 사용자 설명서
  연말정산 홈택스 자주 묻는 질문
홈택스(www.hometax.go.kr)
[ 안내 ]    126-내선1-3번
안내책자
및 영상
  「연말정산 신고안내」 책자 및 동영상
  「편리한 연말정산 이용방법」 동영상
국세청 홈페이지(www.nts.go.kr) 
국세신고안내  개인 또는 법인  연말정산
프로그램   퇴직소득 세액계산 프로그램
  지급명세서 전산매체 제출요령
국세청 홈택스(www.hometax.go.kr) 
자료실

In [3]:
from img2table.document import PDF
from img2table.ocr import TesseractOCR
from img2table.document import Image


pdf = PDF(PDF_PATH, 
          pages=[2],
          detect_rotation=False,
          pdf_text_extraction=True)

ocr = TesseractOCR(n_threads=1, lang="eng")
doc = Image(PDF_PATH)

extracted_tables = pdf.extract_tables(
    ocr=ocr,
    implicit_rows=False,
    implicit_columns=False,
    borderless_tables=False,
    min_confidence=50
)

tesseract 5.5.2
 leptonica-1.87.0
  libgif 5.2.2 : libjpeg 8d (libjpeg-turbo 3.1.3) : libpng 1.6.54 : libtiff 4.7.1 : zlib 1.2.12 : libwebp 1.6.0 : libopenjp2 2.5.4
 Found NEON
 Found libarchive 3.8.5 zlib/1.2.12 liblzma/5.8.2 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.7 expat/expat_2.7.1 CommonCrypto/system libb2/system
 Found libcurl/8.7.1 SecureTransport (LibreSSL/3.3.6) zlib/1.2.12 nghttp2/1.67.1

In [25]:
for page_number, tables in extracted_tables.items():
    for idx, table in enumerate(tables):
        df = table.df
        print(f"Page {page_number} - Table {idx} DataFrame:")
        display(df) # 주피터 노트북 환경인 경우

Page 2 - Table 0 DataFrame:

,0,1,2,3
0,이용자,서비스,내 용,접근 경로
1,공통,원천징수(연말정산)안내 홈페이지,원천징수(연말정산)안내 홈페이지,국세청 홈페이지(www.nts.go.kr) \n국세신고안내  개인 또는 법인 ...
2,공통,연말정산 관련 질의회신 및 판례 조회,연말정산 관련 질의회신 및 판례 조회,국세법령정보시스템\n(www.hometax.go.kr  법령정보)
3,공통,인터넷 상담 및 회신,인터넷 상담 및 회신,국세청 국세상담센터\n(www.hometax.go.kr  상담/제보)
4,근로자,소득공제\n자료조회,연말정산 소득·세액공제 자료 조회,홈택스  장려금·연말정산·기부금 \n연말정산간소화\n[ 안내 ] 126-내선1-5번
5,근로자,소득공제\n자료조회,현금영수증 발행금액 조회,현금영수증\n(홈택스  전자(세금)계산서·현금영수증·\n신용카드  현금영수증(근...
6,근로자,공제신고서\n작성,간소화자료 선택 후 신고서 자동 반영,홈택스  장려금·연말정산·기부금 \n편리한 연말정산\n[ 안내 ] 126-내선1-5번
7,근로자,간편제출,작성된 공제신고서 및 증명자료\n온라인 제출,홈택스  장려금·연말정산·기부금 \n편리한 연말정산\n[ 안내 ] 126-내선1-5번
8,근로자,신고결과\n조회,과거 원천징수 영수증(지급명세서)조회\n* ’19년~’24년 및 ’25년 중 제출한...,홈택스  My홈택스  연말정산 \n지급명세서 등 제출내역\n[ 안내 ] 126...
9,근로자,안내책자\n및 영상,「근로자를 위한 연말정산 안내」 책자\n「근로자를 위한 연말정산」 동영상\n「편리한...,국세청 홈페이지(www.nts.go.kr) \n국세신고안내  개인 또는 법인 ...
10,근로자,프로그램,연말정산 모의계산 서비스,국세청 홈택스(www.hometax.go.kr) \n장려금·연말정산·기부금  편...
11,원천징수\n의무자\n(회사 등),전자신고,원천징수이행상황신고 및 환급신청\n원천세 전자신고 설명서\n지급명세서 제출\n지급명...,홈택스(www.hometax.go.kr)\n[ 안내 ] 126-내선1-3번
12,원천징수\n의무자\n(회사 등),안내책자\n및 영상,「연말정산 신고안내」 책자 및 동영상\n「편리한 연말정산 이용방법」 동영상,국세청 홈페이지(www.nts.go.kr) \n국세신고안내  개인 또는 법인 ...
13,원천징수\n의무자\n(회사 등),프로그램,퇴직소득 세액계산 프로그램\n지급명세서 전산매체 제출요령,None

In [ ]:
data = extracted_tables[2][0].content.values()
data

odict_values([[TableCell(bbox=BBox(x1=173, y1=354, x2=292, y2=409), value='이용자'), TableCell(bbox=BBox(x1=292, y1=354, x2=425, y2=409), value='서비스'), TableCell(bbox=BBox(x1=425, y1=354, x2=867, y2=409), value='내 용'), TableCell(bbox=BBox(x1=867, y1=354, x2=1323, y2=409), value='접근 경로')], [TableCell(bbox=BBox(x1=173, y1=409, x2=292, y2=622), value='공통'), TableCell(bbox=BBox(x1=292, y1=409, x2=867, y2=480), value='원천징수(연말정산)안내 홈페이지'), TableCell(bbox=BBox(x1=292, y1=409, x2=867, y2=480), value='원천징수(연말정산)안내 홈페이지'), TableCell(bbox=BBox(x1=867, y1=409, x2=1323, y2=480), value='국세청 홈페이지(www.nts.go.kr) \ue3fc\n국세신고안내 \ue3fc 개인 또는 법인 \ue3fc 연말정산')], [TableCell(bbox=BBox(x1=173, y1=409, x2=292, y2=622), value='공통'), TableCell(bbox=BBox(x1=292, y1=480, x2=867, y2=551), value='연말정산 관련 질의회신 및 판례 조회'), TableCell(bbox=BBox(x1=292, y1=480, x2=867, y2=551), value='연말정산 관련 질의회신 및 판례 조회'), TableCell(bbox=BBox(x1=867, y1=480, x2=1323, y2=551), value='국세법령정보시스템\n(www.hometax.go.kr \ue3fc 법령정보)')], [TableCell(bbox=BBox(x1=173, y1=409, x2=292, y2=622), value='공통'), TableCell(bbox=BBox(x1=292, y1=551, x2=867, y2=622), value='인터넷 상담 및 회신'), TableCell(bbox=BBox(x1=292, y1=551, x2=867, y2=622), value='인터넷 상담 및 회신'), TableCell(bbox=BBox(x1=867, y1=551, x2=1323, y2=622), value='국세청 국세상담센터\n(www.hometax.go.kr \ue3fc 상담/제보)')], [TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2=1504), value='근로자'), TableCell(bbox=BBox(x1=292, y1=622, x2=425, y2=859), value='소득공제\n자료조회'), TableCell(bbox=BBox(x1=425, y1=622, x2=867, y2=725), value='연말정산 소득·세액공제 자료 조회'), TableCell(bbox=BBox(x1=867, y1=622, x2=1323, y2=725), value='홈택스 \ue3fc 장려금·연말정산·기부금 \ue3fc\n연말정산간소화\n[ 안내 ] 126-내선1-5번')], [TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2=1504), value='근로자'), TableCell(bbox=BBox(x1=292, y1=622, x2=425, y2=859), value='소득공제\n자료조회'), TableCell(bbox=BBox(x1=425, y1=725, x2=867, y2=859), value='현금영수증 발행금액 조회'), TableCell(bbox=BBox(x1=867, y1=725, x2=1323, y2=859), value='현금영수증\n(홈택스 \ue3fc 전자(세금)계산서·현금영수증·\n신용카드 \ue3fc 현금영수증(근로자·소비자))\n[ 안내 ] 126-내선1-1번')], [TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2=1504), value='근로자'), TableCell(bbox=BBox(x1=292, y1=859, x2=425, y2=957), value='공제신고서\n작성'), TableCell(bbox=BBox(x1=425, y1=859, x2=867, y2=957), value='간소화자료 선택 후 신고서 자동 반영'), TableCell(bbox=BBox(x1=867, y1=859, x2=1323, y2=957), value='홈택스 \ue3fc 장려금·연말정산·기부금 \ue3fc\n편리한 연말정산\n[ 안내 ] 126-내선1-5번')], [TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2=1504), value='근로자'), TableCell(bbox=BBox(x1=292, y1=957, x2=425, y2=1055), value='간편제출'), TableCell(bbox=BBox(x1=425, y1=957, x2=867, y2=1055), value='작성된 공제신고서 및 증명자료\n온라인 제출'), TableCell(bbox=BBox(x1=867, y1=957, x2=1323, y2=1055), value='홈택스 \ue3fc 장려금·연말정산·기부금 \ue3fc\n편리한 연말정산\n[ 안내 ] 126-내선1-5번')], [TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2=1504), value='근로자'), TableCell(bbox=BBox(x1=292, y1=1055, x2=425, y2=1291), value='신고결과\n조회'), TableCell(bbox=BBox(x1=425, y1=1055, x2=867, y2=1291), value='과거 원천징수 영수증(지급명세서)조회\n* ’19년~’24년 및 ’25년 중 제출한\n’25년 귀속분(중도퇴사자 등)은 조회 가능\n* ’25.8월 수시오픈 이후부터는\n’19년 귀속 확인 불가\n제출된 연말정산 신고사항은 제출\n다음날부터 조회 가능'), TableCell(bbox=BBox(x1=867, y1=1055, x2=1323, y2=1291), value='홈택스 \ue3fc My홈택스 \ue3fc 연말정산 \ue3fc\n지급명세서 등 제출내역\n[ 안내 ] 126-내선1-3번')], [TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2=1504), value='근로자'), TableCell(bbox=BBox(x1=292, y1=1291, x2=425, y2=1402), value='안내책자\n및 영상'), TableCell(bbox=BBox(x1=425, y1=1291, x2=867, y2=1402), value='「근로자를 위한 연말정산 안내」 책자\n「근로자를 위한 연말정산」 동영상\n「편리한 연말정산 이용방법」 동영상'), TableCell(bbox=BBox(x1=867, y1=1291, x2=1323, y2=1402), value='국세청 홈페이지(www.nts.go.kr) \ue3fc\n국세신고안내 \ue3fc 개인 또는 법인 \ue3fc 연말정산')], [TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2=1504), value='근로자'), TableCell(bbox=BBox(x1=292, y1=1402, x2=425, y2=1504), value='프로그램'), TableCell(bbox=BBox(x1=425, y1=1402, x2=867, y2=1504), value='연말정산 모의계산 서비스'), TableCell(bbox=BBox(x1=867, y1=1402, x2=1323, y2=1504), value='국세청 홈택스(www.hometax.go.kr) \ue3fc\n장려금·연말정산·기부금 \ue3fc 편리한\n연말정산 \ue3fc (모의계산) 연말정산 자동계산')], [TableCell(bbox=BBox(x1=173, y1=1504, x2=292, y2=1875), value='원천징수\n의무자\n(회사 등)'), TableCell(bbox=BBox(x1=292, y1=1504, x2=425, y2=1725), value='전자신고'), TableCell(bbox=BBox(x1=425, y1=1504, x2=867, y2=1725), value='원천징수이행상황신고 및 환급신청\n원천세 전자신고 설명서\n지급명세서 제출\n지급명세서 전자제출 사용자 설명서\n홈택스 연말정산 프로그램 사용자 설명서\n연말정산 홈택스 자주 묻는 질문'), TableCell(bbox=BBox(x1=867, y1=1504, x2=1323, y2=1725), value='홈택스(www.hometax.go.kr)\n[ 안내 ] 126-내선1-3번')], [TableCell(bbox=BBox(x1=173, y1=1504, x2=292, y2=1875), value='원천징수\n의무자\n(회사 등)'), TableCell(bbox=BBox(x1=292, y1=1725, x2=425, y2=1800), value='안내책자\n및 영상'), TableCell(bbox=BBox(x1=425, y1=1725, x2=867, y2=1800), value='「연말정산 신고안내」 책자 및 동영상\n「편리한 연말정산 이용방법」 동영상'), TableCell(bbox=BBox(x1=867, y1=1725, x2=1323, y2=1800), value='국세청 홈페이지(www.nts.go.kr) \ue3fc\n국세신고안내 \ue3fc 개인 또는 법인 \ue3fc 연말정산')], [TableCell(bbox=BBox(x1=173, y1=1504, x2=292, y2=1875), value='원천징수\n의무자\n(회사 등)'), TableCell(bbox=BBox(x1=292, y1=1800, x2=425, y2=1875), value='프로그램'), TableCell(bbox=BBox(x1=425, y1=1800, x2=867, y2=1875), value='퇴직소득 세액계산 프로그램\n지급명세서 전산매체 제출요령'), TableCell(bbox=BBox(x1=867, y1=1800, x2=867, y2=1875), value=None)]])

In [19]:
import pandas as pd

a = pd.DataFrame(data)

In [20]:
a

,0,1,2,3
0,"TableCell(bbox=BBox(x1=173, y1=354, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=354, x2=425, y2...","TableCell(bbox=BBox(x1=425, y1=354, x2=867, y2...","TableCell(bbox=BBox(x1=867, y1=354, x2=1323, y..."
1,"TableCell(bbox=BBox(x1=173, y1=409, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=409, x2=867, y2...","TableCell(bbox=BBox(x1=292, y1=409, x2=867, y2...","TableCell(bbox=BBox(x1=867, y1=409, x2=1323, y..."
2,"TableCell(bbox=BBox(x1=173, y1=409, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=480, x2=867, y2...","TableCell(bbox=BBox(x1=292, y1=480, x2=867, y2...","TableCell(bbox=BBox(x1=867, y1=480, x2=1323, y..."
3,"TableCell(bbox=BBox(x1=173, y1=409, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=551, x2=867, y2...","TableCell(bbox=BBox(x1=292, y1=551, x2=867, y2...","TableCell(bbox=BBox(x1=867, y1=551, x2=1323, y..."
4,"TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=622, x2=425, y2...","TableCell(bbox=BBox(x1=425, y1=622, x2=867, y2...","TableCell(bbox=BBox(x1=867, y1=622, x2=1323, y..."
5,"TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=622, x2=425, y2...","TableCell(bbox=BBox(x1=425, y1=725, x2=867, y2...","TableCell(bbox=BBox(x1=867, y1=725, x2=1323, y..."
6,"TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=859, x2=425, y2...","TableCell(bbox=BBox(x1=425, y1=859, x2=867, y2...","TableCell(bbox=BBox(x1=867, y1=859, x2=1323, y..."
7,"TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=957, x2=425, y2...","TableCell(bbox=BBox(x1=425, y1=957, x2=867, y2...","TableCell(bbox=BBox(x1=867, y1=957, x2=1323, y..."
8,"TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=1055, x2=425, y...","TableCell(bbox=BBox(x1=425, y1=1055, x2=867, y...","TableCell(bbox=BBox(x1=867, y1=1055, x2=1323, ..."
9,"TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=1291, x2=425, y...","TableCell(bbox=BBox(x1=425, y1=1291, x2=867, y...","TableCell(bbox=BBox(x1=867, y1=1291, x2=1323, ..."
10,"TableCell(bbox=BBox(x1=173, y1=622, x2=292, y2...","TableCell(bbox=BBox(x1=292, y1=1402, x2=425, y...","TableCell(bbox=BBox(x1=425, y1=1402, x2=867, y...","TableCell(bbox=BBox(x1=867, y1=1402, x2=1323, ..."
11,"TableCell(bbox=BBox(x1=173, y1=1504, x2=292, y...","TableCell(bbox=BBox(x1=292, y1=1504, x2=425, y...","TableCell(bbox=BBox(x1=425, y1=1504, x2=867, y...","TableCell(bbox=BBox(x1=867, y1=1504, x2=1323, ..."
12,"TableCell(bbox=BBox(x1=173, y1=1504, x2=292, y...","TableCell(bbox=BBox(x1=292, y1=1725, x2=425, y...","TableCell(bbox=BBox(x1=425, y1=1725, x2=867, y...","TableCell(bbox=BBox(x1=867, y1=1725, x2=1323, ..."
13,"TableCell(bbox=BBox(x1=173, y1=1504, x2=292, y...","TableCell(bbox=BBox(x1=292, y1=1800, x2=425, y...","TableCell(bbox=BBox(x1=425, y1=1800, x2=867, y...","TableCell(bbox=BBox(x1=867, y1=1800, x2=867, y..."

In [24]:
import pdfplumber

pdf = pdfplumber.open(PDF_PATH)
X = pdf.pages[2]
im = X.to_image()
text = X.extract_text(keep_black_chars=True)

In [26]:
print(text)

국세청
연말정산 서비스
이용자 서비스 내 용 접근 경로
국세청 홈페이지(www.nts.go.kr) 
원천징수(연말정산)안내 홈페이지
국세신고안내  개인 또는 법인  연말정산
국세법령정보시스템
공통 연말정산 관련 질의회신 및 판례 조회
(www.hometax.go.kr  법령정보)
국세청 국세상담센터
인터넷 상담 및 회신
(www.hometax.go.kr  상담/제보)
홈택스  장려금·연말정산·기부금 
연말정산 소득·세액공제 자료 조회 연말정산간소화
[ 안내 ] 126-내선1-5번
소득공제
자료조회 현금영수증
(홈택스  전자(세금)계산서·현금영수증·
현금영수증 발행금액 조회
신용카드  현금영수증(근로자·소비자))
[ 안내 ] 126-내선1-1번
홈택스  장려금·연말정산·기부금 
공제신고서
간소화자료 선택 후 신고서 자동 반영 편리한 연말정산
작성
[ 안내 ] 126-내선1-5번
홈택스  장려금·연말정산·기부금 
작 성된 공제신고서 및 증명자료
간편제출 편리한 연말정산
온라인 제출
[ 안내 ] 126-내선1-5번
근로자
과거 원천징수 영수증(지급명세서)조회
* ’ 19년~’24년 및 ’25년 중 제출한
’25년 귀속분(중도퇴사자 등)은 조회 가능 홈택스  My홈택스  연말정산 
신고결과
* ’ 25.8월 수시오픈 이후부터는 지급명세서 등 제출내역
조회
’19년 귀속 확인 불가 [ 안내 ] 126-내선1-3번
제 출된 연말정산 신고사항은 제출
다음날부터 조회 가능
「근로자를 위한 연말정산 안내」 책자
안내책자 국세청 홈페이지(www.nts.go.kr) 
「근로자를 위한 연말정산」 동영상
및 영상 국세신고안내  개인 또는 법인  연말정산
「편리한 연말정산 이용방법」 동영상
국세청 홈택스(www.hometax.go.kr) 
프로그램 연말정산 모의계산 서비스 장려금·연말정산·기부금  편리한
연말정산  (모의계산) 연말정산 자동계산
원천징수이행상황신고 및 환급신청
원천세 전자신고 설명서
지급명세서 제출 홈택스(www.hometax.go.kr)
전자신고
지급명세서 전자제출 사용자 설명서 [ 안내 ] 126-내선1-3번
원천징수 홈택스 연말정산 프로그램 사용자 설명서
의무자 연말정산 홈택스 자주 묻는 질문
(회사 등)
안내책자 「연말정산 신고안내」 책자 및 동영상 국세청 홈페이지(www.nts.go.kr) 
및 영상 「편리한 연말정산 이용방법」 동영상 국세신고안내  개인 또는 법인  연말정산
퇴직소득 세액계산 프로그램 국세청 홈택스(www.hometax.go.kr) 
프로그램
지급명세서 전산매체 제출요령 자료실

In [ ]:

# TABLE_SETTINGS = {
#     "vertical_strategy": "lines",
#     "horizontal_strategy": "lines",
#     "explicit_vertical_lines": [],
#     "explicit_horizontal_lines": [],
#     "snap_tolerance": 3,
#     "snap_x_tolerance": 2,
#     "snap_y_tolerance": 2,
#     "join_tolerance": 3,
#     "join_x_tolerance": 3,
#     "join_y_tolerance": 3,
#     "edge_min_length": 3,
#     "min_words_vertical": 3,
#     "min_words_horizontal": 1,
#     "intersection_tolerance": 3,
#     "intersection_x_tolerance": 3,
#     "intersection_y_tolerance": 3,
#     "text_tolerance": 3,
#     "text_x_tolerance": 3,
#     "text_y_tolerance": 3,
# }

all_pages = []

with pdfplumber.open(PDF_PATH) as pdf:
    pages = pdf.pages

    for page in pages:

        tables = page.extract_tables()

        all_pages.extend(tables)

In [7]:
len(all_pages)

250

In [ ]:
import random

for i in range(10):

    print(docs[i].page_content)
    print("="*30)

연말정산
신고안내
일 하나는 제대로 하는,
국민께 인정받는 국세청
2024. 12.
2024 원천징수의무자를 위한
맞춤형 안내
간소화 서비스
 일괄제공 서비스
발간등록번호
11-1210000-000072-10
==============================
머 리 말
어려운 경제 상황 속에서도 항상 성실하게 원천징수의무를 이행하여 국세행정에
협력해주신 원천징수의무자(회사)와 성실하게 세금을 납부하신 근로자 여러분께 진심
으로 감사드립니다.
그동안 국세청은 「연말정산 미리보기」, 「편리한 연말정산」 시스템과 「간소화자료
일괄제공」 서비스를 시행하는 등 디지털 납세서비스를 제공하고 「맞춤형안내」를 통해
성실 납세를 지원해 왔습니다.
더불어, 2024년 귀속부터는 소득기준 초과 부양가족에 대한 자료 조회 및 다운로드를
제한하여 납세자의 실수를 최소화하고 정확한 연말정산을 지원하기 위해 「간소화
서비스」를 전면 개편합니다.
이 책자에는 세법 개정사항과 최신 예규, 소득·세액공제신고서 작성 방법, 홈택스를
이용한 지급명세서 제출 방법 등을 분야별로 담아 납세자에게 실질적인 도움이 될 수
있도록 구성하였습니다.
책자에 수록된 내용 외에도 연말정산 주요정보, 동영상 자료, 계산 사례, 체크리스트 등
다양한 자료를 국세청 누리집(www.nts.go.kr) 연말정산 종합안내에서 제공하고 있습니다.
본 책자가 연말정산에 관한 납세자 여러분의 궁금증을 해소하고, 원천징수의무 이행에
유용한 참고자료로 활용되어 성실신고·납부에 도움이 되기를 바랍니다.
2024년 12월
법인납세국장
연말정산
신고안내
2024 원천징수의무자를 위한
==============================
국세청
연말정산 서비스
이용자 서비스 내 용 접근 경로
공통
  원천징수(연말정산)안내 홈페이지 국세청 홈페이지(www.nts.go.kr) 
국세신고안내  개인 또는 법인  연말정산
  연말정산 관련 질의회신 및 판례 조회 국세법령정보시스템
(www.hometax.go.kr  법령정보)
  인터넷 상담 및 회신 국세청 국세상담센터
(www.hometax.go.kr  상담/제보)
근로자
소득공제
자료조회
  연말정산 소득·세액공제 자료 조회
홈택스  장려금·연말정산·기부금 
연말정산간소화
[ 안내 ]    126-내선1-5번
  현금영수증 발행금액 조회
현금영수증
(홈택스  전자(세금)계산서·현금영수증·
신용카드  현금영수증(근로자·소비자))
[ 안내 ]    126-내선1-1번
공제신고서
작성   간소화자료 선택 후 신고서 자동 반영
홈택스  장려금·연말정산·기부금 
편리한 연말정산
[ 안내 ]    126-내선1-5번
간편제출     작성된 공제신고서 및 증명자료
온라인 제출
홈택스  장려금·연말정산·기부금 
편리한 연말정산
[ 안내 ]    126-내선1-5번
신고결과
조회
  과거 원천징수 영수증(지급명세서)조회
*   ’19년~’24년 및 ’25년 중 제출한
’25년 귀속분(중도퇴사자 등)은 조회 가능
*   ’25.8월 수시오픈 이후부터는
’19년 귀속 확인 불가
    제출된 연말정산 신고사항은 제출
다음날부터 조회 가능
홈택스  My홈택스  연말정산 
지급명세서 등 제출내역
[ 안내 ]    126-내선1-3번
안내책자
및 영상
  「근로자를 위한 연말정산 안내」 책자
  「근로자를 위한 연말정산」 동영상
  「편리한 연말정산 이용방법」 동영상
국세청 홈페이지(www.nts.go.kr) 
국세신고안내  개인 또는 법인  연말정산
프로그램   연말정산 모의계산 서비스
국세청 홈택스(www.hometax.go.kr) 
장려금·연말정산·기부금  편리한
연말정산  (모의계산) 연말정산 자동계산
원천징수
의무자
(회사 등)
전자신고
  원천징수이행상황신고 및 환급신청
  원천세 전자신고 설명서
  지급명세서 제출
  지급명세서 전자제출 사용자 설명서
  홈택스 연말정산 프로그램 사용자 설명서
  연말정산 홈택스 자주 묻는 질문
홈택스(www.hometax.go.kr)
[ 안내 ]    126-내선1-3번
안내책자
및 영상
  「연말정산 신고안내」 책자 및 동영상
  「편리한 연말정산 이용방법」 동영상
국세청 홈페이지(www.nts.go.kr) 
국세신고안내  개인 또는 법인  연말정산
프로그램   퇴직소득 세액계산 프로그램
  지급명세서 전산매체 제출요령
국세청 홈택스(www.hometax.go.kr) 
자료실
==============================
고용관계 또는 이와 유사한 계약에 의하여 근로를 제공하고 지급받는 모든 대가 등
(다만, 일용근로소득 제외)
※ 연간 근로소득은 비과세소득을 포함하며 일반적으로 「연봉」을 말함
  실비변상적 급여
    자기차량운전보조금(본인명의 임대차량 포함, 월 20만원 이내), 연구보조비(월 20만원 이내),
회사지급규정에 의해 지급받는 여비 등
  국외근로소득(월 100만원 또는 500만원 이내)
  비과세 학자금, 근로장학금
    생산 및 그 관련직에 종사하는 근로자의 연장근로 등으로 인하여 받는 급여(연 240만원 이내)
  현물식사 또는 월 20만원 이하 식사대
  6세 이하의 자녀 보육수당(월 20만원 이내)
  자녀 출생일 이후 2년 이내에 회사로부터 지급(2회 이내)받는 급여(한도 없음)
*   ’24년에 수당 지급 시 ’21.1.1. 이후 출생자에 대한 지급분 포함
  고용보험법 등에 따라 받는 육아휴 직급여, 출산전후 휴가급여 등
  연 7 00만원 이하의 직무발명보상금
( = 연간 근로소득 - 비과세소득 )  ※   총급여액은 의료비, 연금계좌, 월세액 세액공제·신용카드 등
소득공제 적용 시 활용
총급여액 공제액
(2,000만원 한도)
공제액
(2,000만원 한도, 속산표)
500만원 이하 총급여액의 7 0% 총급여액의 7 0%
500만원 초과 1,500만원 이하 350만원 + 500만원 초과액의 40% 총급여액 × 40%  +  150만원
1,500만원 초과 4,500만원 이하7 50만원 +  1,500만원 초과액의 15% 총급여액 × 15%  +  525만원
4,500만원 초과 1억원 이하 1,200만원 + 4,500만원 초과액의 5% 총급여액 ×   5 %  +  975만원
1억원 초과 1,475만원 +  1억원 초과액의 2% 총급여액 ×   2 %  +  1,275만원
( = 총급여액 - 근로소득공제 )  ※   근로소득금액은 기부금·중소기업창업투자조합, 소기업소상공인
소득공제 한도적용시 활용
    기본공제：근로자 본인, 연간 소득금액 100만원(근로소득만 있는 자는 총급여액 500만원)
이하인 배우자 및 생계를 같이하는 부양가족(나이요건 충족 필요, 장애인은 나이제한
없음)에 대해 1명당 연 150만원
부양가족 직계존속 직계비속 형제자매 위탁아동 수급자
나이요건 60세 이상
(’64.12.31.이전)
20세 이하
(’04.01.01.이후)
20세 이하
60세 이상
해당과세기간 6개월 이상
직접 양육한 위탁아동 제한없음
  추가공제：기본공제대상자가 다음의 요건에 해당하는 경우 추가공제
요건 경로우대(70세 이상) (’54.12.31.이전) 장애인 부녀자(부양/기혼) 한부모*
공제금액 100만원 200만원 50만원 100만원
* 한부모 공제는 부녀자공제와 중복 적용 배제(중복시 한부모 공제 적용)
근로소득자의 과세표준 및
세액계산
연간 근로소득
총급여액
근로소득금액
(-) 근로소득공제
(-) 인적공제
(-) 비과세소득
52P
93P
94P
==============================
공적연금(국민연금, 공무원연금, 군인연금, 사립학교교직원연금, 별정우체국연금, 국민연금과
직역연금의 연계에 관한 법률)의 근로자 부담금 : 전액 공제
  보험료
    국민건강보험료·고용보험료·노인장기요양보험료 :  전액 공제
  주택자금공제
    주택임차차입금 원리금상환액의 40%  공제 :  주택마련저축과 합하여 연 400만원 한도
    장기주택저당차입금 이자상환액 공제 :  연 600만원~ 2,000만원 한도
*   주택자금공제와 주택마련저축공제를 합하여 한도금액 계산(2012.1.1. 이후 차입분에 한해 적용)
상환기간 15년 이상 상환기간 10년 이상
고정금리 +  비거치식 고정금리 or 비거치식 기타 고정금리 or 비거치식
2,000만원 1,800만원 8 00만원 600만원
    개인연금저축 :  2000.12.31.까지 가입한 개인연금저축 납입액의 40%  공제(연 7 2만원 한도)
    소 기업·소상공인 공제부금 :  소기업 ·소상공인공제에 가입하여 해당 연도에 납입 한 금액
(근로소득금액 4천만원 이하 500만원, 1억원 이하 300만원, 1억원 초과 200만원 한도)
    주 택마련저축공제 :  청약저축·주택청약종합저축에 납입한 금액의 40%  공제(납입한도:
300만원)
    중소기업창업투자조합 출자 등 소득공제 :  출자·투자분에 대해 투자금액의 10% (벤처
기업에 직접투자 3천만원이하 100% , 5천만원 이하 7 0% , 5천만원 초과 30%) 공제(종합
소득금액의 50%  한도로 하며, 벤처기업투자신탁 에 대한 소득공제 금액은 300만원을
초과할 수 없음)
    신용카드 등 사용금액 :  신용카드, 직불카드, 선불카드, 현금영수증 사용액의 합계액 중
총급여액의 25% 를 초과하는 금액의 15%~40% 를 소득공제
*   공제한도 :  총급여 7 천만원 이하는 300만원, 총급여 7 천만원 초과는 250만원이며 공제한도 초과
금액이 있는 경우 아래 금액을 추가공제
   그 한도를 초과하는 금액과 전통시장 사용분에 공제율 , 대중교통 이용분에 공제율, 총급여 7 천
만원 이하자의 도서·신문·영화관람료·공연·박물관·미술관 사용분에 공제율 을 곱한 금액의
합계액 중 작거나 같은 금액(연간 300만원 한도)을 추가로 공제하고,
   2023년 대비 2024년 신용카드 사용금액 5%  초과 증가분에 대하여 10%  공제율 을 적용하여
100만원을 한도로 추가 공제
    우리사주조합출연금 :  우리사주조합원이 우리사주를 취득하기 위해 우리사주조합에
출연한 금액(연 400만원 한도, 벤처기업 연 1,500만원 한도)
    고용유지중소기업 근로자 :  고용유지 중소기업에 근무하는 상시근로자의 임금삭 감액의
50% 를 소득공제 (연 1,000만원 한도)
    청년형 장기집합투자증권 저축 :  청년형 장기집합투 자증권저축 납 입액의 40%  소득공제
(연 240만원 한도)
    장기집합투자증권저축 :  장기집합투자증권저축 납입액의 40%  소득공제(연 240만원 한도)
119P
(-)   그 밖의 소득
공제
(-) 연금보험료공제
(-) 특별소득공제
102P
104P
==============================
( =  근로소득금액 - 인적공제 - 연금보험료공제 - 특별소득공제 - 그 밖의 소득공제 +  소득공제
종합한도초과액)
*   소득공제 종합한도초과액 :  특별소득공제 및 그 밖의 소득공제 중 종합한도대상 공제금액이 2,500만원을
초과하는 경우 과세표준에 합산
과세표준 기본세율 기본세율(속산표)
1,400만원 이하 과세표준의 6% 과세표준의 6%
1,400만원~5,000만원 이하 8 4만원 + (1,400만원 초과금액의 15%)    (과세표준 × 15% ) - 126만원
5,000만원~8,8 00만원 이하 624만원 + (5,000만원 초과금액의 24%)    (과세표준 × 24% ) - 576만원
8 ,8 00만원~ 1.5억원  이 하             1,536만원 + (8,8 00만원 초과금액의 35% )    (과세표준 × 35% ) - 1,544만원
1.5억원~ 3억원 이하 3,706만원 + (1억5천만원 초과금액의 38%)    (과세표준 × 38%) - 1,994만원
3억원~ 5 억원 이하 9 ,406만원 + (3억원 초과금액의 40% ) (과세표준 × 40% ) - 2,594만원
5 억원~ 10억원 이하 17 ,406만원 + (5억원 초과금액의 42% ) (과세표준 × 42% ) - 3,594만원
10억원 초과 38 ,406만원 + (10억원 초과금액의 45% ) (과세표준 × 45% ) - 6,594만원
과세표준에 기본세율을 적용하여 계산
    중소기업 취업자 소득세 감면 :  15세∼34세 이하 청년, 60세 이상인 사람, 장애인, 경력
단절여성이 중소기업 에 취업하는 경우  취업일로부터 3년간(청년 5년간) 근로소득세
7 0% (청년 90% ) 감면(연간 200만원 한도)
    근로소득세액공제 :  산출세액 130만원 이하분 55% , 초과분 30% 공제(74만원, 66만원,
20 만원 한도)
    결혼세액공제 :  ’24년~’26년까지 혼인신고 한 거주자에 대하여 혼인신고를 한 해에 50만원
세액공제(인별 기준, 생애 1회)
    자녀세액공제 :  기본공제대상(8세 이상) 자녀 및 손자녀 1명 15만원, 2명 35만원, 3명 이상
(35만원+2명 초과 1명당 30만원) 출생·입양 :  첫째 30만원, 둘째 50만원, 셋째이상 7 0만원
    연 금 계좌세액공제 :  퇴직연금·연금저축 납입액의 12%  세액공제(총급여액 55백만원 이하는 15% )
    공제한도는 연 600만원(퇴직연금과 합하여 연 900만원 한도)
    개인종합자산관리계좌(ISA ) 만기시 연금계좌 전환금액의 10% 에 해당하는 금액(세액공제 대상금액,
300만원 한도)의 12%(총급여 55백 만원 이하 15% ) 추가 세액공제
  특별세액공제
  보험료 세액공제(세액공제율 :  12% , 장애인전용보장성보험은 15% )
    기본공제대상자를 피보험자로 하는 보장성보험료 :  연 100만원 공제대상 한도
    기본공제대상자 중 장애인을 피보험자로 하는 장애인전용보장성보험료 :  연 100만원 공제대상 한도
  의료비 세액공제(세액공제율 :  15% , 난임시술비는 30% , 미숙아·선천성 이상아 의료비는 20% )
    기본공제대상자(소득·나이 제한 없음)를 위해 지출한 총급여액의 3% 를 초과하는 의료비 :
연 7 00만원 공제대상 한도.
다만, 본인, 65세 이상자, 6세 이하자, 장애인, 미숙아·선천성 이상아, 건강보험 산정특 례자로
등록된 자를 위해 지출한 의료비, 난임시술비는 한도 없음
※ 산후조리원비용 :  출산 1회당 200만원 한도
※ 장애인활동지원급여* 비용 중 실제 지출한 본인부담금
* 「장애인활동 지원에 관한 법률」에 따라 수급자에게 제공되는 활동보조, 방문목욕, 방문간호 등 서비스
과세표준
산출세액
(-)   세액감면 및
세액공제
(x) 기본세율
146P
==============================
교육비 세액공제(세액공제율 :  15% )
    근로자 본인을 위해 대학·대학원 1학기 이상의 교육과정 등에 지출한 교육비 :  전액 공제대상
    직 계존속을 제외한 기본공제대상자(나이 제한 없음)를 위해 교육기관(대학원 제외) 등에 지출한
교육비 :  취학전 아동 및 초·중·고생 1명당 연 300만원, 대학생 1명당 연 900만원 한도
    기본공제대상자인 장애인(소득 제한 없음, 직계존속 포함)의 재활교육을 위하여 지출한 특수교육비 :
전액 공제대상
  기부금 세액공제 대상한도 및 세액공제율
기부금 종류 소득공제·세액공제 대상금액 한도 세액공제율 이월
공제
    정치자금기부금
(조특법 제 7 6조) 근로소득금액×100%
10만원 이하 100/110
10만원 초과 15% (3천만원
초과분 25% )
    고향사랑기부금
(조특법 제58 조)
(근로소득금액-)×100%
(연간 500만원 한도)
10만원 이하 100/110
10만원 초과 15/100
  특례기부금 (근로소득금액--)×100%
특례기부금+ 일반기부금+
우리사주조합기부금 : 15%
(1천만원 초과분 30%)
(3천만원 초과분 40%)
10년
    우리사주조합기부금
(조특법 제88조의 4
제13항)
(근로소득금액---)×30% -
    일반기부금
(소법 제34조 제3항)
종교단체에 기부한
금액이 있는 경우
[ (근로소득금액----)×10%
+ (근로소득금액----)의 20%와
종교단체 외에 지급한 금액*  중 적은 금액]
* 당해+이월 연도 종교단체 외 일반기부금
10년
    일반기부금
(소법 제34조 제3항)
종교단체에 기부한
금액이 없는 경우
(근로소득금액----)×30%
* 일반기부금(종교단체 및 비종교단체 포함)은 근로소득금액의 30%를 초과할 수 없음
    표준세액공제 :  특별소득공제·특별세액공제·월세액세액공제를 신청하지 아니한 경우
연 13만원을 세액공제
    납세조합공제 :  납세조합에 의하여 원천징수된 근로소득에 대해 종합소득산출세액의 5% 를
세액공제(1인당 연간 100만원 한도, 근로제공기간에 따라 월할계산)
    주택자금차입금이자세액공제 :  (’95.11.1.∼’97.12.31. 취득)주택자금차입금에 대한 이자
상환액의 30%  세액공제
    외국납부세액공제 :  거주자의 외국소득세액을 당해연도의 종합소득산출세액에서 공제
    월세액 세액공제 :  총급여액 8 천만원 이하 무주택 세대주(일정요건을 충족한 세대원도
가능)가 지급한 월세액(연 1,000만원 한도)의 15%·17% 세액공제
( = 산출세액 - 세액감면·세액공제 )
    주(현)근무지의 기납부세액과 종(전)근무지의 결정세액의 합계액
( =  결정세액 - 기납부세액 ) ※ 결정세액 >  기납부세액 :  차액을 납부, 결정세액 <  기납부세액 :  차액을 환급
결정세액
차감징수세액
(-) 기납부세액
==============================
연말정산 소득·세액공제
요건표
구 분
공 제 요 건
비 고
나이요건* 소득요건*
동거 요건
주민등록동거 일시퇴거 허용
기
본
공
제
본 인 × × ×
배 우 자 ×  ×
직계존속 60세 이상  △
(주거형편상 별거 허용) 19 64.12.31. 이전
직계비속, 동거입양자 20세 이하  × 2004.  1.  1. 이후
장애인 직계비속의
장애인 배우자 ×  ×
형제자매 60세 이상
20세 이하    19 64.12.31. 이전
2004.  1.  1. 이후
국민기초생활보장법에
의한 수급자 ×   
위탁아동 
추
가
공
제
장 애 인 기본공제대상자 중 장애인
경로우대 기본공제대상자 중 7 0세 이상인 자 19 54.12.31.이전
부 녀 자 배우자가 없는 여성근로자로서 기본공제대상 부양가족이 있는 세대주 또는
배우자가 있는 여성 근로자 (종합소득금액 3천만원 이하자)
한 부 모 배우자가 없는 자로서 부양자녀(20세 이하)가 있는자
연금보험료 공제 공적연금보험료의 근로자 본인 불입분만 공제 가능
*  나이요건    장애인의 경우 나이요건을 적용하지 않으며, 당해 과세기간 중 공제기준일이 해당하는 날이 있는 경우  적용
* 소득요건    연간 소득금액 100만원 이하(근로소득만 있는 경우 총급여 500만원 이하)
구 분
기본공제대상자의 요건 근로기간 지출한
비용만 공제 비 고
나이요건 소득요건
특별
소득공제
보 험 료 근로자 본인 부담분만 공제 가능 (건강·노인장기요양·고용보험료)
주택자금공제 - -  본인만 가능
그 밖의
소득공제
개인연금저축 근로자 본인 불입분만 공제 가능(배우자, 부양가족 불입분 제외)
주택마련저축 세대주인 근로자 본인 불입분만 공제 가능
신용카드 등 ×   형제자매 제외
자녀세액공제 (8세이상)   - 기본공제대상 자녀
(입양자·위탁아동·손자녀 포함)
2016.12.31.
이전
연금계좌세액공제 근로자 본인 불입분만 세액공제 가능(배우자, 부양가족 불입분 제외)
특별
세액공제
보장성보험료   
의 료 비 × × 
교 육 비 ×   직계존속 제외      *       장애인특수교육비는 소득요건
제한 없으며, 직계존속도 가능
기 부 금 ×  ×
기본공제대상자   *       정치자금기부금,
고향사랑기부금, 우리사주조합
기부금은 본인만 가능
표준세액공제 특별소득공제, 특별세액공제, 월세액세액공제를 신청하지 아니한 경우 표준세액공제(13만원) 적용
==============================
「간소화 서비스 전면개편」
주요 내용
「간소화자료 일괄제공 서비스」 이용을 희망하는 회사는 근로자로부터 간소화자료 일괄제공 신청서를 제출받아,
신청 근로자 명단을 ’25.1.10.까지 홈택스를 통해 등록하여야 함
근로자는 ’24.12.1.부터 ’25.1.15.까지 일괄제공 신청 내용에 대한 확인(동의)절차를 진행하고, 국세청은 확인 절차를
진행한 근로자의 간소화자료를 회사에 일괄제공함
「간소화자료 일괄제공 서비스」 신청 방법 및 절차
일괄제공 명단 등록
회사  국세청
~’25.1.10.
간소화자료 일괄제공
국세청  회사
’25.1.17(20). ~ 3.10.
일괄제공 신청내역 확인(동의)
근로자  국세청
~’24.12.1. ~ ’25.1.15.
  회사 신청   근로자 확인(동의)   자료 내려받기
  주요 개선 내용
1.   간소화서비스를 개선하여 소득금액 100만원(총급여 500만원)을 초과하는 비공제 대상 부양가족의 공제자료는
활용을 제한하기 위해 조회·다운로드 기능 미제공
 ’24년 6월까지 발생한 소득자료 기준
 보험료·의료비·교육비는 부양가족의 인적공제 가능 여부와 무관하게 모두 제공
2. 부양가족 중 소득기준 초과자(Y)를 간소화자료로 제공(Y만 표시, N은 미표시)
  소득금액 100만원(총급여 500만원) 산출 방법
1. 근로소득만 있는 경우에는 ’24.1월~’24.6월까지 발생한 총급여
2. 타 소득이 있는 경우 아래의 방법으로 산정한 ’24.1월~’24.6월까지의 소득금액 합산
※ 각 소득별 소득금액 산출방법
 근로소득=총급여액-(총급여액×근로소득공제)      사업소득= 지급액-(지급액×업종별 단순경비율[타가] )
 기타소득= 지급액-(지급액×의제필요경비율)          양도소득= 양도소득금액(음수는 0으로 간주)
 퇴직소득= 과세대상 퇴직급여
==============================
연말정산 과다공제
유형
항목 과다공제 사례
    소득금액 기준(1백만 원)
초과 부양가족 공제
    연간 소득금액(근로·사업·양도·퇴직소득 등) 합계액이 1백만 원을
초과하는 부양가족을 인적공제(기본+추가공제)
* 근로소득만 있는 경우 총급여 5백만원
  부양가족 중복공제
    맞벌이 근로자가 자녀 등을 중복으로 공제
    형제자매가 부모님을 각각 중복하여 공제
    사망자에 대한 인적공제     과세기간 개시일 이전 사망한 부양가족에 대해 인적공제
  이혼한 배우자 등 공제
    과세기간 종료일 이전 이혼한 배우자에 대해 인적공제
    이혼 후 지출한 보험료·기부금 등에 대해 세액공제
    연령 조건에 맞지 않는
부양가족 공제     연령 조건 미충족 형제·자매에 대해 부양가족 공제
    교육비·의료비 등
중복공제
    동일 부양가족의 의료비, 교육비, 신용카드 공제를 다수의 근로자가
중복 또는 분할하여 공제
  주택자금 과다공제     유주택자* 임에도 주택자금(월세액 공제 포함) 공제
* 장기주택저당차입금 이자상환액은 1주택자도 공제 가능
  교육비 과다공제
    자녀, 형제자매 등의 대학원 교육비 공제
    자녀 교육비를 부부가 중복으로 공제
    교육비 중 사내근로복지기금으로부터 학자금(비과세)을 지원받거나,
학교로부터 받은 장학금 등을 공제
  의료비 과다공제
    실손의료보험금 등 보험회사로부터 수령한 보험금으로 보전받은
의료비를 공제
    의료비 중 국민건강보험공단으로부터 지급받은 「본인부담금 상한액
초과환급금」 상당액을 공제
  중소기업취업자 감면     감면대상 업종* 이 아님에도 감면 신청
* 제외업종(예시) : 전문서비스업, 보건업, 금융 및 보험업, 교육서비스업 등
*     ∼ 의 경 우, 해당 부양가족에 대한 인적공제(기본공제+추가공제) 뿐만 아니라, 해당 부양가족에 대한
특별공제(보험료, 교육비, 신용카드, 기부금 등) 또한 배제
==============================