# 목표

연말정산 신고 안내 문서 활용 RAG 시스템 구현

In [69]:
# 기본 경로 설정
# ===============================================================
import os
import requests

PROJECT_NUM = "14"

ROOT_DIR = os.getcwd()


try:
    from google.colab import drive, userdata
    IS_COLAB_MODE = True
    print("코랩 모드")

except ModuleNotFoundError as e:
    IS_COLAB_MODE = False
    ROOT_DIR = os.path.abspath(os.path.join(ROOT_DIR, ".."))
    os.environ["KMP_DUPLICATE_LIB_OK"] = "True"
    os.environ["TOKENIZERS_PARALLELISM"] = "false"
    print(f"로컬 모드")


DATA_DIR = os.path.join(ROOT_DIR, "data")
RAW_DIR = os.path.join(DATA_DIR, "raw")
os.makedirs(DATA_DIR, exist_ok=True)


# 환경변수 로드 설정
def get_secret(key_name: str):
    if IS_COLAB_MODE:
        return userdata.get(key_name)
    else:
        from dotenv import load_dotenv
        load_dotenv(dotenv_path=os.path.join(ROOT_DIR, ".env"))
        return os.getenv(key_name)


if IS_COLAB_MODE:
    import subprocess

    drive.mount('/content/drive')

    # 압축 파일 확보
    if "raw.tar.gz" not in os.listdir():

        headers = {
            "Authorization": f"token {get_secret('GITHUB_PAT')}",
            "Accept": "application/vnd.github.v3+json"
        }

        release_url = f"https://api.github.com/repos/wonbywondev/ML-DL-data/releases/tags/data-v{PROJECT_NUM}"

        response = requests.get(release_url, headers=headers)
        asset_id = response.json().get('assets', [])[0]["id"]

        download_url = f"https://api.github.com/repos/wonbywondev/ML-DL-data/releases/assets/{asset_id}"
        download_headers = headers.copy()
        download_headers["Accept"] = "application/octet-stream"

        with requests.get(download_url, headers=download_headers, stream=True) as r:
            r.raise_for_status()
            with open("raw.tar.gz", 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)

    print("· 압축 파일 있음")


    # 압축 해제 및 경로 처리
    if not os.path.exists(RAW_DIR):
        subprocess.run(["tar", "-xzvf", "raw.tar.gz", "-C", DATA_DIR], check=True)

    print("· 압축 해제 완료")
    print("· 환경 세팅 완료")


    DRIVE_DIR = os.path.join(ROOT_DIR, "drive", "MyDrive")
    SAVE_DIR = os.path.join(DRIVE_DIR, "runs", PROJECT_NUM)

    os.makedirs(SAVE_DIR, exist_ok=True)

PDF_PATH = os.path.join(RAW_DIR, "2024년+원천징수의무자를+위한+연말정산+신고안내.pdf")

로컬 모드

### 텍스트 데이터

In [70]:
from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader(PDF_PATH)
TEXTS_BY_PAGE = loader.load()

In [71]:
for i, page in enumerate(TEXTS_BY_PAGE):
    page.metadata = {"page": i}

In [72]:
TEXTS_BY_PAGE[2].metadata

{'page': 2}

### 표 데이터

In [73]:
from img2table.document import PDF
from img2table.ocr import TesseractOCR

pdf = PDF(
    PDF_PATH, 
    detect_rotation=False,
    pdf_text_extraction=True
)

ocr = TesseractOCR(n_threads=1, lang="eng")

TABLES_BY_PAGE = pdf.extract_tables(
    ocr=ocr,
    implicit_rows=False,
    implicit_columns=False,
    borderless_tables=False,
    min_confidence=30
)

tesseract 5.5.2
 leptonica-1.87.0
  libgif 5.2.2 : libjpeg 8d (libjpeg-turbo 3.1.3) : libpng 1.6.54 : libtiff 4.7.1 : zlib 1.2.12 : libwebp 1.6.0 : libopenjp2 2.5.4
 Found NEON
 Found libarchive 3.8.5 zlib/1.2.12 liblzma/5.8.2 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.7 expat/expat_2.7.1 CommonCrypto/system libb2/system
 Found libcurl/8.7.1 SecureTransport (LibreSSL/3.3.6) zlib/1.2.12 nghttp2/1.67.1

In [74]:
# 표 데이터 - 메타데이터 title 보정

for page_num, tables in TABLES_BY_PAGE.items():
    for table in tables:
        if table and table.title:
            if len(table.title) > 20:
                table.title = None

In [75]:
import pandas as pd
def trim_table(df: pd.DataFrame):
    df.columns = df.iloc[0]
    df = df[1:]
    df.reset_index(drop=True, inplace=True)

    return df

In [97]:
# 표 데이터 metadata에 merge

to_delete_list = list()

for page_num, tables in TABLES_BY_PAGE.items():
    if tables:
        TEXTS_BY_PAGE[page_num].metadata["table"] = {
            f"{page_num}.{i}": trim_table(table.df) for i, table in enumerate(tables)
        }
    else:
        TEXTS_BY_PAGE[page_num].metadata["table"] = None
        to_delete_list.append(page_num)

for page_num in to_delete_list:
    del TABLES_BY_PAGE[page_num]

In [96]:
TEXTS_BY_PAGE[3].metadata["table"]["3.0"]

,직계존속,직계비속,형제자매,위탁아동
0,60세 이상\n(’64.12.31.이전),20세 이하\n(’04.01.01.이후),20세 이하\n60세 이상,해당과세기간 6개월 이상\n직접 양육한 위탁아동

In [ ]:
import pandas as pd
a = TABLES_BY_PAGE[3][0].df
a.columns = a.iloc[0]
a = a[1:]

a

b = pd.DataFrame(TABLES_BY_PAGE[3][0].df[1:], columns=TABLES_BY_PAGE[3][0].df.iloc[0])

In [ ]:
count = 0

for page_num, tables in TABLES_BY_PAGE.items():
    for idx, table in enumerate(tables):

        df = table.df

        print(f"Page {page_num} - Table {idx} DataFrame: ")
        display(df)
        count += 1

Page 2 - Table 0 DataFrame:

,0,1,2,3
0,이용자,서비스,내 용,접근 경로
1,공통,원천징수(연말정산)안내 홈페이지,원천징수(연말정산)안내 홈페이지,국세청 홈페이지(www.nts.go.kr) \n국세신고안내  개인 또는 법인 ...
2,공통,연말정산 관련 질의회신 및 판례 조회,연말정산 관련 질의회신 및 판례 조회,국세법령정보시스템\n(www.hometax.go.kr  법령정보)
3,공통,인터넷 상담 및 회신,인터넷 상담 및 회신,국세청 국세상담센터\n(www.hometax.go.kr  상담/제보)
4,근로자,소득공제\n자료조회,연말정산 소득·세액공제 자료 조회,홈택스  장려금·연말정산·기부금 \n연말정산간소화\n[ 안내 ] 126-내선1-5번
5,근로자,소득공제\n자료조회,현금영수증 발행금액 조회,현금영수증\n(홈택스  전자(세금)계산서·현금영수증·\n신용카드  현금영수증(근...
6,근로자,공제신고서\n작성,간소화자료 선택 후 신고서 자동 반영,홈택스  장려금·연말정산·기부금 \n편리한 연말정산\n[ 안내 ] 126-내선1-5번
7,근로자,간편제출,작성된 공제신고서 및 증명자료\n온라인 제출,홈택스  장려금·연말정산·기부금 \n편리한 연말정산\n[ 안내 ] 126-내선1-5번
8,근로자,신고결과\n조회,과거 원천징수 영수증(지급명세서)조회\n* ’19년~’24년 및 ’25년 중 제출한...,홈택스  My홈택스  연말정산 \n지급명세서 등 제출내역\n[ 안내 ] 126...
9,근로자,안내책자\n및 영상,「근로자를 위한 연말정산 안내」 책자\n「근로자를 위한 연말정산」 동영상\n「편리한...,국세청 홈페이지(www.nts.go.kr) \n국세신고안내  개인 또는 법인 ...
10,근로자,프로그램,연말정산 모의계산 서비스,국세청 홈택스(www.hometax.go.kr) \n장려금·연말정산·기부금  편...
11,원천징수\n의무자\n(회사 등),전자신고,원천징수이행상황신고 및 환급신청\n원천세 전자신고 설명서\n지급명세서 제출\n지급명...,홈택스(www.hometax.go.kr)\n[ 안내 ] 126-내선1-3번
12,원천징수\n의무자\n(회사 등),안내책자\n및 영상,「연말정산 신고안내」 책자 및 동영상\n「편리한 연말정산 이용방법」 동영상,국세청 홈페이지(www.nts.go.kr) \n국세신고안내  개인 또는 법인 ...
13,원천징수\n의무자\n(회사 등),프로그램,퇴직소득 세액계산 프로그램\n지급명세서 전산매체 제출요령,None

Page 3 - Table 0 DataFrame:

,0,1,2,3
0,직계존속,직계비속,형제자매,위탁아동
1,60세 이상\n(’64.12.31.이전),20세 이하\n(’04.01.01.이후),20세 이하\n60세 이상,해당과세기간 6개월 이상\n직접 양육한 위탁아동

Page 3 - Table 1 DataFrame:

                             0      1           2
0  경로우대(70세 이상) (’54.12.31.이전)    장애인  부녀자(부양/기혼)
1                        100만원  200만원        50만원

Page 4 - Table 0 DataFrame:

              0      1
0  고정금리 or 비거치식     기타
1       1,800만원  800만원

Page 5 - Table 0 DataFrame:

                               0                       1
0                           기본세율                    None
1                       과세표준의 6%                과세표준의 6%
2     84만원 + (1,400만원 초과금액의 15%)    (과세표준 × 15%) - 126만원
3    624만원 + (5,000만원 초과금액의 24%)    (과세표준 × 24%) - 576만원
4  1,536만원 + (8,800만원 초과금액의 35%)  (과세표준 × 35%) - 1,544만원
5   3,706만원 + (1억5천만원 초과금액의 38%)  (과세표준 × 38%) - 1,994만원
6      9,406만원 + (3억원 초과금액의 40%)  (과세표준 × 40%) - 2,594만원
7     17,406만원 + (5억원 초과금액의 42%)  (과세표준 × 42%) - 3,594만원
8    38,406만원 + (10억원 초과금액의 45%)                    None

Page 6 - Table 0 DataFrame:

,0,1,2,3
0,기부금 종류,소득공제·세액공제 대상금액 한도,세액공제율,세액공제율
1, 정치자금기부금\n(조특법 제 76조),근로소득금액×100%,10만원 이하,100/110
2, 정치자금기부금\n(조특법 제 76조),근로소득금액×100%,10만원 초과,15%(3천만원\n초과분 25%)
3, 고향사랑기부금\n(조특법 제58조),(근로소득금액-)×100%\n(연간 500만원 한도),10만원 이하,100/110
4, 고향사랑기부금\n(조특법 제58조),(근로소득금액-)×100%\n(연간 500만원 한도),10만원 초과,15/100
5, 특례기부금,(근로소득금액--)×100%,특례기부금+일반기부금+\n우리사주조합기부금 : 15%\n(1천만원 초과분 30%)\...,특례기부금+일반기부금+\n우리사주조합기부금 : 15%\n(1천만원 초과분 30%)\...
6, 우리사주조합기부금\n(조특법 제88조의 4\n제13항),(근로소득금액---)×30%,특례기부금+일반기부금+\n우리사주조합기부금 : 15%\n(1천만원 초과분 30%)\...,특례기부금+일반기부금+\n우리사주조합기부금 : 15%\n(1천만원 초과분 30%)\...
7, 일반기부금\n(소법 제34조 제3항)\n종교단체에 기부한\n금액이 있는 경우,[(근로소득금액----)×10%\n+(근로소득금액----)의 20%와...,특례기부금+일반기부금+\n우리사주조합기부금 : 15%\n(1천만원 초과분 30%)\...,특례기부금+일반기부금+\n우리사주조합기부금 : 15%\n(1천만원 초과분 30%)\...
8,None,(근로소득금액----)×30%,특례기부금+일반기부금+\n우리사주조합기부금 : 15%\n(1천만원 초과분 30%)\...,특례기부금+일반기부금+\n우리사주조합기부금 : 15%\n(1천만원 초과분 30%)\...

Page 7 - Table 0 DataFrame:

,0,1,2,3,4,5,6
0,구 분,구 분,공 제 요 건,공 제 요 건,공 제 요 건,공 제 요 건,비 고
1,구 분,구 분,나이요건*,소득요건*,동거 요건,동거 요건,비 고
2,구 분,구 분,나이요건*,소득요건*,주민등록동거,일시퇴거 허용,비 고
3,기 본 공 제,본 인,×,×,×,None,None
4,기 본 공 제,배 우 자,×,,×,None,None
5,기 본 공 제,직계존속,60세 이상,,△\n(주거형편상 별거 허용),None,1964.12.31. 이전
6,기 본 공 제,"직계비속, 동거입양자",20세 이하,,×,None,2004. 1. 1. 이후
7,기 본 공 제,장애인 직계비속의\n장애인 배우자,×,,×,None,None
8,기 본 공 제,형제자매,60세 이상\n20세 이하,,,,1964.12.31. 이전\n2004. 1. 1. 이후
9,기 본 공 제,국민기초생활보장법에\n의한 수급자,×,,,,None
10,기 본 공 제,위탁아동,None,,None,None,None
11,추 가 공 제,장 애 인,기본공제대상자 중 장애인,기본공제대상자 중 장애인,기본공제대상자 중 장애인,기본공제대상자 중 장애인,None
12,추 가 공 제,경로우대,기본공제대상자 중 70세 이상인 자,기본공제대상자 중 70세 이상인 자,기본공제대상자 중 70세 이상인 자,기본공제대상자 중 70세 이상인 자,1954.12.31.이전
13,추 가 공 제,부 녀 자,배우자가 없는 여성근로자로서 기본공제대상 부양가족이 있는 세대주 또는\n배우자가 있...,배우자가 없는 여성근로자로서 기본공제대상 부양가족이 있는 세대주 또는\n배우자가 있...,배우자가 없는 여성근로자로서 기본공제대상 부양가족이 있는 세대주 또는\n배우자가 있...,배우자가 없는 여성근로자로서 기본공제대상 부양가족이 있는 세대주 또는\n배우자가 있...,None
14,추 가 공 제,한 부 모,배우자가 없는 자로서 부양자녀(20세 이하)가 있는자,배우자가 없는 자로서 부양자녀(20세 이하)가 있는자,배우자가 없는 자로서 부양자녀(20세 이하)가 있는자,배우자가 없는 자로서 부양자녀(20세 이하)가 있는자,None
15,연금보험료 공제,연금보험료 공제,공적연금보험료의 근로자 본인 불입분만 공제 가능,공적연금보험료의 근로자 본인 불입분만 공제 가능,공적연금보험료의 근로자 본인 불입분만 공제 가능,공적연금보험료의 근로자 본인 불입분만 공제 가능,None

Page 7 - Table 1 DataFrame:

,0,1,2,3,4,5
0,구 분,구 분,기본공제대상자의 요건,기본공제대상자의 요건,근로기간 지출한\n비용만 공제,비 고
1,구 분,구 분,나이요건 소득요건,나이요건 소득요건,근로기간 지출한\n비용만 공제,비 고
2,특별 소득공제,보 험 료,None,None,None,None
3,특별 소득공제,주택자금공제,None,None,None,None
4,그 밖의 소득공제,개인연금저축,None,None,None,None
5,그 밖의 소득공제,주택마련저축,None,None,None,None
6,그 밖의 소득공제,신용카드 등,×,,,None
7,자녀세액공제 (8세이상),자녀세액공제 (8세이상),,,-,기본공제대상 자녀\n(입양자·위탁아동·손자녀 포함)

Page 7 - Table 2 DataFrame:

         0       1  2  3  4                                           5
0  특별 세액공제  보장성보험료                                              None
1  특별 세액공제   의 료 비  ×  ×                                          None
2  특별 세액공제   교 육 비  ×      직계존속 제외 * 장애인특수교육비는 소득요건\n제한 없으며, 직계존속도 가능
3  특별 세액공제   기 부 금  ×    ×                                        None

Page 9 - Table 0 DataFrame:

,0,1
0,항목,None
1, 소득금액 기준(1백만 원)\n초과 부양가족 공제,연간 소득금액(근로·사업·양도·퇴직소득 등) 합계액이 1백만 원을\n초과하는 부양가...
2, 부양가족 중복공제,맞벌이 근로자가 자녀 등을 중복으로 공제\n형제자매가 부모님을 각각 중복하여 공제
3, 사망자에 대한 인적공제,과세기간 개시일 이전 사망한 부양가족에 대해 인적공제
4, 이혼한 배우자 등 공제,과세기간 종료일 이전 이혼한 배우자에 대해 인적공제\n이혼 후 지출한 보험료·기부금...
5, 연령 조건에 맞지 않는\n부양가족 공제,연령 조건 미충족 형제·자매에 대해 부양가족 공제
6, 교육비·의료비 등\n중복공제,"동일 부양가족의 의료비, 교육비, 신용카드 공제를 다수의 근로자가\n중복 또는 분할..."
7, 주택자금 과다공제,유주택자*임에도 주택자금(월세액 공제 포함) 공제\n* 장기주택저당차입금 이자상환액...
8, 교육비 과다공제,"자녀, 형제자매 등의 대학원 교육비 공제\n자녀 교육비를 부부가 중복으로 공제\n교..."
9, 의료비 과다공제,실손의료보험금 등 보험회사로부터 수령한 보험금으로 보전받은\n의료비를 공제\n의료비...
10, 중소기업취업자 감면,None

Page 18 - Table 0 DataFrame:

              0              1            2              3
0   상환기간 15년 이상    상환기간 15년 이상  상환기간 15년 이상   상환기간\n10년 이상
1  고정금리\n+ 비거치식  고정금리\n또는 비거치식           기타  고정금리\n또는 비거치식
2          None        1,500만원        500만원          300만원

Page 18 - Table 1 DataFrame:

              0              1            2              3
0   상환기간 15년 이상    상환기간 15년 이상  상환기간 15년 이상   상환기간\n10년 이상
1  고정금리\n+ 비거치식  고정금리\n또는 비거치식           기타  고정금리\n또는 비거치식
2          None        1,800만원        800만원           None

Page 39 - Table 0 DataFrame:

,0,1,2,3
0,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...
1,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...,성 명,주민등록번호,소득기준 초과
2,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...,이세정,820505-2******,Y
3,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...,김국세,551012-1******,Y
4,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...,2024년 귀속 소득기준 초과 부양가족 내역(소득 발생기간 : 2024년 1월~6월...

Page 40 - Table 0 DataFrame:

     0                    1                          2
0  구 분                  항 목                        일 정
1  근로자     일괄제공 신청 확인\n(동의)    ’24. 12. 1.~’25. 1. 15.
2  근로자     간소화자료 확인\n및 내려받기  ’25. 1.17.(1.20.)~ 3. 10.
3  근로자           공제 증명자료 수집           ’25.1.20.~2. 28.
4  근로자             공제신고서 제출          ’25. 2. 1.~2. 28.
5  회 사           연말정산 업무 준비              ~’24 .12. 31.
6  회 사    일괄제공 희망자 등록\n(선택)               ~’25 .1. 10.
7  회 사  서류 검토 및\n원천징수영수증 발급         ’25. 1. 20.~2. 28.
8  회 사   원천세 신고 및\n지급명세서 제출               ~’25 .3. 10.

Page 49 - Table 0 DataFrame:

,0,1,2
0,구 분,중점 확인사항,관련 근거
1,과세대상\n근로소득\n포함 항목,① ’24년 귀속 급여 중 미지급 급여\n￮ 1월부터11월까지미지급급여는해당과세기간...,소법 §135
2,과세대상\n근로소득\n포함 항목,② 일용근로자를 일반급여자로 보는 시기(소득세 집행기준 14-20-3)\n￮ 일용근...,소령 §20
3,과세대상\n근로소득\n포함 항목,③ 인정상여(예시)\n￮ 종업원에게 주택자금 등 저리 또는 무상으로 대여한 대여금의...,None

Page 50 - Table 0 DataFrame:

,0,1,2
0,구 분,중점 확인사항,관련 근거
1,과세대상\n근로소득\n포함 항목,"④ 파견수당(파견공무원, 대학병원 교수, 파견근로자 등)\n￮ 파견공무원, 대학병원...",소령 §38
2,과세대상\n근로소득\n포함 항목,⑤ 시내출장 여비와 별도로 지급받는 자기차량운전보조금\n￮ 시내출장의여비를별도로지급...,소령 §12 소기통\n12-12…1
3,과세대상\n근로소득\n포함 항목,⑥ 비과세 한도를 초과한 국외근로소득 비과세 금액과 국외 출장기간 중의 급여\n￮ ...,소령 §16
4,과세대상\n근로소득\n포함 항목,⑦ 현물식사와 별도로 지급받는 식사대\n￮ 현물식사를 근로자에게 제공하면서 급여에 ...,소기통\n12-17의2…1
5,과세대상\n근로소득\n포함 항목,⑧ 직원에게 지급하는 비과세 아닌 학자금 및 자녀교육비 지원액\n￮ 명예퇴직하는 근...,소령 §11\n소령 §38①2
6,과세대상\n근로소득\n포함 항목,⑨ 초·중·고 교사의 방과후학교 수업대가\n￮ 초·중등 교육법에 따른 교육기관이 학...,소령 §12
7,이중 근무자,￮ 소속근로자가재취직자또는2인이상으로부터근로소득이 있는자에해당하는지 확인하여\n종(...,소법 §137의2
8,전출·합병·\n법인전환 등\n고용승계자,￮ 관계회사 또는 지점 간 전출·입 근로자 등에 대한 연말정산 시 종(전) 근무지의...,"소기통\n137-0…2,3"
9,None,￮ 외국인 단일세율(19%) 또는 외국인기술자 세액감면은 외국인에게 적용\n(대한민...,None

Page 62 - Table 0 DataFrame:

      0     1           2
0   제2부   제2부        None
1  None  None  근로소득\n연말정산

Page 80 - Table 0 DataFrame:

,0,1,2,3
0,직종,직종,직종,한국표준\n직업분류번호
1,연번,대분류,"중분류, 소분류 또는 세분류",한국표준\n직업분류번호
2,1,서비스 종사자,돌봄 서비스직\n미용 관련 서비스직\n여가 및 관광 서비스직\n숙박시설 서비스직\n...,4211\n422 4321\n4322\n44
3,2,판매 종사자,매장 판매 및 상품 대여직\n통신 관련 판매직,52 531
4,3,기능원 및 관련\n기능 종사자,식품가공 관련 기능직\n섬유·의복 및 가죽 관련 기능직\n목재·가구·악기 및 간판 ...,71 72 73 74 75 76 77 78 79
5,4,장치·기계 조작 및\n조립 종사자,식품가공 관련 기계 조작직\n섬유 및 신발 관련 기계 조작직\n화학 관련 기계 조작...,81 82 83 84 85 86 87 88 89
6,5,단순노무 종사자,건설 및 광업 관련 단순 노무직\n운송 관련 단순 노무직\n제조 관련 단순 노무직\...,91 92 93 94 95 99

Page 96 - Table 0 DataFrame:

,0,1,2
0,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...
1,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,내 용
2,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,신고분납부,홈택스에서 신고한 세금신고분 납부
3,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,고지분납부,고지한 내역을 조회하여 납부
4,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,신고하거나 고지받은 세금에 대하여 자진납부
5,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,다른 사람의 세금을 납부
6,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...,○ 홈택스로 전송한 신고서를 삭제하려면 홈택스에서 ‘전자신고 삭제요청서’를 작성하여...

Page 116 - Table 0 DataFrame:

           0          1                               2
0       소득종류       소득종류                         소득금액 계산
1  ① 종 합 소 득       근로소득  총급여액(연간근로소득 -\n비과세소득) - 근로소득공제
2  ① 종 합 소 득       연금소득                   총연금액 - 연금소득공제
3  ① 종 합 소 득       사업소득                    총수입금액 - 필요경비
4  ① 종 합 소 득       기타소득                    총수입금액 - 필요경비
5  ① 종 합 소 득  이자·\n배당소득                           총수입금액
6  ① 종 합 소 득         소계      위의 소득금액의 합계액이\n종합소득금액이 된다.
7          ②       None                   퇴직소득 = 퇴직소득금액
8     ③ 양도소득     ③ 양도소득        양도가액 - 필요경비 -\n장기보유 특별공제

Page 119 - Table 0 DataFrame:

,0,1,2,3,4
0,소득공제,소득공제,공제항목,공제한도액,공제한도액
1,보험료,"건강보험, 고용보험,\n노인장기요양보험",본인부담 보험료,None,None
2,주택자금,① 주택마련저축,"청약저축·주택청약종합저축 납입액(300만원\n한도), 근로자주택마련저축 납입액(18...",연 400만원\n[①＋②],"600만원~2,000만원"
3,주택자금,② 주택임차차입금\n원리금 상환액,무주택 세대의 세대주(세대원포함)가 국민주택\n규모의 주택을 임차하기 위한 차입금의...,연 400만원\n[①＋②],"600만원~2,000만원"
4,주택자금,③ 장기주택저당\n차입금 이자상환액,무주택 또는 1주택 보유세대의 세대주(세대원\n포함)인 근로자가 기준시가 6억원 이...,None,"600만원~2,000만원"
5,개인연금저축,납입액,’00.12.31 이전 가입(납입액의 40%),None,72만원
6,투자조합\n출자 등 공제,’21년 이후 투자,"투자금액의 10%(개인이 벤처기업·벤처\n조합에 투자하는 경우 100%, 70, 30%)",None,50%\n공제금액은\n초과할 수 없음)
7,None,"신용카드, 현금영수증\n직불카드, 선불카드 등",신용카드 등 사용금액(중고차 구입금액의\n10% 포함)이 총급여액의 25%를 초과한...,"총급여액 7천만원 이하는\n300만원, 총급여 7천만원\n초과자는 250만원 한도\...","총급여액 7천만원 이하는\n300만원, 총급여 7천만원\n초과자는 250만원 한도\..."

Page 120 - Table 0 DataFrame:

                      0                                                  1
0                  None                                               공제항목
1                  공제부금                              소기업·소상공인 공제부금에 납입한 금액
2                   출연금                       우리사주 취득을 위해 우리사주조합에 출연한\n출연금
3                 임금삭감액  (직전 과세연도의 해당 근로자 연간 임금총액\n- 해당 과세연도의 해당 근로자 연간...
4      장기집합투자증권\n저축 납입액  가입 시 직전 과세기간의 총급여액 5천만원\n(해당 과세기간에는 8천만원)이하인 근...
5  청년형 장기집합투자\n증권저축 납입액  총급여액 8천만원(종합소득금액 6,700만원)\n이하인 근로자가 청년형 장기집합투자...

Page 129 - Table 0 DataFrame:

        0                       1        2
0    None                    상환방식     None
1  15년 이상   고정금리 방식이고 비거치식 분할상환방식  2,000만원
2  15년 이상  고정금리 방식이거나 비거치식 분할상환방식  1,800만원
3  15년 이상                      기타    800만원
4    None  고정금리 방식이거나 비거치식 분할상환방식     None

Page 129 - Table 1 DataFrame:

,0,1,2,3
0,공제종류,공제금액(한도액),공제금액(한도액),공제금액(한도액)
1,㉠ 장기주택저당\n차입금이자상환액,이자상환액 전액,이자상환액 전액,※ 전체 (㉠+㉡+㉢) 한도액\n㉠이 2012.1.1. 이후 차입·상환기간 연장인 ...
2,㉡\n주택임차차입금\n원리금상환액,원리금\n상환액\n× 40%,"공제한도：\nMin(①, ②)\n①：㉡+㉢\n②：400만원",※ 전체 (㉠+㉡+㉢) 한도액\n㉠이 2012.1.1. 이후 차입·상환기간 연장인 ...
3,None,저축 납입액\n× 40%,"공제한도：\nMin(①, ②)\n①：㉡+㉢\n②：400만원",※ 전체 (㉠+㉡+㉢) 한도액\n㉠이 2012.1.1. 이후 차입·상환기간 연장인 ...

Page 134 - Table 0 DataFrame:

           0                                                  1
0       None                                       개인연금저축(소득공제)
1       가입기간                                   2000.12.31 이전 가입
2       가입대상                                           만 20세 이상
3       납입금액                                 분기마다 300만원 이내에서 납입
4       납입기간                                             10년 이상
5  소득공제 등 비율                                        연간 납입액의 40%
6    공제금액 한도                                       연 72만원(소득공제)
7       None  은행 또는 투자신탁회사의 신탁상품, 보험\n회사의 보험상품, 우체국 보험, 수협의 ...

Page 135 - Table 0 DataFrame:

         0         1
0  4천만원 이하  4천만원~1억원
1    500만원     300만원

Page 138 - Table 0 DataFrame:

,0,1,2,3
0,저축 상품,해지추징세액*,추징 기간,중도해지 해당연도\n불입금액
1,연금저축(’13.2.28. 이전 가입),저축불입액의 2%,5년,▪ 소득공제 제외\n▪ 해지추징세액 대상\n제외
2,장기주택마련저축,저축불입액의 4% (1년 이내 8%),5년,▪ 소득공제 제외\n▪ 해지추징세액 대상\n제외
3,None,저축불입액의 6%,5년,▪ 소득공제 제외\n▪ 해지추징세액 대상\n제외

Page 150 - Table 0 DataFrame:

               0              1              2          3
0            구 분            구 분      특별세액공제 항목       None
1      신용카드로 결제한           None    의료비 세액공제 가능  신용카드공제 가능
2      신용카드로 결제한           None    보험료 세액공제 가능  신용카드공제 불가
3  신용카드로 결제한 학원비         취학전 아동  교육비 세액공제 가능 *  신용카드공제 가능
4  신용카드로 결제한 학원비            그 외    교육비 세액공제 불가  신용카드공제 가능
5      신용카드로 결제한           None    교육비 세액공제 가능  신용카드공제 가능
6  신용카드로 결제한 기부금  신용카드로 결제한 기부금    기부금 세액공제 가능       None

Page 164 - Table 0 DataFrame:

,0,1,2,3
0,<청년 중소기업 취업자에 대한 소득세 감면 개정 세법 적용>,<청년 중소기업 취업자에 대한 소득세 감면 개정 세법 적용>,<청년 중소기업 취업자에 대한 소득세 감면 개정 세법 적용>,<청년 중소기업 취업자에 대한 소득세 감면 개정 세법 적용>
1,감면 요건,당초,개정,비고
2,감면기간,3년,5년,취업일부터 기산
3,감면율,70%,90%,None
4,연령요건,15세~29세,15세~34세,근로계약 체결당시
5,일몰기한,2023년,2026년,None

Page 169 - Table 0 DataFrame:

,0,1
0,※ 외국인기술자 특례배제 요건 보완(조특령 §16),※ 외국인기술자 특례배제 요건 보완(조특령 §16)
1,종 전,개 정
2,○ 과세연도 종료일(12.31.)기준으로 외국인 기술자가\n해당 기업과 특수관계 *...,○근로기간중외국인기술자가해당 기업과 특수관계에\n있는 경우는 적용 배제
3,* ｢국세기본법 시행령｣ §1의2에 따른 친족관계 또는 경영지배관계,* ｢국세기본법 시행령｣ §1의2에 따른 친족관계 또는 경영지배관계

Page 171 - Table 0 DataFrame:

        0     1     2
0    None  중소기업  중견기업
1  청년 근로자   90%   50%
2    None   50%  None

Page 177 - Table 0 DataFrame:

               0                        1     2
0  종합소득금액 (총급여액)  세액공제 대상 납입한도\n(퇴직연금 포함)   공제율
1           None           600만원\n(900만원)  None

Page 181 - Table 0 DataFrame:

,0,1,2,3,4,5
0,세액공제,세액공제,세액공제,공제항목,세액공제\n대상금액 한도,공제율
1,보험료,보장성보험,보장성보험,"생명보험, 상해보험 등의 보장성보험료",연 100만원,12%
2,보험료,장애인전용\n보장성보험,장애인전용\n보장성보험,장애인을 피보험자 또는 수익자로 하는\n장애인전용보장성보험료,연 100만원,15%
3,의료비,"㉮ 본인, 장애인, 만 65세\n이상자, 6세 이하자,\n미숙아및선천성이상아,\n건...","㉮ 본인, 장애인, 만 65세\n이상자, 6세 이하자,\n미숙아및선천성이상아,\n건...","의료비, 의약품, 안경 구입비(50만원 이내),\n산후조리원비용(출산1회당200만원...",총급여 3% 초과분\n공제대상\n㉮ 한도 제한 없음\n㉯ 연700만원 한도,15%(미숙아 ·\n선천성이상아\n의료비 : 20%\n난임시술비 :\n30%)
4,의료비,㉯ 그 외 부양가족,㉯ 그 외 부양가족,"의료비, 의약품, 안경 구입비(50만원 이내),\n산후조리원비용(출산1회당200만원...",총급여 3% 초과분\n공제대상\n㉮ 한도 제한 없음\n㉯ 연700만원 한도,15%(미숙아 ·\n선천성이상아\n의료비 : 20%\n난임시술비 :\n30%)
5,교육비,본인,본인,"대학원, 대학, 시간제과정, 직업능력개발훈\n련시설, 학자금대출 상환액 등",전액,15%
6,교육비,취학전 아동,취학전 아동,"어린이집·유치원·학원·체육시설 수업료,\n급식비, 방과후과정 수업료(도서구입비 포함)",1명당 연 300만원,15%
7,교육비,초·중·고등학생,초·중·고등학생,"등록금, 입학금, 대학입학전형료, 수능응시료,\n급식비, 교과서대금, 방과후학교 수...",1명당 연\n300만원,15%
8,교육비,대학생,대학생,"등록금, 입학금",1명당 연 900만원,15%
9,교육비,장애인,장애인,장애인 재활교육비,전액,15%
10,기부금,정치자금 기부금,정치자금 기부금,정당기부 등,근로소득금액\n전액,"10만원 이하\n(100/110)\n10만원 초과\n(15%, 25%)"
11,기부금,고향사랑 기부금,고향사랑 기부금,지방자치단체,500만원,10만원 이하\n(100/110)\n10만원 초과\n(15%)
12,기부금,특례기부금,특례기부금,"국방헌금, 위문금품 등",근로소득금액\n전액,1천만원 이하\n15%\n1천만원 초과\n30%\n3천만원 초과\n40%
13,기부금,우리사주조합기부금,우리사주조합기부금,우리사주조합원이 아닌 사람이 우리사주\n조합에 지출하는 기부금,근로소득금액의\n30%,1천만원 이하\n15%\n1천만원 초과\n30%\n3천만원 초과\n40%
14,기부금,일반 기부금,종교단체 외,지정된 사회·복지·문화·예술단체,근로소득금액의\n30%,1천만원 이하\n15%\n1천만원 초과\n30%\n3천만원 초과\n40%
15,기부금,일반 기부금,종교단체,주무관청에 등록된 종교단체,근로소득금액의\n10%,1천만원 이하\n15%\n1천만원 초과\n30%\n3천만원 초과\n40%

Page 183 - Table 0 DataFrame:

            0             1      2
0         구 분  세액공제 대상금액 한도  세액공제율
1  보장성보험의 보험료    연 100만원 한도    12%
2        None    연 100만원 한도   None

Page 198 - Table 0 DataFrame:

            0                   1                    2
0        None                 내 용                 None
1          본인  대학원 (1학기 이상의 교육과정)            교육비 800만원
2          자녀    초등학교 취학 전 자녀(1명)            보육료 120만원
3          자녀            초등학생(1명)  학원 및 체육시설 수강료 120만원
4          자녀             중학생(1명)        중학교 수업료 300만원
5  형제자매\n(3명)       대학원생(처남, 26세)              1,000만원
6  형제자매\n(3명)        대학생(처남, 22세)                900만원
7  형제자매\n(3명)        대학생(동생, 25세)                 None

Page 198 - Table 1 DataFrame:

,0,1
0,❍ 학자금 대출 상환액 교육비 세액공제\n｢한국장학재단 설립 등에 관한 법률｣ 등에...,❍ 학자금 대출 상환액 교육비 세액공제\n｢한국장학재단 설립 등에 관한 법률｣ 등에...
1,❍ 학자금 대출 상환액 교육비 세액공제\n｢한국장학재단 설립 등에 관한 법률｣ 등에...,｢한국장학재단 설립 등에 관한 법률｣ 등에 따른 학자금 대출(등록금에 대한 대출)의...
2,❍ 학자금 대출 상환액 교육비 세액공제\n｢한국장학재단 설립 등에 관한 법률｣ 등에...,❍ 학자금 대출 상환액 교육비 세액공제\n｢한국장학재단 설립 등에 관한 법률｣ 등에...

Page 199 - Table 0 DataFrame:

,0,1,2
0,None,소득공제·세액공제 대상금액 한도,None
1,① 정치자금기부금 (조특법 제76조),근로소득금액 × 100%,10만원 이하：100/110\n10만원 초과：15%\n(3천만원 초과분 25%)
2,None,(근로소득금액 － ①) × 100%\n(연간 한도 500만원),None

Page 200 - Table 0 DataFrame:

,0,1
0,None,소득공제·세액공제 대상금액 한도
1,③ 특례기부금\n(소법 제34조 제2항 제1호),(근로소득금액 － ①－ ②) × 100%
2,④ 우리사주조합기부금\n(조특법 제88조의4 제13항),(근로소득금액 － ① － ②－ ③)\n× 30%
3,⑤ 일반기부금\n(소법 제34조 제3항 제1호)\n종교단체에 기부한 금액이 있는 경우,[근로소득금액 － ① － ② － ③ - ④]\n× 10% + [(근로소득금액 － ①...
4,None,(근로소득금액 － ① － ② － ③ － ④)\n× 30%

Page 225 - Table 0 DataFrame:

      0      1               2      3              4
0  None     나이          주민등록번호     성명           None
1   배우자  만 43세  810701-2******  황 정 연  사업소득(1,000만원)
2  자녀 1  만 19세  050501-1******  이 태 현           고등학생
3  자녀 2   만 6세  181224-4******  이 태 희         취학전 아동
4  None   만 0세  241030-3******  이 태 영           None

Page 225 - Table 1 DataFrame:

            0        1          2         3
0     월 급여 내역  월 급여 내역   상여금 등 내역  상여금 등 내역
1         구 분      금 액        구 분       금 액
2       기 본 급    250만원     연간 상여금   2,200만원
3         식 대     20만원     자녀 수업료     250만원
4      시간외 근무     40만원     비과세학자금     300만원
5  6세 이하 보육수당     30만원     성과급여 *     190만원
6      배우자 수당     25만원  출산지원금(1회)     500만원
7        None    365만원        합 계      None

Page 226 - Table 0 DataFrame:

          0               1      2       3
0   지출내역 구분         지출내역 구분    지출액     대상자
1       보험료           건강보험료  130만원      본인
2       보험료       노인장기요양보험료   40만원      본인
3       보험료           종신보험료  150만원  태희(자녀)
4       보험료           종신보험료  150만원  태영(자녀)
5       보험료           자동차보험  120만원     배우자
6       의료비             수술비  250만원     배우자
7       의료비        보약(건강증진)  150만원      본인
8       의료비           입원치료비  130만원      본인
9       의료비           난임시술비  100만원     배우자
10      의료비         산후조리원비용  220만원     배우자
11      의료비         시력교정용안경   55만원      본인
12      교육비             수업료  250만원  태현(자녀)
13      교육비           교복구입비   35만원  태현(자녀)
14      교육비           학원수강료  120만원  태현(자녀)
15      교육비           체험학습비   50만원  태현(자녀)
16      교육비           수능응시료   20만원  태현(자녀)
17      교육비            체육시설  120만원  태희(자녀)
18      교육비       대학원(박사과정)  300만원      본인
19      기부금         정치자금기부금   20만원      본인
20      기부금         고향사랑기부금   10만원      본인
21      기부금           특례기부금   50만원      본인
22      기부금          우리사주조합   50만원      본인
23      기부금          노인복지시설   50만원     배우자
24    연금보험료            국민연금  250만원      본인
25    연금보험료            퇴직연금  100만원      본인
26    연금보험료            연금저축  200만원      본인
27     None  장기주택저당차입금이자상환액  100만원      본인

Page 227 - Table 0 DataFrame:

            0               1                  2
0        None           연간사용액               None
1  신용카드\n대중교통  1,500만원\n200만원  전기료, 수도료 300만원 포함
2       현금영수증         1,000만원      전통시장 300만원 포함
3        체크카드           600만원     도서공연비 100만원 포함
4        None         3,100만원               None

Page 227 - Table 1 DataFrame:

            0           1       2     3
0        None  지급명세서 기재대상  기재란 번호  None
1          식대           ○   ￾￾-40   P01
2  6세 이하 보육수당           ○    ￾￾-2   Q02
3      비과세학자금           ○    ￾￾-5   G01
4        None           ○    ￾￾-3  None

Page 228 - Table 0 DataFrame:

            0      1
0        공제한도   납입금액
1  근로자 부담분 전액  250만원

Page 228 - Table 1 DataFrame:

       0      1      2     3      4
0   None   납입금액   자료구분  공제한도   None
1  건강보험료  130만원  국세청자료    없음  130만원
2   None   40만원  국세청자료    없음   None

Page 230 - Table 0 DataFrame:

      0                  1      2          3
0  None               공제한도   납입금액  세액공제 대상금액
1  연금저축            연 600만원  200만원      200만원
2  퇴직연금  연금저축과 합하여 연 900만원  100만원      100만원
3  None               None  300만원      300만원

Page 230 - Table 1 DataFrame:

       0      1       2                        3                        4
0   None   납입금액    자료구분              세액공제 대상금액 *                     None
1  종신보험료  300만원  국세청 자료                    100만원                     12만원
2   None  120만원  국세청 자료  소득요건 초과 배우자의 보험료로 공제 제외  소득요건 초과 배우자의 보험료로 공제 제외

Page 231 - Table 0 DataFrame:

,0,1,2,3,4,5,6
0,구분,수술,입원치료비,시력교정용안경,산후조리원 비용,세액공제\n대상금액,세액공제액
1,"본인,\n난임시술비",None,230만원*,55만원 →\n50만원한도,None,280.0만원,"950,700원"
2,그 외\n부양가족,250만원,None,None,220만원 →\n한도 200만원,253.8만원,"950,700원"
3,None,250만원,230만원,50만원,200만원,533.8만원,"950,700원"

Page 231 - Table 1 DataFrame:

       0      1     2      3
0  250만원  230만원  None  200만원
1   None   None  50만원   None

Page 231 - Table 2 DataFrame:

            0                1       2      3           4
0        None           교육비 내역    자료구분     금액        None
1  이태희(취학전아동)          체육시설수강료   기타 자료  120만원        공제대상
2   이태현(고등학생)              수업료  국세청 자료  250만원        공제대상
3   이태현(고등학생)            교복구입비   기타 자료   35만원        공제대상
4   이태현(고등학생)            체험학습비   기타 자료   50만원  공제대상(30만원)
5   이태현(고등학생)            수능응시료  국세청 자료   20만원        공제대상
6   이태현(고등학생)              학원비       -  120만원     공제대상 아님
7        None  대학원 수강료(비과세학자금)       -  300만원        None

Page 231 - Table 3 DataFrame:

        0      1        2      3          4        5
0    None   공제대상  공제대상 제외  공제 한도  세액공제 대상금액     None
1   취학전아동  120만원     None  300만원      120만원  630,000
2    고등학생  335만원    120만원  300만원      300만원  630,000
3  근로자 본인   None    300만원     없음          -  630,000
4    None  455만원    420만원   None      420만원  630,000

Page 232 - Table 0 DataFrame:

         0    1       2     3          4          5
0     None  기부자  공제대상여부  기부금액  세액공제 대상금액  세액공제 대상금액
1  정치자금기부금  이강모       여  20만원    10만원 이하       10만원
2  정치자금기부금  이강모       여  20만원    10만원 초과       10만원
3  고향사랑기부금  이강모       여  10만원    10만원 이하       10만원
4    특례기부금  이강모       여  50만원       50만원       50만원
5   우리사주조합  이강모       부  50만원          -          -
6     None  황정연       부  50만원          -          -

Page 233 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7
0,관 계,관 계,관 계,기본 공제,추가공제,추가공제,추가공제,추가공제
1,관 계,관 계,관 계,기본 공제,부녀자,장애인,경로 우대,한부모
2,None,None,0,-,· 기혼여성\n· 부양가족있는세대주인여성\n(종합소득금액3천만원 이하),장애인\n등록증\n∙ 장애인\n증명서\n∙ 상이자\n증명을\n제출한\n자,70세 이상,· 배우자 없이\n자녀를 부양\n하는 자
3,소득금액\n100만원\n이하 (근로소득만\n있는 자는 총급여\n500만원),소득자 직계존속,1,60세 이상,None,장애인\n등록증\n∙ 장애인\n증명서\n∙ 상이자\n증명을\n제출한\n자,70세 이상,None
4,소득금액\n100만원\n이하 (근로소득만\n있는 자는 총급여\n500만원),배우자 직계존속,2,60세 이상,None,장애인\n등록증\n∙ 장애인\n증명서\n∙ 상이자\n증명을\n제출한\n자,70세 이상,None
5,소득금액\n100만원\n이하 (근로소득만\n있는 자는 총급여\n500만원),배우자,3,-,None,장애인\n등록증\n∙ 장애인\n증명서\n∙ 상이자\n증명을\n제출한\n자,70세 이상,None
6,소득금액\n100만원\n이하 (근로소득만\n있는 자는 총급여\n500만원),직계비속 자녀,4,20세 이하,None,장애인\n등록증\n∙ 장애인\n증명서\n∙ 상이자\n증명을\n제출한\n자,70세 이상,None
7,소득금액\n100만원\n이하 (근로소득만\n있는 자는 총급여\n500만원),직계비속 자녀외,5,20세 이하,None,장애인\n등록증\n∙ 장애인\n증명서\n∙ 상이자\n증명을\n제출한\n자,70세 이상,None
8,소득금액\n100만원\n이하 (근로소득만\n있는 자는 총급여\n500만원),형제자매,6,20세 이하\n60세 이상,None,장애인\n등록증\n∙ 장애인\n증명서\n∙ 상이자\n증명을\n제출한\n자,70세 이상,None
9,소득금액\n100만원\n이하 (근로소득만\n있는 자는 총급여\n500만원),수급자,7,기초생활수급자,None,장애인\n등록증\n∙ 장애인\n증명서\n∙ 상이자\n증명을\n제출한\n자,70세 이상,None
10,소득금액\n100만원\n이하 (근로소득만\n있는 자는 총급여\n500만원),위탁아동,8,위탁아동,None,장애인\n등록증\n∙ 장애인\n증명서\n∙ 상이자\n증명을\n제출한\n자,70세 이상,None

Page 234 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,80% 중 선택할 수
1,인 적 공 제 및 소 득 · 세 액 공 제,인적공제 항목,인적공제 항목,인적공제 항목,인적공제 항목,인적공제 항목,인적공제 항목,인적공제 항목,인적공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목
2,인 적 공 제 및 소 득 · 세 액 공 제,관계 코드,성 명,소득금액\n기준,기본공제,기본공제,경로 우대,결혼 세액 공제,출산 입양,자료 구분,보험료,보험료,보험료,보험료,None,None,None,None
3,인 적 공 제 및 소 득 · 세 액 공 제,내·외\n국인,주민등록\n번호,(백만원)\n초과여부,부녀자,한부모,장애인,결혼 세액 공제,자녀,자료 구분,건강,고용,보장성,장애인\n전용 보장성,일반,미숙아\n선천성\n이상아,난임 시술비,"6세이하,\n65세이상,\n장애인, 건강보헝\n산정특례자"
4,인 적 공 제 및 소 득 · 세 액 공 제,인적공제 항목에 해당하는\n인원수를 적습니다.,인적공제 항목에 해당하는\n인원수를 적습니다.,인적공제 항목에 해당하는\n인원수를 적습니다.,None,None,None,None,None,국세청,None,None,"3,000,000",None,"6,000,000",None,None,None
5,인 적 공 제 및 소 득 · 세 액 공 제,인적공제 항목에 해당하는\n인원수를 적습니다.,인적공제 항목에 해당하는\n인원수를 적습니다.,인적공제 항목에 해당하는\n인원수를 적습니다.,None,None,None,None,None,기타,"1,700,000",None,None,None,"550,000",None,"1,000,000",None
6,인 적 공 제 및 소 득 · 세 액 공 제,0,None,None,○,○,None,None,None,국세청,None,None,None,None,"1,300,000",None,None,None
7,인 적 공 제 및 소 득 · 세 액 공 제,None,(근로자\n본인),None,None,None,None,None,None,기타,"1,700,000",None,None,None,"550,000",None,None,None
8,인 적 공 제 및 소 득 · 세 액 공 제,3,황정연,✓,None,None,None,None,None,국세청,None,None,None,None,"4,700,000",None,None,None
9,인 적 공 제 및 소 득 · 세 액 공 제,1,810701\n-2******,✓,None,None,None,None,None,기타,None,None,None,None,None,None,"1,000,000",None
10,인 적 공 제 및 소 득 · 세 액 공 제,4,이태현,None,○,○,None,None,None,국세청,None,None,None,None,None,None,None,None
11,인 적 공 제 및 소 득 · 세 액 공 제,1,050501\n-1******,None,None,None,None,None,○,기타,None,None,None,None,None,None,None,None
12,인 적 공 제 및 소 득 · 세 액 공 제,4,이태희,None,○,○,None,None,None,국세청,None,None,"1,500,000",None,None,None,None,None
13,인 적 공 제 및 소 득 · 세 액 공 제,1,181224\n-4******,None,None,None,None,None,None,기타,None,None,None,None,None,None,None,None
14,인 적 공 제 및 소 득 · 세 액 공 제,4,이태영,None,○,○,None,None,○,국세청,None,None,"1,500,000",None,None,None,None,None
15,인 적 공 제 및 소 득 · 세 액 공 제,1,241030\n-3******,None,None,None,None,None,None,기타,None,None,None,None,None,None,None,None

Page 234 - Table 1 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11
0,명 세,자료 구분,교육비,교육비,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액
1,명 세,자료 구분,일반,장애인\n특수교육비,신용카드,직불카드등,현금영수증,도서공연등사용분\n(총급여 7천만원\n이하자만 기재),전통시장\n사용분,대중교통\n사용분,소비증가분,소비증가분
2,명 세,자료 구분,일반,장애인\n특수교육비,신용카드,직불카드등,현금영수증,도서공연등사용분\n(총급여 7천만원\n이하자만 기재),전통시장\n사용분,대중교통\n사용분,2023년\n전체 사용분,2024년\n전체 사용분
3,명 세,국세청계,"2,700,000",None,"10,000,000","5,000,000","7,000,000","1,000,000","3,000,000","2,000,000","25,000,000","28,000,000"
4,명 세,기타계,"1,850,000",None,None,None,None,None,None,None,None,None
5,명 세,국세청,"2,700,000",None,"10,000,000","5,000,000","7,000,000","1,000,000","3,000,000","2,000,000",None,None
6,명 세,기타,"1,850,000",None,None,None,None,None,None,None,None,None
7,명 세,국세청,None,None,None,None,None,None,None,None,None,None
8,명 세,기타,None,None,None,None,None,None,None,None,None,None

Page 234 - Table 2 DataFrame:

,0,1,2,3,4,5
0,구 분,관계 코드,구 분,관계 코드,구 분,관계 코드
1,소득자 본인(｢소득세법｣ §50①1),0,소득자의 직계존속(｢소득세법｣ §50①3가)\n직계비속(자녀 및 손자녀·입양자)(｢...,1,배우자의 직계존속(｢소득세법｣ §50①3가),2
2,배우자(｢소득세법｣ §50①2),3,소득자의 직계존속(｢소득세법｣ §50①3가)\n직계비속(자녀 및 손자녀·입양자)(｢...,4,직계비속(코드 4 제외)(｢소득세법｣ §50①3나),5*
3,형제자매(｢소득세법｣ §50①3다),6,수급자(코드1~6제외)(｢소득세법｣ §50①3라),7,위탁아동(｢소득세법｣ §50①3마),8

Page 234 - Table 3 DataFrame:

,0,1,2,3
0,구분,｢장애인복지법｣에 따른 장애인,｢국가유공자 등 예우 및 지원에 관한 법률｣에 따른\n상이자 및 이와 유사한 자로서...,그 밖에 항시 치료를 요하는 중증환자
1,해당코드,1,2,3

Page 235 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9
0,구분,구분,지출명세,지출명세,지출명세,지출명세,지출명세,지출구분,금 액,한도액
1,Ⅱ 연금 보험료\n공제,"연금보험료\n(국민연금, 공무원\n연금, 군인연금,\n교직원연금 등)",국민연금보험료,국민연금보험료,None,None,종(전)근무지,보험료,None,전액
2,Ⅱ 연금 보험료\n공제,"연금보험료\n(국민연금, 공무원\n연금, 군인연금,\n교직원연금 등)",국민연금보험료,국민연금보험료,None,None,주(현)근무지,보험료,"2,500,000",전액
3,Ⅱ 연금 보험료\n공제,"연금보험료\n(국민연금, 공무원\n연금, 군인연금,\n교직원연금 등)",국민연금보험료 외의\n공적연금보험료,국민연금보험료 외의\n공적연금보험료,None,None,종(전)근무지,보험료,None,전액
4,Ⅱ 연금 보험료\n공제,"연금보험료\n(국민연금, 공무원\n연금, 군인연금,\n교직원연금 등)",국민연금보험료 외의\n공적연금보험료,국민연금보험료 외의\n공적연금보험료,None,None,주(현)근무지,보험료,None,전액
5,Ⅱ 연금 보험료\n공제,"연금보험료\n(국민연금, 공무원\n연금, 군인연금,\n교직원연금 등)",연금보험료 계,연금보험료 계,연금보험료 계,연금보험료 계,연금보험료 계,None,"2,500,000",None
6,Ⅲ 특 별 소 득 공 제,보험료,국민건강보험(노인\n장기요양보험 포함),국민건강보험(노인\n장기요양보험 포함),None,None,종(전)근무지,보험료,None,전액
7,Ⅲ 특 별 소 득 공 제,보험료,국민건강보험(노인\n장기요양보험 포함),국민건강보험(노인\n장기요양보험 포함),None,None,주(현)근무지,보험료,"1,700,000",전액
8,Ⅲ 특 별 소 득 공 제,보험료,고용보험,고용보험,None,None,종(전)근무지,보험료,None,전액
9,Ⅲ 특 별 소 득 공 제,보험료,고용보험,고용보험,None,None,주(현)근무지,보험료,None,전액
10,Ⅲ 특 별 소 득 공 제,보험료,보험료 계,보험료 계,보험료 계,보험료 계,보험료 계,None,"1,700,000",None
11,Ⅲ 특 별 소 득 공 제,주택자금,주택임차차입금,주택임차차입금,대출기관차입,대출기관차입,대출기관차입,원리금상환액,None,작성방법 참조
12,Ⅲ 특 별 소 득 공 제,주택자금,주택임차차입금,주택임차차입금,거주자 차입,거주자 차입,거주자 차입,원리금상환액,None,작성방법 참조
13,Ⅲ 특 별 소 득 공 제,주택자금,장기 주택 저당 차입금,2011년 이전\n차입분,15년 미만,15년 미만,15년 미만,이자 상환액,None,작성방법 참조
14,Ⅲ 특 별 소 득 공 제,주택자금,장기 주택 저당 차입금,2011년 이전\n차입분,15년~29년,15년~29년,15년~29년,이자 상환액,None,작성방법 참조
15,Ⅲ 특 별 소 득 공 제,주택자금,장기 주택 저당 차입금,2011년 이전\n차입분,30년 이상,30년 이상,30년 이상,이자 상환액,None,작성방법 참조
16,Ⅲ 특 별 소 득 공 제,주택자금,장기 주택 저당 차입금,2011년 이전\n차입분,15년\n이상,"고정금리이면서,\n비거치상환 대출","고정금리이면서,\n비거치상환 대출",이자 상환액,None,작성방법 참조
17,Ⅲ 특 별 소 득 공 제,주택자금,장기 주택 저당 차입금,2011년 이전\n차입분,15년\n이상,"고정금리이거나,\n비거치상환 대출","고정금리이거나,\n비거치상환 대출",이자 상환액,None,작성방법 참조
18,Ⅲ 특 별 소 득 공 제,주택자금,장기 주택 저당 차입금,2012년 이후\n차입분,15년\n이상,"고정금리이면서,\n비거치상환 대출","고정금리이면서,\n비거치상환 대출",이자 상환액,"1,000,000",작성방법 참조
19,Ⅲ 특 별 소 득 공 제,주택자금,장기 주택 저당 차입금,2012년 이후\n차입분,15년\n이상,"고정금리이거나,\n비거치상환 대출","고정금리이거나,\n비거치상환 대출",이자 상환액,None,작성방법 참조
20,Ⅲ 특 별 소 득 공 제,주택자금,장기 주택 저당 차입금,2012년 이후\n차입분,15년\n이상,기타 대출,기타 대출,이자 상환액,None,작성방법 참조
21,Ⅲ 특 별 소 득 공 제,주택자금,장기 주택 저당 차입금,2012년 이후\n차입분,10년\n~ 15년,"고정금리이거나,\n비거치상환 대출","고정금리이거나,\n비거치상환 대출",이자 상환액,None,작성방법 참조
22,Ⅲ 특 별 소 득 공 제,주택자금,주택자금 공제액 계,주택자금 공제액 계,주택자금 공제액 계,주택자금 공제액 계,주택자금 공제액 계,None,"1,000,000",None
23,Ⅳ 그 밖 의 소 득 공 제,개인연금저축(2000년 이전 가입),개인연금저축(2000년 이전 가입),개인연금저축(2000년 이전 가입),개인연금저축(2000년 이전 가입),개인연금저축(2000년 이전 가입),개인연금저축(2000년 이전 가입),납입금액,None,납입액 40%와72만원
24,Ⅳ 그 밖 의 소 득 공 제,소기업·소상공인 공제부금,소기업·소상공인 공제부금,소기업·소상공인 공제부금,소기업·소상공인 공제부금,소기업·소상공인 공제부금,소기업·소상공인 공제부금,납입금액,None,작성방법 참조
25,Ⅳ 그 밖 의 소 득 공 제,주택마련저축,청약저축,청약저축,청약저축,청약저축,청약저축,납입금액,None,작성방법 참조
26,Ⅳ 그 밖 의 소 득 공 제,주택마련저축,근로자주택마련저축,근로자주택마련저축,근로자주택마련저축,근로자주택마련저축,근로자주택마련저축,납입금액,None,작성방법 참조
27,Ⅳ 그 밖 의 소 득 공 제,주택마련저축,주택청약종합저축,주택청약종합저축,주택청약종합저축,주택청약종합저축,주택청약종합저축,납입금액,None,작성방법 참조
28,Ⅳ 그 밖 의 소 득 공 제,주택마련저축,주택마련저축 소득공제 계,주택마련저축 소득공제 계,주택마련저축 소득공제 계,주택마련저축 소득공제 계,주택마련저축 소득공제 계,None,None,None
29,Ⅳ 그 밖 의 소 득 공 제,투자조합\n출자 등,2022년 출자·투자분,2022년 출자·투자분,2022년 출자·투자분,벤처 등,벤처 등,출자·투자금액,None,작성방법 참조
30,Ⅳ 그 밖 의 소 득 공 제,투자조합\n출자 등,2022년 출자·투자분,2022년 출자·투자분,2022년 출자·투자분,조합1,조합1,출자·투자금액,None,작성방법 참조
31,Ⅳ 그 밖 의 소 득 공 제,투자조합\n출자 등,2022년 출자·투자분,2022년 출자·투자분,2022년 출자·투자분,조합2,조합2,출자·투자금액,None,작성방법 참조
32,Ⅳ 그 밖 의 소 득 공 제,투자조합\n출자 등,2023년 출자·투자분,2023년 출자·투자분,2023년 출자·투자분,벤처 등,벤처 등,출자·투자금액,None,작성방법 참조
33,Ⅳ 그 밖 의 소 득 공 제,투자조합\n출자 등,2023년 출자·투자분,2023년 출자·투자분,2023년 출자·투자분,조합1,조합1,출자·투자금액,None,작성방법 참조
34,Ⅳ 그 밖 의 소 득 공 제,투자조합\n출자 등,2023년 출자·투자분,2023년 출자·투자분,2023년 출자·투자분,조합2,조합2,출자·투자금액,None,작성방법 참조
35,Ⅳ 그 밖 의 소 득 공 제,투자조합\n출자 등,2024년 출자·투자분,2024년 출자·투자분,2024년 출자·투자분,벤처 등,벤처 등,출자·투자금액,None,작성방법 참조
36,Ⅳ 그 밖 의 소 득 공 제,투자조합\n출자 등,2024년 출자·투자분,2024년 출자·투자분,2024년 출자·투자분,조합1,조합1,출자·투자금액,None,작성방법 참조
37,Ⅳ 그 밖 의 소 득 공 제,투자조합\n출자 등,2024년 출자·투자분,2024년 출자·투자분,2024년 출자·투자분,조합2,조합2,출자·투자금액,None,작성방법 참조
38,Ⅳ 그 밖 의 소 득 공 제,투자조합\n출자 등,투자조합 출자 등 소득공제 계,투자조합 출자 등 소득공제 계,투자조합 출자 등 소득공제 계,투자조합 출자 등 소득공제 계,투자조합 출자 등 소득공제 계,None,None,None
39,Ⅳ 그 밖 의 소 득 공 제,신용카드등\n사용액,① 신용카드,① 신용카드,① 신용카드,① 신용카드,① 신용카드,사용금액,"10,000,000",None
40,Ⅳ 그 밖 의 소 득 공 제,신용카드등\n사용액,② 직불·선불카드,② 직불·선불카드,② 직불·선불카드,② 직불·선불카드,② 직불·선불카드,사용금액,"5,000,000",None
41,Ⅳ 그 밖 의 소 득 공 제,신용카드등\n사용액,③ 현금영수증,③ 현금영수증,③ 현금영수증,③ 현금영수증,③ 현금영수증,사용금액,"7,000,000",None
42,Ⅳ 그 밖 의 소 득 공 제,신용카드등\n사용액,④ 도서·공연사용분등(총급여 7천만원 이하자),④ 도서·공연사용분등(총급여 7천만원 이하자),④ 도서·공연사용분등(총급여 7천만원 이하자),④ 도서·공연사용분등(총급여 7천만원 이하자),④ 도서·공연사용분등(총급여 7천만원 이하자),사용금액,"1,000,000",None
43,Ⅳ 그 밖 의 소 득 공 제,신용카드등\n사용액,⑤ 전통시장사용분,⑤ 전통시장사용분,⑤ 전통시장사용분,⑤ 전통시장사용분,⑤ 전통시장사용분,사용금액,"3,000,000",None
44,Ⅳ 그 밖 의 소 득 공 제,신용카드등\n사용액,⑥ 대중교통이용분,⑥ 대중교통이용분,⑥ 대중교통이용분,⑥ 대중교통이용분,⑥ 대중교통이용분,사용금액,"2,000,000",None
45,Ⅳ 그 밖 의 소 득 공 제,신용카드등\n사용액,⑦ 소비증가분(2024년 신용카드사용금액 중\n2023년 대비 5% 초과하여 증가한...,⑦ 소비증가분(2024년 신용카드사용금액 중\n2023년 대비 5% 초과하여 증가한...,⑦ 소비증가분(2024년 신용카드사용금액 중\n2023년 대비 5% 초과하여 증가한...,⑦ 소비증가분(2024년 신용카드사용금액 중\n2023년 대비 5% 초과하여 증가한...,⑦ 소비증가분(2024년 신용카드사용금액 중\n2023년 대비 5% 초과하여 증가한...,증가금액,"1,750,000",None
46,Ⅳ 그 밖 의 소 득 공 제,신용카드등\n사용액,계(①+②+③+④+⑤+⑥+⑦),계(①+②+③+④+⑤+⑥+⑦),계(①+②+③+④+⑤+⑥+⑦),계(①+②+③+④+⑤+⑥+⑦),계(①+②+③+④+⑤+⑥+⑦),None,"29,750,000",None
47,Ⅳ 그 밖 의 소 득 공 제,우리사주조합 출연금,우리사주조합 출연금,우리사주조합 출연금,우리사주조합 출연금,우리사주조합 출연금,우리사주조합 출연금,출연금액,None,작성방법 참조
48,Ⅳ 그 밖 의 소 득 공 제,고용유지중소기업 근로자,고용유지중소기업 근로자,고용유지중소기업 근로자,고용유지중소기업 근로자,고용유지중소기업 근로자,고용유지중소기업 근로자,임금삭감액,None,작성방법 참조
49,Ⅳ 그 밖 의 소 득 공 제,장기집합투자증권저축,장기집합투자증권저축,장기집합투자증권저축,장기집합투자증권저축,장기집합투자증권저축,장기집합투자증권저축,납입금액,None,작성방법 참조
50,Ⅳ 그 밖 의 소 득 공 제,청년형 장기집합투자증권 저축,청년형 장기집합투자증권 저축,청년형 장기집합투자증권 저축,청년형 장기집합투자증권 저축,청년형 장기집합투자증권 저축,청년형 장기집합투자증권 저축,납입금액,None,None

Page 236 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,None,세액감면·공제명세,세액감면·공제명세,세액감면·공제명세,세액감면·공제명세,세액감면·공제명세,세액감면·공제명세,세액감면·공제명세,세액감면·공제명세,세액감면·공제 명세,세액감면·공제 명세,세액감면·공제 명세,세액감면·공제 명세,세액감면·공제 명세,세액감면·공제 명세,세액감면·공제 명세,세액감면·공제 명세
1,세 액 감 면,외국인\n근로자,외국인\n근로자,입국목적,입국목적,입국목적,입국목적,입국목적,입국목적,None,None,[ ] 정부간,None,None,None,None,상 감면
2,세 액 감 면,외국인\n근로자,외국인\n근로자,기술도입계약 또는 근로제공일,기술도입계약 또는 근로제공일,기술도입계약 또는 근로제공일,기술도입계약 또는 근로제공일,기술도입계약 또는 근로제공일,기술도입계약 또는 근로제공일,None,None,None,감면기간 만료일,감면기간 만료일,None,None,None
3,세 액 감 면,외국인\n근로자,외국인\n근로자,외국인 근로소득에 대한 감면,외국인 근로소득에 대한 감면,외국인 근로소득에 대한 감면,외국인 근로소득에 대한 감면,외국인 근로소득에 대한 감면,외국인 근로소득에 대한 감면,접수일,접수일,접수일,None,None,제출일,제출일,None
4,세 액 감 면,외국인\n근로자,외국인\n근로자,근로소득에 대한 조세조약 상 면제,근로소득에 대한 조세조약 상 면제,근로소득에 대한 조세조약 상 면제,근로소득에 대한 조세조약 상 면제,근로소득에 대한 조세조약 상 면제,근로소득에 대한 조세조약 상 면제,접수일,접수일,접수일,None,None,제출일,제출일,None
5,세 액 감 면,성과공유 중소기업 경영성과급 감면,성과공유 중소기업 경영성과급 감면,성과공유 중소기업 경영성과급 감면,성과공유 중소기업 경영성과급 감면,성과공유 중소기업 경영성과급 감면,성과공유 중소기업 경영성과급 감면,성과공유 중소기업 경영성과급 감면,성과공유 중소기업 경영성과급 감면,시작일,시작일,시작일,None,None,종료일,종료일,None
6,세 액 감 면,중소기업 청년근로자 및 핵심인력\n성과보상기금 수령액 감면,중소기업 청년근로자 및 핵심인력\n성과보상기금 수령액 감면,중소기업 청년근로자 및 핵심인력\n성과보상기금 수령액 감면,중소기업 청년근로자 및 핵심인력\n성과보상기금 수령액 감면,중소기업 청년근로자 및 핵심인력\n성과보상기금 수령액 감면,중소기업 청년근로자 및 핵심인력\n성과보상기금 수령액 감면,중소기업 청년근로자 및 핵심인력\n성과보상기금 수령액 감면,중소기업 청년근로자 및 핵심인력\n성과보상기금 수령액 감면,시작일,시작일,시작일,None,None,종료일,종료일,None
7,세 액 감 면,내국인 우수 인력 국내 복귀 감면,내국인 우수 인력 국내 복귀 감면,내국인 우수 인력 국내 복귀 감면,내국인 우수 인력 국내 복귀 감면,내국인 우수 인력 국내 복귀 감면,내국인 우수 인력 국내 복귀 감면,내국인 우수 인력 국내 복귀 감면,내국인 우수 인력 국내 복귀 감면,시작일,시작일,시작일,None,None,종료일,종료일,None
8,세 액 감 면,중소기업 취업자 감면,중소기업 취업자 감면,중소기업 취업자 감면,중소기업 취업자 감면,중소기업 취업자 감면,중소기업 취업자 감면,중소기업 취업자 감면,중소기업 취업자 감면,취업일,취업일,취업일,None,None,감면기간 종료일,감면기간 종료일,None
9,세 액 공 제,공제종류,공제종류,공제종류,공제종류,공제종류,공제종류,공제종류,공제종류,명세,명세,명세,명세,한도액,한도액,공제대상금액,공제율 공제세액
10,세 액 공 제,연 금 계 좌,「과학기술인공제회법」에 따른 퇴직연금,「과학기술인공제회법」에 따른 퇴직연금,「과학기술인공제회법」에 따른 퇴직연금,「과학기술인공제회법」에 따른 퇴직연금,「과학기술인공제회법」에 따른 퇴직연금,「과학기술인공제회법」에 따른 퇴직연금,「과학기술인공제회법」에 따른 퇴직연금,납입금액,납입금액,납입금액,None,작성방법\n참조,작성방법\n참조,None,None
11,세 액 공 제,연 금 계 좌,｢근로자퇴직급여 보장법｣에 따른 퇴직연금,｢근로자퇴직급여 보장법｣에 따른 퇴직연금,｢근로자퇴직급여 보장법｣에 따른 퇴직연금,｢근로자퇴직급여 보장법｣에 따른 퇴직연금,｢근로자퇴직급여 보장법｣에 따른 퇴직연금,｢근로자퇴직급여 보장법｣에 따른 퇴직연금,｢근로자퇴직급여 보장법｣에 따른 퇴직연금,납입금액,납입금액,납입금액,"1,000,000",작성방법\n참조,작성방법\n참조,"1,000,000",12%
12,세 액 공 제,연 금 계 좌,연금저축,연금저축,연금저축,연금저축,연금저축,연금저축,연금저축,납입금액,납입금액,납입금액,"2,000,000",작성방법\n참조,작성방법\n참조,"2,000,000",또는
13,세 액 공 제,연 금 계 좌,ISA 만기시 연금계좌 납입액,ISA 만기시 연금계좌 납입액,ISA 만기시 연금계좌 납입액,ISA 만기시 연금계좌 납입액,ISA 만기시 연금계좌 납입액,ISA 만기시 연금계좌 납입액,ISA 만기시 연금계좌 납입액,납입금액,납입금액,납입금액,None,작성방법\n참조,작성방법\n참조,None,15%
14,세 액 공 제,연 금 계 좌,연금계좌 계,연금계좌 계,연금계좌 계,연금계좌 계,연금계좌 계,연금계좌 계,연금계좌 계,None,None,None,"3,000,000",None,None,"3,000,000",None
15,세 액 공 제,특 별 세 액 공 제,보험료,보험료,보장성,보장성,보장성,보장성,보장성,보험료,보험료,보험료,"3,000,000",100만원,100만원,"1,000,000",12%
16,세 액 공 제,특 별 세 액 공 제,보험료,보험료,장애인전용보장성,장애인전용보장성,장애인전용보장성,장애인전용보장성,장애인전용보장성,보험료,보험료,보험료,None,100만원,100만원,None,15%
17,세 액 공 제,특 별 세 액 공 제,보험료,보험료,보험료 계,보험료 계,보험료 계,보험료 계,보험료 계,None,None,None,"3,000,000",None,None,"1,000,000",None
18,세 액 공 제,특 별 세 액 공 제,의료비,의료비,본인·6세 이하 또는 65세 이상자\n장애인·건강보험산정특례자,본인·6세 이하 또는 65세 이상자\n장애인·건강보험산정특례자,본인·6세 이하 또는 65세 이상자\n장애인·건강보험산정특례자,본인·6세 이하 또는 65세 이상자\n장애인·건강보험산정특례자,본인·6세 이하 또는 65세 이상자\n장애인·건강보험산정특례자,지출액,지출액,지출액,"1,850,000",작성방법\n참조,작성방법\n참조,"1,800,000",15%
19,세 액 공 제,특 별 세 액 공 제,의료비,의료비,난임시술비\n미숙아·선천성 이상아,난임시술비\n미숙아·선천성 이상아,난임시술비\n미숙아·선천성 이상아,난임시술비\n미숙아·선천성 이상아,난임시술비\n미숙아·선천성 이상아,지출액\n지출액,지출액\n지출액,지출액\n지출액,"1,000,000",작성방법\n참조,작성방법\n참조,"1,000,000",30%
20,세 액 공 제,특 별 세 액 공 제,의료비,의료비,난임시술비\n미숙아·선천성 이상아,난임시술비\n미숙아·선천성 이상아,난임시술비\n미숙아·선천성 이상아,난임시술비\n미숙아·선천성 이상아,난임시술비\n미숙아·선천성 이상아,지출액\n지출액,지출액\n지출액,지출액\n지출액,None,작성방법\n참조,작성방법\n참조,None,20%
21,세 액 공 제,특 별 세 액 공 제,의료비,의료비,그 밖의 공제대상자,그 밖의 공제대상자,그 밖의 공제대상자,그 밖의 공제대상자,그 밖의 공제대상자,지출액,지출액,지출액,"4,700,000",작성방법\n참조,작성방법\n참조,"2,538,000",15%
22,세 액 공 제,특 별 세 액 공 제,의료비,의료비,실손의료보험금 계,실손의료보험금 계,실손의료보험금 계,실손의료보험금 계,실손의료보험금 계,수령액,수령액,수령액,None,None,None,None,None
23,세 액 공 제,특 별 세 액 공 제,의료비,의료비,의료비 계,의료비 계,의료비 계,의료비 계,의료비 계,None,None,None,"7,550,000",None,None,"5,338,000",None
24,세 액 공 제,특 별 세 액 공 제,교육비,교육비,소득자 본인,소득자 본인,소득자 본인,소득자 본인,소득자 본인,공납금(대학원 포함),공납금(대학원 포함),공납금(대학원 포함),None,전액,전액,None,None
25,세 액 공 제,특 별 세 액 공 제,교육비,교육비,취학전 아동 ( 1 명),취학전 아동 ( 1 명),취학전 아동 ( 1 명),취학전 아동 ( 1 명),취학전 아동 ( 1 명),유치원·학원비 등,유치원·학원비 등,유치원·학원비 등,"1,200,000",1명당 300만원,1명당 300만원,"1,200,000",None
26,세 액 공 제,특 별 세 액 공 제,교육비,교육비,초·중·고등학교(1 명),초·중·고등학교(1 명),초·중·고등학교(1 명),초·중·고등학교(1 명),초·중·고등학교(1 명),공납금,공납금,공납금,"3,350,000",1명당 300만원,1명당 300만원,"3,000,000",15%
27,세 액 공 제,특 별 세 액 공 제,교육비,교육비,대학생(대학원 불포함) ( 명),대학생(대학원 불포함) ( 명),대학생(대학원 불포함) ( 명),대학생(대학원 불포함) ( 명),대학생(대학원 불포함) ( 명),공납금,공납금,공납금,None,1명당 900만원,1명당 900만원,None,None
28,세 액 공 제,특 별 세 액 공 제,교육비,교육비,장애인 ( 명),장애인 ( 명),장애인 ( 명),장애인 ( 명),장애인 ( 명),특수교육비,특수교육비,특수교육비,None,전액,전액,None,None
29,세 액 공 제,특 별 세 액 공 제,교육비,교육비,교육비 계,교육비 계,교육비 계,교육비 계,교육비 계,None,None,None,"4,550,000",None,None,"4,200,000",None
30,세 액 공 제,특 별 세 액 공 제,기부금,기부금,정치자금\n기부금,정치자금\n기부금,정치자금\n기부금,10만원 이하,10만원 이하,기부금액,기부금액,기부금액,"100,000",작성방법\n참조,작성방법\n참조,"100,000",100/110
31,세 액 공 제,특 별 세 액 공 제,기부금,기부금,정치자금\n기부금,정치자금\n기부금,정치자금\n기부금,10만원 초과,10만원 초과,기부금액,기부금액,기부금액,"100,000",작성방법\n참조,작성방법\n참조,"100,000 15%,",25%
32,세 액 공 제,특 별 세 액 공 제,기부금,기부금,고향사랑\n기부금,고향사랑\n기부금,고향사랑\n기부금,10만원 이하,10만원 이하,None,기부금액,기부금액,"100,000",작성방법\n참조,작성방법\n참조,"100,000",100/110\n15%
33,세 액 공 제,특 별 세 액 공 제,기부금,기부금,고향사랑\n기부금,고향사랑\n기부금,고향사랑\n기부금,10만원 초과,10만원 초과,None,기부금액,기부금액,None,작성방법\n참조,작성방법\n참조,None,100/110\n15%
34,세 액 공 제,특 별 세 액 공 제,기부금,기부금,특례기부금,None,None,None,None,None,기부금액,기부금액,"500,000",작성방법\n참조,작성방법\n참조,"500,000",100/110\n15%
35,세 액 공 제,특 별 세 액 공 제,기부금,기부금,None,None,None,None,None,None,기부금액,기부금액,None,작성방법\n참조,작성방법\n참조,None,15%·30%
36,세 액 공 제,특 별 세 액 공 제,기부금,기부금,None,None,None,None,None,None,기부금액,기부금액,None,작성방법\n참조,작성방법\n참조,(2024년의,경우
37,세 액 공 제,특 별 세 액 공 제,기부금,기부금,None,None,None,None,None,None,기부금액,기부금액,None,작성방법\n참조,작성방법\n참조,None,15%·30%·40%
38,세 액 공 제,특 별 세 액 공 제,기부금,기부금,기부금 계,기부금 계,기부금 계,기부금 계,기부금 계,None,None,None,"800,000",None,None,"800,000",None
39,세 액 공 제,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,국외원천소득,국외원천소득,국외원천소득,None,None,None,None,None
40,세 액 공 제,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,납세액(외화),납세액(외화),납세액(외화),None,None,None,None,None
41,세 액 공 제,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,납세액(원화),납세액(원화),None,None,-,-,-,None
42,세 액 공 제,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,납세국명,납세국명,납세국명,None,납부일,납부일,납부일,None
43,세 액 공 제,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,신청서제출일\n근무기간,신청서제출일\n근무기간,신청서제출일\n근무기간,None,국외근무처,국외근무처,국외근무처,None
44,세 액 공 제,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,외국납부세액,신청서제출일\n근무기간,신청서제출일\n근무기간,신청서제출일\n근무기간,None,직책,직책,직책,None
45,세 액 공 제,주택자금차입금이자세액공제,주택자금차입금이자세액공제,주택자금차입금이자세액공제,주택자금차입금이자세액공제,주택자금차입금이자세액공제,주택자금차입금이자세액공제,주택자금차입금이자세액공제,주택자금차입금이자세액공제,이자상환액,이자상환액,이자상환액,None,30%,30%,30%,None
46,세 액 공 제,월세액 세액공제,월세액 세액공제,월세액 세액공제,월세액 세액공제,월세액 세액공제,월세액 세액공제,월세액 세액공제,월세액 세액공제,지출액,지출액,지출액,None,15% 또는 17%,15% 또는 17%,15% 또는 17%,None

Page 237 - Table 0 DataFrame:

,0,1,2,3
0,1. 인적사항,① 상 호,한강건설(주),② 사업자등록번호
1,1. 인적사항,③ 성 명,이강모,④ 주민등록번호
2,1. 인적사항,⑤ 주 소,None,None
3,1. 인적사항,⑥ 사업장 소재지,서울특별시 종로구 종로5길 1000(전화번호: 02-0000-0000 ),서울특별시 종로구 종로5길 1000(전화번호: 02-0000-0000 )

Page 237 - Table 1 DataFrame:

      0       1               2          3        4
0  None  금융회사 등  계좌번호 (또는 증권번호)       납입금액     None
1  퇴직연금    00보험    987-**-*****  1,000,000  120,000

Page 237 - Table 2 DataFrame:

      0       1              2          3        4
0  None  금융회사 등  계좌번호(또는 증권번호)       납입금액     None
1  연금저축    ㅁㅁ은행    *****-67890  2,000,000  240,000

Page 238 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8
0,⑦ 임대인성명\n(상 호),⑧ 주민등록번호\n(사업자번호),⑨ 유형,⑩ 계약면적\n(㎡),⑪\n임대차계약서 상 주소지,⑫ 계약서 상 임대차 계약기간,⑫ 계약서 상 임대차 계약기간,⑬ 연간월세액(원),⑭\n세액공제금액(원)
1,⑦ 임대인성명\n(상 호),⑧ 주민등록번호\n(사업자번호),⑨ 유형,⑩ 계약면적\n(㎡),⑪\n임대차계약서 상 주소지,개시일,종료일,⑬ 연간월세액(원),⑭\n세액공제금액(원)

Page 238 - Table 1 DataFrame:

          0         1               2          3        4        5        6
0  ⑮ 대주(貸主)  ⑯ 주민등록번호  ⑰\n금전소비대차 계약기간  ⑱ 차입금 이자율  원리금 상환액  원리금 상환액  원리금 상환액
1  ⑮ 대주(貸主)  ⑯ 주민등록번호  ⑰\n금전소비대차 계약기간  ⑱ 차입금 이자율      ⑲ 계     ⑳ 원금    ￾￾ 이자

Page 238 - Table 2 DataFrame:

,0,1,2,3,4,5,6,7
0,￾￾ 임대인성명\n(상\n호),￾￾ 주민등록번호\n(사업자번호),￾￾ 유형,￾￾ 계약면적\n(㎡),￾￾\n임대차계약서상 주소지,￾￾ 계약서상 임대차 계약기간,￾￾ 계약서상 임대차 계약기간,￾￾\n전세보증금(원)
1,￾￾ 임대인성명\n(상\n호),￾￾ 주민등록번호\n(사업자번호),￾￾ 유형,￾￾ 계약면적\n(㎡),￾￾\n임대차계약서상 주소지,개시일,종료일,￾￾\n전세보증금(원)

Page 239 - Table 0 DataFrame:

         0         1        2          3                4                 5
0  ⑦ 자녀 성명  ⑧ 주민등록번호    출산지원금      출산지원금            출산지원금  ⑫ 지급처\n(사업자등록번호)
1  ⑦ 자녀 성명  ⑧ 주민등록번호  ⑨지급받은 날  ⑩ 지급받은 금액  ⑪지급회차\n[1 또는 2]  ⑫ 지급처\n(사업자등록번호)

Page 241 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,의료비 공제 대상자,의료비 공제 대상자,의료비 공제 대상자,의료비 공제 대상자,의료비 공제 대상자,의료비 공제 대상자,의료비 공제 대상자,의료비 공제 대상자,의료비 공제 대상자,의료비 공제 대상자,...,지급처,지급처,지급처,지급처,지급처,지급처,지급명세,지급명세,지급명세,지급명세
1,None,None,None,None,None,None,None,None,None,None,...,⑦ 사업자등록번호,⑦ 사업자등록번호,⑦ 사업자등록번호,⑦ 사업자등록번호,⑧ 상호,⑨ 의료 증빙 코드,⑩ 건수,⑪ 금액,⑫ 미숙아·\n선천성\n이상아\n해당여부,⑬ 난임 시술비\n해당여부
2,8,0,0,1,0,1,-,1,2,3,...,None,None,None,None,None,1,None,"1,300,000",×,×
3,8,0,0,1,0,1,-,1,2,3,...,*,*,*,*,A안경,5,1,"550,000",×,×
4,8,1,0,7,0,1,-,2,2,3,...,None,None,None,None,None,1,None,"2,500,000",×,×
5,8,1,0,7,0,1,-,2,2,3,...,None,None,None,None,None,1,None,"1,000,000",×,○
6,8,1,0,7,0,1,-,2,2,3,...,None,None,None,None,None,1,None,"2,200,000",×,×
7,None,None,None,None,None,None,-,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,None,None,None,None,None,None,-,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,None,None,None,None,None,None,-,None,None,None,...,None,None,None,None,None,None,None,None,None,None
10,None,None,None,None,None,None,-,None,None,None,...,None,None,None,None,None,None,None,None,None,None
11,None,None,None,None,None,None,None,None,None,None,...,합 계,합 계,합 계,합 계,합 계,합 계,1,"7,550,000",None,None

Page 244 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10
0,None,⑧ 기부내용,기부처,기부처,⑪ 기부자,⑪ 기부자,⑪ 기부자,기부 명세\n기부금액,기부 명세\n기부금액,기부 명세\n기부금액,기부 명세\n기부금액
1,⑦ 코드,⑧ 기부내용,⑨ 상호 (법인명),⑩ 사업자\n등록번호 등,관계 코드,성명,주민등록번호,건수,⑫ 합계 (⑬+⑭),⑬ 공제대상\n기부금액,공제제외
2,⑦ 코드,⑧ 기부내용,⑨ 상호 (법인명),⑩ 사업자\n등록번호 등,관계 코드,성명,주민등록번호,건수,⑫ 합계 (⑬+⑭),⑬ 공제대상\n기부금액,⑭ 기부장려금\n신청금액
3,20,금전,None,None,1,이강모,800101- 1******,1,"200,000","200,000",None
4,43,금전,부산광역시,601-83-*****,1,이강모,800101- 1******,1,"100,000","100,000",None
5,10,금전,00대학교,101-82-*****,1,이강모,801010- 1******,1,"500,000","500,000",None

Page 244 - Table 1 DataFrame:

,0,1,2,3,4,5,6,7,8
0,기부자\n구분,총계,공제대상 기부금,공제대상 기부금,공제대상 기부금,공제대상 기부금,공제대상 기부금,공제대상 기부금,None
1,기부자\n구분,총계,특례기부금,정치자금\n기부금,고향사랑\n기부금,일반기부금\n(종교단체 외),일반기부금\n(종교단체),우리사주조합\n기부금,기부장려금\n신청금액
2,코드,None,10,20,43,40,41,42,"10,40,41"
3,합계,"800,000","500,000","200,000","100,000",None,None,None,None
4,본인,"800,000","500,000","200,000","100,000",None,None,None,None
5,배우자,None,None,None,None,None,None,None,None
6,직계비속,None,None,None,None,None,None,None,None
7,직계존속,None,None,None,None,None,None,None,None
8,형제자매,None,None,None,None,None,None,None,None

Page 244 - Table 2 DataFrame:

,0,1,2,3,4,5,6,7,8
0,기부금\n코드,기부 연도,￾￾ 기부금액,⑰ 전년까지\n공제된 금액,⑱ 공제대상\n금액(￾￾-⑰),해당 연도 공제금액,해당 연도 공제금액,해당 연도에 공제받지 못한 금액,해당 연도에 공제받지 못한 금액
1,기부금\n코드,기부 연도,￾￾ 기부금액,⑰ 전년까지\n공제된 금액,⑱ 공제대상\n금액(￾￾-⑰),필요경비,세액(소득)공제,소멸금액,이월금액
2,10,2023,"500,000",-,"500,000",-,"500,000",None,None
3,20,2023,"200,000",-,"200,000",-,"200,000",None,None
4,43,2023,"100,000",None,"100,000",None,"100,000",None,None

Page 245 - Table 0 DataFrame:

         0        1
0      이강모     생년월일
1  한강건설(주)  사업자등록번호

Page 245 - Table 1 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,① 내·외\n국인 구분,② 관계,③ 성명,④ 생년 월일,자료구분,⑤ 소계\n(⑥+⑦+⑧+\n⑨+⑩+⑪),⑥ 신용카드,⑦ 직불·\n선불카드\n등,⑧ 현금 영수증,⑨ 도서공연\n등 사용분(총\n급여 7천만원\n이하자만 기재),⑩ 전통시장\n사용분,⑪ 대중교통\n이용분,⑪-1\n소비증가분,⑪-1\n소비증가분
1,① 내·외\n국인 구분,② 관계,③ 성명,④ 생년 월일,자료구분,⑤ 소계\n(⑥+⑦+⑧+\n⑨+⑩+⑪),⑥ 신용카드,⑦ 직불·\n선불카드\n등,⑧ 현금 영수증,⑨ 도서공연\n등 사용분(총\n급여 7천만원\n이하자만 기재),⑩ 전통시장\n사용분,⑪ 대중교통\n이용분,2023년\n전체 사용분,2024년\n전체 사용분
2,내국인,본인,이강모,8001\n01,국세청 자료,"28,000,000","10,000,000","5,000,000","7,000,000","1,000,000","3,000,000","2,000,000","25,000,000","28,000,000"
3,내국인,본인,이강모,8001\n01,그 밖의 자료,None,None,None,None,None,None,None,None,None
4,None,None,None,-,국세청 자료,None,None,None,None,None,None,None,None,None
5,None,None,None,-,그 밖의 자료,None,None,None,None,None,None,None,None,None
6,⑤-1 합 계 액,⑤-1 합 계 액,⑤-1 합 계 액,⑤-1 합 계 액,⑤-1 합 계 액,"28,000,000","10,000,000","5,000,000","7,000,000","1,000,000","3,000,000","2,000,000","25,000,000",None

Page 245 - Table 2 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,⑫ 신용카드\n사용분\n공제금액\n(⑥×15%),⑬ 직불카드등\n사용분\n공제금액\n(⑦+⑧)×\n30%,⑭ 도서·공연등\n사용분 공제금액,⑭ 도서·공연등\n사용분 공제금액,⑮ 전통시장\n사용분 공제금액),⑮ 전통시장\n사용분 공제금액),￾￾ 대중교통\n이용분 공제금액,￾￾ 대중교통\n이용분 공제금액,￾￾ 공제제외금액 계산\n신용카드,￾￾ 공제제외금액 계산\n신용카드,￾￾ 공제제외금액 계산\n신용카드,￾￾ 공제제외금액 계산\n신용카드,￾￾ 공제제외금액 계산\n신용카드,⑱ 2024년\n등 사용금액 중\n신용카드 둥 사용\n5%를 초과하여\n금액의 10%
1,⑫ 신용카드\n사용분\n공제금액\n(⑥×15%),⑬ 직불카드등\n사용분\n공제금액\n(⑦+⑧)×\n30%,⑭ 도서·공연등\n사용분 공제금액,⑭ 도서·공연등\n사용분 공제금액,⑮ 전통시장\n사용분 공제금액),⑮ 전통시장\n사용분 공제금액),￾￾ 대중교통\n이용분 공제금액,￾￾ 대중교통\n이용분 공제금액,￾￾-1\n총급여,￾￾-1\n총급여,￾￾-2\n최저사용금액\n[(￾￾-1)×25%],￾￾-2\n최저사용금액\n[(￾￾-1)×25%],2023년\n￾￾-3 공제제외\n금액 대비\n증가한\n금액,⑱ 2024년\n등 사용금액 중\n신용카드 둥 사용\n5%를 초과하여\n금액의 10%
2,"1,500,000","3,600,000","300,000","300,000","1,200,000","1,200,000","800,000","800,000","65,400,000","65,400,000","16,350,000","16,350,000","3,405,000","175,000"
3,￾￾ 공제가능금액\n[⑫+⑬+⑭+\n⑮+￾￾-(￾￾-\n3)]+⑱,"￾￾\n공제한도액[총급여\n수준별 250만원,\n300만원]","￾￾\n공제한도액[총급여\n수준별 250만원,\n300만원]",￾￾ 일반 공제금액\n(￾￾과 ￾￾중\n적은 금액),￾￾ 일반 공제금액\n(￾￾과 ￾￾중\n적은 금액),"㉒ 대중교통, 전통시장, 도서·공연 등 추가공제액 계산","㉒ 대중교통, 전통시장, 도서·공연 등 추가공제액 계산","㉒ 대중교통, 전통시장, 도서·공연 등 추가공제액 계산","㉒ 대중교통, 전통시장, 도서·공연 등 추가공제액 계산","㉒ 대중교통, 전통시장, 도서·공연 등 추가공제액 계산","㉒ 대중교통, 전통시장, 도서·공연 등 추가공제액 계산",㉓ 2024년 신용카드 등 사용금액 중\n2023년 신용카드 등 사용금액 대비\n소...,㉓ 2024년 신용카드 등 사용금액 중\n2023년 신용카드 등 사용금액 대비\n소...,￾￾ 최종 공제금액\n{㉑+(㉒-3)+\n㉓}
4,￾￾ 공제가능금액\n[⑫+⑬+⑭+\n⑮+￾￾-(￾￾-\n3)]+⑱,"￾￾\n공제한도액[총급여\n수준별 250만원,\n300만원]","￾￾\n공제한도액[총급여\n수준별 250만원,\n300만원]",￾￾ 일반 공제금액\n(￾￾과 ￾￾중\n적은 금액),￾￾ 일반 공제금액\n(￾￾과 ￾￾중\n적은 금액),㉒-1 추가공제 가능금액\n[⑲>⑳인 경우\n(⑭+⑮+◯16)과\n(⑲-⑳)중\n적...,㉒-1 추가공제 가능금액\n[⑲>⑳인 경우\n(⑭+⑮+◯16)과\n(⑲-⑳)중\n적...,"㉒-2 추가공제 한도액\n[총급여 수준별\n300만원,\n200만원]","㉒-2 추가공제 한도액\n[총급여 수준별\n300만원,\n200만원]",㉒-3 추가공제금액\n{(㉒-1)과 (㉒-2)중\n적은 금액},㉒-3 추가공제금액\n{(㉒-1)과 (㉒-2)중\n적은 금액},㉓ 2024년 신용카드 등 사용금액 중\n2023년 신용카드 등 사용금액 대비\n소...,㉓ 2024년 신용카드 등 사용금액 중\n2023년 신용카드 등 사용금액 대비\n소...,￾￾ 최종 공제금액\n{㉑+(㉒-3)+\n㉓}
5,None,"3,000,000","3,000,000","3,000,000","3,000,000","1,170,000","1,170,000","3,000,000","3,000,000","1,170,000","1,170,000",-,-,None

Page 245 - Table 3 DataFrame:

,0,1,2
0,None,계산식,None
1,⑥ ≥ (￾￾-2),(￾￾-2)×15%,None
2,⑥ + ⑦ + ⑧ + ⑨ ≥ (￾￾-2) 〉⑥,⑥×15% + {(￾￾-2)-⑥}×30%,"3,405,000"
3,⑥ + ⑦ + ⑧ + ⑨ ≥ (￾￾-2) 〉\n⑥ +⑦ + ⑧ + ⑨ + ⑩ + ⑪,⑥×15% + (⑦+⑧+⑨×30%) + {(￾￾-2)-⑥-⑦-⑧-⑨}×40%,None

Page 247 - Table 0 DataFrame:

,0,1,2,3,4
0,법조문,비과세 항목,기재란\n번호,코드,비과세 한도
1,소법§12 3 아,비과세 학자금(소령§ 11),￾￾-5,G01,해당연도 납입할 금액 한도
2,소법§12 3 자,"소령§12 9~11(경호수당, 승선수당 등)",￾￾-18,H05,전액(승선수당은 20만원 한도)
3,소법§12 3 자,"소령§12 12 가(연구보조비) - 유아교육법,\n초중등교육법",￾￾-4,H06,월 20만원 이내 금액
4,소법§12 3 자,소령§12 12 가(연구보조비) - 고등교육법,￾￾-4,H07,월 20만원 이내 금액
5,소법§12 3 자,소령§12 12 가(연구보조비) - 특별법에 의한\n교육기관,￾￾-4,H08,월 20만원 이내 금액
6,소법§12 3 자,소령§12 12 나(연구보조비),￾￾-4,H09,월 20만원 이내 금액
7,소법§12 3 자,소령§12 12 다(연구보조비),￾￾-4,H10,월 20만원 이내 금액
8,소법§12 3 자,소령§12 13 가 (보육교사 근무환경개선비),￾￾-22,H14,전액
9,소법§12 3 자,소령§12 13 나 (사립유치원 교사의 인건비),￾￾-23,H15,전액
10,소법§12 3 자,소령§12 14 (취재수당),￾￾-6,H11,월 20만원 이내 금액
11,소법§12 3 자,소령§12 15 (벽지수당),￾￾-7,H12,월 20만원 이내 금액
12,소법§12 3 자,소령§12 16 (천재·지변 등 재해로 받는 급여),￾￾-8,H13,None

Page 248 - Table 0 DataFrame:

,0,1,2,3,4
0,법조문,비과세 항목,기재란\n번호,코드,비과세 한도
1,소법§12 3 자,소령§12 17 (정부·공공기관 중 지방이전\n기관 종사자 이주수당),￾￾-24,H16,월 20만원 이내 금액
2,소법§12 3 자,소령§12 18\n(소득령§12 18(종교관련종사자가소속 종교단체의\n규약 또는 소...,￾￾-30,H17,전액
3,소법§12 3 차,외국정부 또는 국제기관에 근무하는 자에 대한\n비과세,￾￾-19,I01,전액
4,소법§12 3 파,작전임무 수행을 위해 외국에 주둔하는 군인 등이\n받는 급여,￾￾-10,K01,전액
5,소법§12 3 거,소령§16①1(국외근로) 100만원,￾￾,M01,월 100만원 이내 금액
6,소법§12 3 거,소령§16①1(국외근로) 300만원,￾￾,M02,월 300만원 이내 금액_2023년\n귀속까지만 적용
7,소법§12 3 거,소령§16①2(국외근로),￾￾,M03,국외 등에서 받는 수당 중 국내에서\n지급받을 금액 상당액을 초과하여\n받는 금액
8,소법§12 3 거,소령§16①1(국외근로) 500만원,￾￾,M04,월 500만원 이내 금액
9,소법§12 3 더,생산직근로자 야간수당 등,￾￾-1,O01,연 240만원 이내 금액(광산\n근로자의 경우 당해 급여 총액)
10,소법§12 3 러,비과세 식사대(월 20만원 이내),None,None,월 20만원 이내 금액
11,소법§12 3 머,출산·6세 이하 자녀의 보육과 관련하여 받는 급여\n(월 10만원 이내),￾￾-2,Q01,월 10만원 이내 금액_2023년 귀속\n까지만 적용
12,소법§12 3 머,6세 이하 자녀의 보육과 관련하여 받는 급여 (월\n20만원 이내),￾￾-2,Q02,월 20만원 이내 금액
13,소법§12 3 머,자녀 출생일 이후 2년이내에 받는 출산지원금(1회),￾￾-3,Q03,전액
14,소법§12 3 머,자녀 출생일 이후 2년이내에 받는 출산지원금(2회),￾￾-3,Q04,전액
15,소법§12 3 서,교육기본법 제28조제1항에 따라 받는 장학금,￾￾-21,R10,전액
16,소법§12 3 어,소득령 17의3 비과세 직무발명보상금,￾￾-29,R11,None
17,구 조특법§15,주식매수선택권 비과세,￾￾-11,S01,"행사이익 중 연3,000만원 이내금액"
18,조특법§16의2,벤처기업 주식매수 선택권 행사이익 비과세,￾￾-31,U01,행사이익 중 연 2억원 이내 금액
19,조특법\n§88의4⑥,우리사주조합 인출금 비과세(50%),￾￾-14,Y02,인출금의 50%
20,조특법\n§88의4⑥,우리사주조합 인출금 비과세(75%),￾￾-15,Y03,인출금의 75%
21,조특법\n§88의4⑥,우리사주조합 인출금 비과세(100%),￾￾-16,Y04,None

Page 249 - Table 0 DataFrame:

,0,1,2,3,4
0,법조문,비과세 항목,기재란\n번호,코드,비과세 한도
1,소법§12 3 자,소령§12 13 다 (전공의 수련보조수당),⑲,Y22,전액
2,조특법§18,외국인 기술자 소득세 감면,￾￾-12,T01,국내에서 내국인에게 근로를 제공\n하고 지급받는 근로소득(50%)
3,조특법§18,외국인 기술자 소득세 감면,￾￾-36,T02,국내에서 내국인에게 근로를 제공\n하고 지급받는 근로소득(70%)
4,조특법§19,성과공유 중소기업의 경영성과급에 대한\n세액공제 등,￾￾-33,T30,경영성과급의 50%
5,조특법§29의6,중소기업 청년근로자 및 핵심인력 성과\n보상기금 수령액에 대한 소득세 감면 등,￾￾-34,T40,공제금 중 기업부담 기여금의\n50%
6,조특법§29의6,중견기업 청년근로자 및 핵심인력 성과\n보상기금 수령액에 대한 소득세 감면 등,￾￾-37,T41,공제금 중 기업부담 기여금의\n30%
7,조특법§29의6,중소기업 청년근로자 및 핵심인력 성과\n보상기금 수령액에 대한 소득세 감면 등,￾￾-38,T42,(청년근로자)공제금 중 기업부담\n기여금의 90%
8,조특법§29의6,중견기업 청년근로자 및 핵심인력 성과\n보상기금 수령액에 대한 소득세 감면 등,￾￾-39,T43,(청년근로자)공제금 중 기업부담\n기여금의 50%
9,조특법§18의3,내국인 우수인력의 국내복귀에 대한 소득세 감면,￾￾-35,T50,해당 기업 등에서 받는 근로소득의\n50%
10,조특법§30,중소기업 취업자 소득세 감면(70%),￾￾-27,T12,중소기업체에서 받는 근로소득의\n70%
11,조특법§30,중소기업 취업자 소득세 감면(90%),￾￾-32,T13,중소기업체에서 받는 근로소득의\n90%
12,None,조세조약 상 교직자 조항의 소득세 감면,￾￾-28,T20,None

Page 250 - Table 0 DataFrame:

       0      1                 2        3
0  기본 사항  근무처상호              None  사업자등록번호
1  기본 사항     구분  주(현), 종(전), 납세조합     근무기간
2  기본 사항  근로자성명              None     생년월일

Page 250 - Table 1 DataFrame:

       0      1                                                  2
0   None   None                                               생년월일
1   None   None                                          비과세 상세 내역
2     코드    기재란                                              비과세항목
3    M01     ￾￾                           소령§16①1(국외근로) 월 100만원 이내
4    M04     ￾￾                           소령§16①1(국외근로) 월 500만원 이내
5    M03     ￾￾                                      소령§16①2(국외근로)
6    O01   ￾￾-1                      생산직 및 그 관련직에 종사하는 근로자의 야간수당 등
7    O01  ￾￾-40                                 비과세 식사대(월 20만원 이내)
8    Q02   ￾￾-2                    6세 이하의 자녀의 보육 관련 비과세(월 20만원 이내)
9    Q03   ￾￾-3                       자녀 출생일 이후 2년이내에 받는 출산지원금(1회)
10   Q04   ￾￾-3                       자녀 출생일 이후 2년이내에 받는 출산지원금(2회)
11   H10   ￾￾-4                                  소령§12 12 다(연구보조비)
12   H09   ￾￾-4                                  소령§12 12 나(연구보조비)
13   H08   ￾￾-4                     소령§12 12 가(연구보조비)-특별법에 의한 교육기관
14   H07   ￾￾-4                            소령§12 12 가(연구보조비)-고등교육법
15   H06   ￾￾-4                    소령§12 12 가(연구보조비)-유아교육법, 초중등교육법
16   G01   ￾￾-5                                    비과세 학자금(소령§ 11)
17   H11   ￾￾-6                                    소령§12 14 (취재수당)
18   H12   ￾￾-7                                    소령§12 15 (벽지수당)
19   H13   ￾￾-8                       소령§12 16 (천재·지변 등 재해로 받는 급여)
20   K01  ￾￾-10                  작전임무를 수행을 위해 외국에 주둔하는 군인 등이 받는 급여
21   S01  ￾￾-11                                        주식매수선택권 비과세
22   T01  ￾￾-12                                외국인 기술자 소득세 면제(50%)
23   T02  ￾￾-36                                외국인 기술자 소득세 면제(70%)
24   Y02  ￾￾-14                                우리사주조합 인출금 비과세(50%)
25   Y03  ￾￾-15                                우리사주조합 인출금 비과세(75%)
26   Y04  ￾￾-16                               우리사주조합 인출금 비과세(100%)
27   R10  ￾￾-21                           교육기본법 제28조제1항에 따라 받는 장학금
28   H05  ￾￾-18                           소령§12 9~11(경호수당, 승선수당 등)
29   I01  ￾￾-19                      외국정부 또는 국제기관에 근무하는 사람에 대한 비과세
30   Y22     ￾￾                             소령§12 13 다(전공의 수련보조수당)
31   H14  ￾￾-22                           소령§12 13 가(보육교사 근무환경개선비)
32   H15  ￾￾-24                     소령§12 13 나(사립유치원 수석교사·교사의 인건비)
33   H16  ￾￾-24                          정부·공공기관 중 지방이전기관 종사자 이주수당
34   T30  ￾￾-33                        성과공유 중소기업의 경영성과급에 대한 세액공제 등
35   T40  ￾￾-34     중소기업 청년근로자 및 핵심인력 성과보상기금 수령액에 대한 소득세 감면 등(50%)
36   T41  ￾￾-37     중견기업 청년근로자 및 핵심인력 성과보상기금 수령액에 대한 소득세 감면 등(30%)
37   T42  ￾￾-38  중소기업 청년근로자 및 핵심인력 성과보상기금 수령액에 대한 소득세 감면 등(청년 90%)
38   T43  ￾￾-39  중견기업 청년근로자 및 핵심인력 성과보상기금 수령액에 대한 소득세 감면 등(청년 50%)
39   T50  ￾￾-35                          내국인 우수인력의 국내복귀에 대한 소득세 감면
40   T12  ￾￾-27                    중소기업에 취업하는 청년 등에 대한 소득세 감면(70%)
41   T13  ￾￾-32                    중소기업에 취업하는 청년 등에 대한 소득세 감면(90%)
42   T20  ￾￾-28                              조세조약 상 교직자 조항의 소득세 감면

Page 252 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...
1,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분,거주구분,거주구분,거주자1/비거주자2,거주자1/비거주자2,거주자1/비거주자2,거주자1/비거주자2
2,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주지국,거주지국,거주지국,거주지국코드,거주지국코드,거주지국코드,거주지국코드
3,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,내·외국인,내·외국인,내·외국인,내국인1 /외국인9,내국인1 /외국인9,내국인1 /외국인9,내국인1 /외국인9
4,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,외국인단일세율적용,외국인단일세율적용,외국인단일세율적용,외국인단일세율적용,외국인단일세율적용,외국인단일세율적용,여 1 / 부 2
5,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,여 1 / 부 2
6,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,종교관련종사자 여부,종교관련종사자 여부,종교관련종사자 여부,종교관련종사자 여부,종교관련종사자 여부,종교관련종사자 여부,여 1 / 부 2
7,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,국적,국적,국적,국적코드,국적코드,국적코드,국적코드
8,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,세대주 여부,세대주 여부,세대주 여부,"세대주1, 세대원2","세대주1, 세대원2","세대주1, 세대원2","세대주1, 세대원2"
9,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,연말정산 구분,연말정산 구분,연말정산 구분,"계속근로1, 중도퇴사2","계속근로1, 중도퇴사2","계속근로1, 중도퇴사2","계속근로1, 중도퇴사2"
10,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...
11,징수 의무자,① 법인명(상호) 한강건설(주),① 법인명(상호) 한강건설(주),① 법인명(상호) 한강건설(주),① 법인명(상호) 한강건설(주),① 법인명(상호) 한강건설(주),① 법인명(상호) 한강건설(주),② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0
12,징수 의무자,③ 사업자등록번호 123-81-*****,③ 사업자등록번호 123-81-*****,③ 사업자등록번호 123-81-*****,③ 사업자등록번호 123-81-*****,③ 사업자등록번호 123-81-*****,③ 사업자등록번호 123-81-*****,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******
13,징수 의무자,③-1 사업자단위과세자 여부\n여1 / 부2,③-1 사업자단위과세자 여부\n여1 / 부2,③-1 사업자단위과세자 여부\n여1 / 부2,③-1 사업자단위과세자 여부\n여1 / 부2,③-1 사업자단위과세자 여부\n여1 / 부2,③-1 사업자단위과세자 여부\n여1 / 부2,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호
14,징수 의무자,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000
15,소득자,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호),⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호)
16,소득자,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길
17,Ⅰ 근 무 처 별 소 득 명 세,구분,구분,구분,구분,주(현),종(전),종(전),종(전),종(전),종(전),￾￾-1 납세조합,￾￾-1 납세조합,￾￾-1 납세조합,합 계,합 계
18,Ⅰ 근 무 처 별 소 득 명 세,⑨ 근무처명,⑨ 근무처명,⑨ 근무처명,⑨ 근무처명,한강건설(주),None,None,None,None,None,None,None,None,None,None
19,Ⅰ 근 무 처 별 소 득 명 세,⑩ 사업자등록번호,⑩ 사업자등록번호,⑩ 사업자등록번호,⑩ 사업자등록번호,123-81-*****,None,None,None,None,None,None,None,None,None,None
20,Ⅰ 근 무 처 별 소 득 명 세,⑪ 근무기간,⑪ 근무기간,⑪ 근무기간,⑪ 근무기간,24.1.1.~24.12.31.,~,~,~,~,~,~,~,~,24.1.1.~24.12.31.,24.1.1.~24.12.31.
21,Ⅰ 근 무 처 별 소 득 명 세,⑫ 감면기간,⑫ 감면기간,⑫ 감면기간,⑫ 감면기간,~,~,~,~,~,~,~,~,~,~,~
22,Ⅰ 근 무 처 별 소 득 명 세,⑬ 급여,⑬ 급여,⑬ 급여,⑬ 급여,"39,000,000",None,None,None,None,None,None,None,None,"39,000,000","39,000,000"
23,Ⅰ 근 무 처 별 소 득 명 세,⑭ 상여,⑭ 상여,⑭ 상여,⑭ 상여,"26,400,000",None,None,None,None,None,None,None,None,"26,400,000","26,400,000"
24,Ⅰ 근 무 처 별 소 득 명 세,⑮ 인정상여,⑮ 인정상여,⑮ 인정상여,⑮ 인정상여,None,None,None,None,None,None,None,None,None,None,None
25,Ⅰ 근 무 처 별 소 득 명 세,⑮-1 주식매수선택권 행사이익,⑮-1 주식매수선택권 행사이익,⑮-1 주식매수선택권 행사이익,⑮-1 주식매수선택권 행사이익,None,None,None,None,None,None,None,None,None,None,None
26,Ⅰ 근 무 처 별 소 득 명 세,⑮-2 우리사주조합인출금,⑮-2 우리사주조합인출금,⑮-2 우리사주조합인출금,⑮-2 우리사주조합인출금,None,None,None,None,None,None,None,None,None,None,None
27,Ⅰ 근 무 처 별 소 득 명 세,⑮-3 임원 퇴직소득금액 한도초과액,⑮-3 임원 퇴직소득금액 한도초과액,⑮-3 임원 퇴직소득금액 한도초과액,⑮-3 임원 퇴직소득금액 한도초과액,None,None,None,None,None,None,None,None,None,None,None
28,Ⅰ 근 무 처 별 소 득 명 세,⑮-4 직무발명보상금,⑮-4 직무발명보상금,⑮-4 직무발명보상금,⑮-4 직무발명보상금,None,None,None,None,None,None,None,None,None,None,None
29,Ⅰ 근 무 처 별 소 득 명 세,￾￾ 계,￾￾ 계,￾￾ 계,￾￾ 계,"65,400,000",None,None,None,None,None,None,None,None,"65,400,000","65,400,000"
30,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾ 국외근로,￾￾ 국외근로,M0X,M0X,None,None,None,None,None,None,None,None,None,None,None
31,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-1 야간근로수당,￾￾-1 야간근로수당,O0X,O0X,None,None,None,None,None,None,None,None,None,None,None
32,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-2 보육수당,￾￾-2 보육수당,Q0X,Q0X,"2,400,000",None,None,None,None,None,None,None,None,"2,400,000","2,400,000"
33,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-3 출산지원금,￾￾-3 출산지원금,Q0X,Q0X,"5,000,000",None,None,None,None,None,None,None,None,"5,000,000","5,000,000"
34,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-4 연구보조비,￾￾-4 연구보조비,H0X,H0X,None,None,None,None,None,None,None,None,None,None,None
35,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-5 비과세학자금,￾￾-5 비과세학자금,GO1,GO1,"3,000,000",None,None,None,None,None,None,None,None,"3,000,000","3,000,000"
36,Ⅱ 비 과 세 및 감 면 소 득 명 세,~,~,None,None,None,None,None,None,None,None,None,None,None,None,None
37,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-40 비과세식대,￾￾-40 비과세식대,P01,P01,"2,400,000",None,None,None,None,None,None,None,None,"2,400,000","2,400,000"
38,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾ 수련보조수당,￾￾ 수련보조수당,Y22,Y22,None,None,None,None,None,None,None,None,None,None,None
39,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾ 비과세소득 계,￾￾ 비과세소득 계,￾￾ 비과세소득 계,￾￾ 비과세소득 계,"12,800,000",None,None,None,None,None,None,None,None,"12,800,000","12,800,000"
40,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-1 감면소득 계,￾￾-1 감면소득 계,￾￾-1 감면소득 계,￾￾-1 감면소득 계,None,None,None,None,None,None,None,None,None,None,None
41,Ⅲ 세 액 명 세,구분,구분,구분,구분,구분,￾￾ 소득세,￾￾ 소득세,￾￾ 소득세,￾￾ 소득세,￾￾ 지방소득세,￾￾ 지방소득세,￾￾ 지방소득세,￾￾ 농어촌특별세,￾￾ 농어촌특별세,￾￾ 농어촌특별세
42,Ⅲ 세 액 명 세,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n기\n(결정세액란의,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n기\n(결정세액란의,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n기\n(결정세액란의,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n기\n(결정세액란의,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n기\n(결정세액란의,"448,982","448,982","448,982","448,982","44,898","44,898","44,898",None,None,None
43,Ⅲ 세 액 명 세,기 납부 세액,세액을 적습니다)\n￾￾ 주(현)근무지,세액을 적습니다)\n￾￾ 주(현)근무지,세액을 적습니다)\n￾￾ 주(현)근무지,세액을 적습니다)\n￾￾ 주(현)근무지,"1,000,000","1,000,000","1,000,000","1,000,000","100,000","100,000","100,000",None,None,None
44,Ⅲ 세 액 명 세,￾￾ 납부특례세액,￾￾ 납부특례세액,￾￾ 납부특례세액,￾￾ 납부특례세액,￾￾ 납부특례세액,None,None,None,None,None,None,None,None,None,None
45,Ⅲ 세 액 명 세,￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),"-551,018","-551,018","-551,018","-551,018","-55,102","-55,102","-55,102",None,None,None
46,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...

Page 253 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8
0,￾￾ 종합소득 과세표준,￾￾ 종합소득 과세표준,￾￾ 종합소득 과세표준,￾￾ 종합소득 과세표준,￾￾ 종합소득 과세표준,￾￾ 종합소득 과세표준,￾￾ 종합소득 과세표준,￾￾ 종합소득 과세표준,"37,010,000"
1,￾￾ 산출세액,￾￾ 산출세액,￾￾ 산출세액,￾￾ 산출세액,￾￾ 산출세액,￾￾ 산출세액,￾￾ 산출세액,￾￾ 산출세액,"4,291,500"
2,세 액 감 면\n세,￾￾ ｢소득세법｣\n￾￾ ｢조세특례제한법｣(￾￾ 제외)\n￾￾ ｢조세특례제한법｣ 제...,￾￾ ｢소득세법｣\n￾￾ ｢조세특례제한법｣(￾￾ 제외)\n￾￾ ｢조세특례제한법｣ 제...,￾￾ ｢소득세법｣\n￾￾ ｢조세특례제한법｣(￾￾ 제외)\n￾￾ ｢조세특례제한법｣ 제...,￾￾ ｢소득세법｣\n￾￾ ｢조세특례제한법｣(￾￾ 제외)\n￾￾ ｢조세특례제한법｣ 제...,￾￾ ｢소득세법｣\n￾￾ ｢조세특례제한법｣(￾￾ 제외)\n￾￾ ｢조세특례제한법｣ 제...,￾￾ ｢소득세법｣\n￾￾ ｢조세특례제한법｣(￾￾ 제외)\n￾￾ ｢조세특례제한법｣ 제...,￾￾ ｢소득세법｣\n￾￾ ｢조세특례제한법｣(￾￾ 제외)\n￾￾ ｢조세특례제한법｣ 제...,"660,000\n150,000\n700,000\n1,000,000\n120,000\..."
3,세 액 감 면\n세,￾￾ ｢조세특례제한법｣(￾￾ 제외),￾￾ ｢조세특례제한법｣(￾￾ 제외),￾￾ ｢조세특례제한법｣(￾￾ 제외),￾￾ ｢조세특례제한법｣(￾￾ 제외),￾￾ ｢조세특례제한법｣(￾￾ 제외),￾￾ ｢조세특례제한법｣(￾￾ 제외),￾￾ ｢조세특례제한법｣(￾￾ 제외),None
4,세 액 감 면\n세,￾￾ ｢조세특례제한법｣ 제30조,￾￾ ｢조세특례제한법｣ 제30조,￾￾ ｢조세특례제한법｣ 제30조,￾￾ ｢조세특례제한법｣ 제30조,￾￾ ｢조세특례제한법｣ 제30조,￾￾ ｢조세특례제한법｣ 제30조,￾￾ ｢조세특례제한법｣ 제30조,None
...,...,...,...,...,...,...,...,...,...
56,세\n액\n공\n제,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,세액공제액,None
57,세\n액\n공\n제,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,세액공제액,None
58,세\n액\n공\n제,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,"3,842,518"
59,세액공제액\n공제대상금액\n10만원 이하\n㉮ 정치 자금 기부금\n액\n세액공제액\...,세액공제액\n공제대상금액\n10만원 이하\n㉮ 정치 자금 기부금\n액\n세액공제액\...,세액공제액\n공제대상금액\n10만원 이하\n㉮ 정치 자금 기부금\n액\n세액공제액\...,세액공제액\n공제대상금액\n10만원 이하\n㉮ 정치 자금 기부금\n액\n세액공제액\...,세액공제액\n공제대상금액\n10만원 이하\n㉮ 정치 자금 기부금\n액\n세액공제액\...,세액공제액\n공제대상금액\n10만원 이하\n㉮ 정치 자금 기부금\n액\n세액공제액\...,세액공제액\n공제대상금액\n10만원 이하\n㉮ 정치 자금 기부금\n액\n세액공제액\...,세액공제액\n공제대상금액\n10만원 이하\n㉮ 정치 자금 기부금\n액\n세액공제액\...,"630,000\n100,000\n90,909\n100,000\n15,000\n100..."
60,￾￾ 실효세율(%) (￾￾/￾￾)×100,￾￾ 실효세율(%) (￾￾/￾￾)×100,￾￾ 실효세율(%) (￾￾/￾￾)×100,￾￾ 실효세율(%) (￾￾/￾￾)×100,￾￾ 실효세율(%) (￾￾/￾￾)×100,￾￾ 실효세율(%) (￾￾/￾￾)×100,￾￾ 실효세율(%) (￾￾/￾￾)×100,￾￾ 실효세율(%) (￾￾/￾￾)×100,0.69

Page 254 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,"￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...",...,"￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코...","￾￾ 소득·세액공제 명세[인적공제항목은 해당란에 ""○""표시(장애인 해당 시 해당 코..."
1,인적공제 항목,인적공제 항목,인적공제 항목,인적공제 항목,인적공제 항목,인적공제 항목,인적공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,...,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목
2,관계 코드,성명,성명,기본공제,기본공제,경로우대,출산입양,자료 구분,보험료,보험료,...,보험료,의료비,의료비,의료비,의료비,의료비,의료비,교육비,교육비,교육비
3,내·외\n국인,주민등록번호,주민등록번호,부녀자,한부모,장애인,자녀,자료 구분,건강,고용,...,장애인\n전용 보장성,일반,일반,미숙아·\n선천성\n이상아,난임,"6세이하,\n65세이상,\n장애인, 건강\n보헝산정특례자",실손 의료 보험금,일반,일반,장애인
4,인적공제 항목에\n해당하는 인원수를\n적습니다.,인적공제 항목에\n해당하는 인원수를\n적습니다.,인적공제 항목에\n해당하는 인원수를\n적습니다.,None,None,None,None,국세청,None,None,...,None,"6,000,000","6,000,000",None,None,None,None,"2,700,000","2,700,000",None
5,인적공제 항목에\n해당하는 인원수를\n적습니다.,인적공제 항목에\n해당하는 인원수를\n적습니다.,인적공제 항목에\n해당하는 인원수를\n적습니다.,None,None,None,None,기타,"1,700,000",None,...,None,"550,000","550,000",None,"1,000,000",None,None,"1,850,000","1,850,000",None
6,0,None,None,○,○,None,None,국세청,None,None,...,None,"1,300,000","1,300,000",None,None,None,None,None,None,None
7,None,(근로자 본인),(근로자 본인),None,None,None,None,기타,"1,700,000",None,...,None,"550,000","550,000",None,None,None,None,None,None,None
8,3,황정연,황정연,None,None,None,None,국세청,None,None,...,None,"4,700,000","4,700,000",None,None,None,None,None,None,None
9,1,810701-\n2******,810701-\n2******,None,None,None,None,기타,None,None,...,None,None,None,None,"1,000,000",None,None,None,None,None
10,4,이태현,이태현,○,○,None,None,국세청,None,None,...,None,None,None,None,None,None,None,"2,700,000","2,700,000",None
11,1,050501-\n1******,050501-\n1******,None,None,None,○,기타,None,None,...,None,None,None,None,None,None,None,"650,000","650,000",None
12,4,이태희,이태희,○,○,None,None,국세청,None,None,...,None,None,None,None,None,None,None,None,None,None
13,1,181224-\n4******,181224-\n4******,None,None,None,None,기타,None,None,...,None,None,None,None,None,None,None,"1,200,000","1,200,000",None
14,4,이태영,이태영,○,○,None,○,국세청,None,None,...,None,None,None,None,None,None,None,None,None,None
15,1,240130-\n3******,240130-\n3******,None,None,None,None,기타,None,None,...,None,None,None,None,None,None,None,None,None,None
16,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,...,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목,각종 소득·세액 공제 항목
17,자료 구분,자료 구분,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,...,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,신용카드등 사용액,기부금,기부금
18,자료 구분,자료 구분,신용카드,신용카드,직불카드 등,직불카드 등,현금영수증,현금영수증,도서공연등 사용분\n(총급여 7천만원\n이하자만 기재),도서공연등 사용분\n(총급여 7천만원\n이하자만 기재),...,전통시장\n사용분,전통시장\n사용분,대중교통\n이용분,대중교통\n이용분,대중교통\n이용분,소비증가분,소비증가분,소비증가분,기부금,기부금
19,자료 구분,자료 구분,신용카드,신용카드,직불카드 등,직불카드 등,현금영수증,현금영수증,도서공연등 사용분\n(총급여 7천만원\n이하자만 기재),도서공연등 사용분\n(총급여 7천만원\n이하자만 기재),...,전통시장\n사용분,전통시장\n사용분,대중교통\n이용분,대중교통\n이용분,대중교통\n이용분,2023년\n전체 사용분,2024년\n전체 사용분,2024년\n전체 사용분,기부금,기부금
20,국세청계,국세청계,"10,000,000","10,000,000","5,000,000","5,000,000","7,000,000","7,000,000","1,000,000","1,000,000",...,"3,000,000","3,000,000","2,000,000","2,000,000","2,000,000","25,000,000","28,000,000","28,000,000",None,None
21,기타계,기타계,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,"800,000","800,000"
22,국세청,국세청,"10,000,000","10,000,000","5,000,000","5,000,000","7,000,000","7,000,000","1,000,000","1,000,000",...,"3,000,000","3,000,000","2,000,000","2,000,000","2,000,000",None,None,None,None,None
23,기타,기타,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,"800,000","800,000"
24,국세청,국세청,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
25,기타,기타,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

Page 256 - Table 0 DataFrame:

,0,1,2,3,4,5
0,구 분,관계코드,구 분,관계코드,구 분,관계코드
1,소득자 본인\n(소득세법 §50 ① 1),0,소득자의 직계존속\n(소득세법 §50 ① 3 가),1,배우자의 직계존속\n(소득세법 §50 ① 3 가),2
2,배우자\n(소득세법 §50 ① 2),3,"직계비속(자녀ㆍ손자녀, 입양자)\n(소득세법 §50 ① 3 나)",4,직계비속(코드 4 제외)\n(소득세법 §50 ① 3 나),5
3,형제자매\n(소득세법 §50 ① 3 다),6,수급자(코드1~6제외)\n(소득세법 §50 ① 3 라),7,위탁아동\n(소득세법 §50 ① 3 마),8

Page 257 - Table 0 DataFrame:

,0,1,2,3,4,5
0,구분,법조문,코드,기재란,비과세항목,지급명세서\n작성 여부
1,비과세,소득세법§12 3 가,A01,None,복무 중인 병(兵)이 받는 급여,×
2,비과세,소득세법§12 3 나,B01,None,법률에 따라 동원 직장에서 받는 급여,×
3,비과세,소득세법§12 3 다,C01,None,「산업재해보상보험법」에 따라 지급받는 요양급여 등,×
4,비과세,소득세법§12 3 라,D01,None,「근로기준법」등에 따라 지급받는 요양보상금 등,×
5,비과세,소득세법§12 3 마,E01,None,「고용보험법」 등에 따라 받는 육아휴직급여 등,×
6,비과세,소득세법§12 3 마,E02,None,｢국가공무원법｣ 등에 따라 받는 육아휴직수당 등(사립학교 직원이\n학교의 정관·규칙...,×
7,비과세,소득세법§12 3 바,E10,None,「국민연금법」에 따라 받는 반환일시금(사망으로 받는 것에 한\n함) 및 사망일시금,×
8,비과세,소득세법§12 3 사,F01,None,「공무원연금법」 등에 따라 받는 요양비 등,×
9,비과세,소득세법§12 3 아,G01,￾￾-5,비과세 학자금(소득령§ 11),○
10,비과세,소득세법§12 3 자,H02,None,소득령§12 2 ~ 3(일직료·숙직료 등),×
11,비과세,소득세법§12 3 자,H03,None,소득령§12 3(자가운전보조금),×
12,비과세,소득세법§12 3 자,H04,None,"소득령§12 4, 8(법령에 따라 착용하는 제복 등)",×
13,비과세,소득세법§12 3 자,H05,￾￾-18,"소득령§12 9 ~ 11(경호수당, 승선수당 등)",○
14,비과세,소득세법§12 3 자,H06,￾￾-4,"소득령§12 12 가(연구보조비 등)-「유아교육법」, 「초·중등교육법」",○
15,비과세,소득세법§12 3 자,H07,￾￾-4,소득령§12 12 가(연구보조비 등)-「고등교육법」,○
16,비과세,소득세법§12 3 자,H08,￾￾-4,소득령§12 12 가(연구보조비 등)-특별법에 따른 교육기관,○
17,비과세,소득세법§12 3 자,H09,￾￾-4,소득령§12 12 나(연구보조비 등),○
18,비과세,소득세법§12 3 자,H10,￾￾-4,소득령§12 12 다(연구보조비 등),○
19,비과세,소득세법§12 3 자,H14,￾￾-22,소득령§12 13 가(보육교사 근무환경개선비)-「영유아보육법 시행령」,○
20,비과세,소득세법§12 3 자,H15,￾￾-23,소득령§12 13 나(사립유치원 수석교사·교사의 인건비)-「유아교육법\n시행령」,○
21,비과세,소득세법§12 3 자,H11,￾￾-6,소득령§12 14 (취재수당),○
22,비과세,소득세법§12 3 자,H12,￾￾-7,소득령§12 15 (벽지수당),○
23,비과세,소득세법§12 3 자,H13,￾￾-8,소득령§12 16 (천재·지변 등 재해로 받는 급여),○
24,비과세,소득세법§12 3 자,H16,￾￾-24,소득령§12 17 (정부·공공기관 중 지방이전기관 종사자 이전지원금),○
25,비과세,소득세법§12 3 자,H17,￾￾-30,소득령§12 18(종교관련종사자가 소속 종교단체의 규약 또는 소속 종교\n단체의 의...,○
26,비과세,소득세법§12 3 차,I01,￾￾-19,외국정부 또는 국제기관에 근무하는 사람에 대한 비과세,○
27,비과세,소득세법§12 3 카,J01,None,「국가유공자 등 예우 및 지원에 관한 법률」에 따라 받는 보훈급여\n금 및 학습보조비,×
28,비과세,소득세법§12 3 타,J10,None,「전직대통령 예우에 관한 법률」에 따라 받는 연금,×
29,비과세,소득세법§12 3 파,K01,￾￾-10,작전임무 수행을 위해 외국에 주둔하는 군인 등이 받는 급여,○
30,비과세,소득세법§12 3 하,L01,None,종군한 군인 등이 전사한 경우 해당 과세기간의 급여,×
31,비과세,소득세법§12 3 거,M01,￾￾,소득령§16①1(국외 등에서 근로에 대한 보수) 100만원,○
32,비과세,소득세법§12 3 거,M02,￾￾,소득령§16①1(국외 등에서 근로에 대한 보수) 300만원\n- 2023년 귀속분까...,○
33,비과세,소득세법§12 3 거,M03,￾￾,소득령§16①2(국외근로),○
34,비과세,소득세법§12 3 거,M03,￾￾,소득령§16①1(국외 등에서 근로에 대한 보수) 500만원,None

Page 258 - Table 0 DataFrame:

,0,1,2,3,4,5
0,구분,법조문,코드,기재란,비과세항목,지급명세서\n작성 여부
1,비과세,소득세법§12 3 너,N01,None,「국민건강보험법」 등에 따라 사용자 등이 부담하는 보험료,×
2,비과세,소득세법§12 3 더,O01,￾￾-1,생산직 등에 종사하는 근로자의 야간수당 등,○
3,비과세,소득세법§12 3 러,P01,￾￾-40,비과세 식사대(월 20만원 이하),○
4,비과세,소득세법§12 3 러,P02,None,현물 급식,×
5,비과세,소득세법§12 3 머,Q01,￾￾-2,"출산, 6세 이하의 자녀의 보육 관련 비과세 급여(월 10만원 이내)",○
6,비과세,소득세법§12 3 머,Q02,￾￾-2,6세 이하의 자녀의 보육 관련 비과세 급여(월 20만원 이내),○
7,비과세,소득세법§12 3 머,Q03,￾￾-3,자녀 출생일 이후 2년 이내에 받는출산지원금(1회),○
8,비과세,소득세법§12 3 머,Q04,￾￾-3,자녀 출생일 이후 2년 이내에 받는출산지원금(2회),○
9,비과세,소득세법§12 3 버,R01,None,국군포로가 지급받는 보수 등,×
10,비과세,소득세법§12 3 서,R10,￾￾-21,「교육기본법」 제28조제1항에 따라 받는 장학금,○
11,비과세,소득세법§12 3 어,R11,￾￾-29,소득령 17의3 비과세 직무발명보상금,○
12,비과세,소득세법§12 3 저,V01,None,사택 제공 이익,×
13,비과세,소득세법§12 3 저,V02,None,주택 자금 저리·무상 대여 이익,×
14,비과세,소득세법§12 3 저,V03,None,종업원 등을 수익자로하는 보험료·신탁부금·공제부금,×
15,비과세,소득세법§12 3 저,V04,None,공무원이 받는 상금과 부상(연 240만원 이내),×
16,비과세,소득세법§12 3 저,V05,None,｢영유아보육법 시행령｣에 따라 사업주가 부담하는 보육비용,×
17,비과세,구 조특법§15,S01,￾￾-11,주식매수선택권 비과세,○
18,비과세,조특법§16의2,U01,￾￾-31,벤처기업 주식매수 선택권 행사이익 비과세,○
19,비과세,조특법§88의4⑥,Y02,￾￾-14,우리사주조합 인출금 비과세(50%),○
20,비과세,조특법§88의4⑥,Y03,￾￾-15,우리사주조합 인출금 비과세(75%),○
21,비과세,조특법§88의4⑥,Y04,￾￾-16,우리사주조합 인출금 비과세(100%),○
22,비과세,소득세법§12 3 자,Y22,￾￾,소득령§12 13 다(전공의 수련보조수당),○
23,감면,조특법§18,T01,￾￾-12,외국인 기술자 소득세 감면(50%),○
24,감면,조특법§18,T02,￾￾-36,외국인 기술자 소득세 감면(70%),○
25,감면,조특법§19,T30,￾￾-33,성과공유 중소기업의 경영성과급에 대한 세액공제 등,○
26,감면,조특법§29의6,T40,￾￾-34,중소기업 청년근로자 및 핵심인력 성과보상기금 수령액에 대한\n소득세 감면 등(50%),○
27,감면,조특법§29의6,T41,￾￾-37,중견기업 청년근로자 및 핵심인력 성과보상기금 수령액에 대한\n소득세 감면 등(30%),○
28,감면,조특법§29의6,T42,￾￾-38,중소기업 청년근로자 및 핵심인력 성과보상기금 수령액에 대한\n소득세 감면 등(청년 ...,○
29,감면,조특법§29의6,T43,￾￾-39,중견기업 청년근로자 및 핵심인력 성과보상기금 수령액에 대한\n소득세 감면 등(청년 ...,○
30,감면,조특법§18의3,T50,￾￾-35,내국인 우수인력의 국내복귀에 대한 소득세 감면,○
31,감면,조특법§30,T12,￾￾-27,중소기업 취업자 소득세 감면(70%),○
32,감면,조특법§30,T13,￾￾-32,중소기업 취업자 소득세 감면(90%),○
33,감면,조세조약,T20,￾￾-28,조세조약상 소득세 면제(교사·교수),None

Page 259 - Table 0 DataFrame:

,0,1,2,3
0,1. 인적사항,① 상 호,한강건설(주),② 사업자등록번호
1,1. 인적사항,③ 성 명,이강모,④ 주민등록번호
2,1. 인적사항,⑤ 주 소,None,None
3,1. 인적사항,⑥ 사업장 소재지,서울특별시 종로구 종로5길 1000(전화번호: 02-0000-0000 ),서울특별시 종로구 종로5길 1000(전화번호: 02-0000-0000 )

Page 259 - Table 1 DataFrame:

      0       1               2          3        4
0  None  금융회사 등  계좌번호 (또는 증권번호)       납입금액     None
1  퇴직연금    00보험    987-65-*****  1,000,000  120,000

Page 259 - Table 2 DataFrame:

      0       1              2          3        4
0  None  금융회사 등  계좌번호(또는 증권번호)       납입금액     None
1  연금저축    ㅁㅁ은행    *****-67890  2,000,000  240,000

Page 260 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8
0,⑦ 임대인성명\n(상 호),⑧ 주민등록번호\n(사업자번호),⑨ 유형,⑩ 계약면적\n(㎡),⑪\n임대차계약서 상 주소지,⑫ 계약서 상 임대차 계약기간,⑫ 계약서 상 임대차 계약기간,⑬ 연간월세액(원),⑭\n세액공제금액(원)
1,⑦ 임대인성명\n(상 호),⑧ 주민등록번호\n(사업자번호),⑨ 유형,⑩ 계약면적\n(㎡),⑪\n임대차계약서 상 주소지,개시일,종료일,⑬ 연간월세액(원),⑭\n세액공제금액(원)

Page 260 - Table 1 DataFrame:

          0         1               2          3        4        5        6
0  ⑮ 대주(貸主)  ⑯ 주민등록번호  ⑰\n금전소비대차 계약기간  ⑱ 차입금 이자율  원리금 상환액  원리금 상환액  원리금 상환액
1  ⑮ 대주(貸主)  ⑯ 주민등록번호  ⑰\n금전소비대차 계약기간  ⑱ 차입금 이자율      ⑲ 계     ⑳ 원금    ￾￾ 이자

Page 260 - Table 2 DataFrame:

,0,1,2,3,4,5,6,7
0,￾￾ 임대인성명\n(상\n호),￾￾ 주민등록번호\n(사업자번호),￾￾ 유형,￾￾ 계약면적\n(㎡),￾￾\n임대차계약서상 주소지,￾￾ 계약서상 임대차 계약기간,￾￾ 계약서상 임대차 계약기간,￾￾\n전세보증금(원)
1,￾￾ 임대인성명\n(상\n호),￾￾ 주민등록번호\n(사업자번호),￾￾ 유형,￾￾ 계약면적\n(㎡),￾￾\n임대차계약서상 주소지,개시일,종료일,￾￾\n전세보증금(원)

Page 261 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7
0,⑦ 자녀 성명,⑧ 주민등록번호,출산지원금,출산지원금,출산지원금,⑫ 지급처\n(사업자\n등록번호),⑬ 주(현)\n근무지\n여부,⑭\n사업주·지배주주와\n특수관계자\n(친족관계) 여부
1,⑦ 자녀 성명,⑧ 주민등록번호,⑨지급받은\n날,⑩ 지급받은\n금액,⑪지급회차\n[1 또는 2],⑫ 지급처\n(사업자\n등록번호),⑬ 주(현)\n근무지\n여부,⑭\n사업주·지배주주와\n특수관계자\n(친족관계) 여부
2,이태영,241030-3******,2024.11.30,"5,000,000",1,123-81-\n*****,여,부

Page 262 - Table 0 DataFrame:

      0               1           2          3     4
0    성명            주민번호        총지급액     원천징수세액    비고
1    합계              8명  22,230,000  1,198,170  None
2   김△△  000000-0000000   2,500,000     51,180  None
3   최△△  000000-0000000   3,000,000    113,390  None
4   박○○  000000-0000000   2,300,000     78,600  None
5   박△△  000000-0000000     500,000          -  None
6   이○○  000000-0000000   5,200,000    465,700  None
7   정△△  000000-0000000   2,100,000     45,000  None
8   송○○  000000-0000000   2,000,000     62,000  None
9  None  000000-0000000   4,630,000    382,300  None

Page 262 - Table 1 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10
0,성명,"총지급액\n(전,현근무지\n포함)",작성대상\n비과세,결정세액,전근무지\n총지급액,기납부세액,기납부세액,기납부세액,전 근무지\n상호,전 근무지\n사업자번호,차감\n징수세액
1,성명,"총지급액\n(전,현근무지\n포함)",작성대상\n비과세,결정세액,전근무지\n총지급액,계,현근무지,전근무지,전 근무지\n상호,전 근무지\n사업자번호,차감\n징수세액
2,*\n고◎◎,"7,500,000","300,000",-,None,"620,820","620,820",None,None,None,"- 620,820"
3,계속근로자합계,"323,231,250","12,290,000","10,994,140","36,690,720","14,895,170","12,356,850","2,538,320",None,None,"- 3,901,030"
4,김△△,"30,000,000","1,200,000","586,230",None,"855,980","855,980",None,None,None,"- 269,750"
5,최△△,"45,000,000","2,200,000","1,500,760",None,"2,500,370","2,500,370",None,None,None,"- 999,610"
6,박○○*,"38,700,000","670,000","825,700","11,690,720","1,571,980","676,980","895,000",㈜◯◯물산,111-81-00010,"- 746,280"
7,박△△*,"32,600,000","1,800,000","1,585,420","10,000,000","1,001,470","326,470","675,000",△△백화점,211-03-00007,"583,950"
8,이○○,"82,003,950","2,400,000","4,250,950",None,"5,900,350","5,900,350",None,None,None,"- 1,649,400"
9,정△△,"12,600,800","720,000",-,None,"312,000","312,000",None,None,None,"- 312,000"
10,송○○,"24,000,000","1,200,000","307,030",None,"521,900","521,900",None,None,None,"- 214,870"
11,None,"58,326,500","2,100,000","1,938,050","15,000,000","2,231,120","1,262,800","968,320",㈜◯◯전자,312-81-00080,None

Page 263 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10
0,귀속연월,지급연월,소득구분,코드,인원,총지급액,징수세액,징수세액,징수세액,당월조정\n환급,납부세액
1,귀속연월,지급연월,소득구분,코드,인원,총지급액,소득세,농특세,가산세,당월조정\n환급,납부세액
2,202401,202401,간이세액,A01,6,"25,300,000","1,225,800",None,None,None,"1,225,800"
3,202402,202402,간이세액,A01,6,"24,600,600","1,136,240",None,None,None,None
4,202402,202402,연말정산,A04,6,"237,650,000","- 2,582,650",None,None,None,None
5,202402,202402,가 감 계,A10,12,"262,250,600","- 1,446,410",None,None,None,None
6,202403,202403,간이세액,A01,6,"23,800,000","1,060,000",None,None,None,"1,060,000"
7,202404,202404,간이세액,A01,6,"21,389,000","968,720",None,None,None,None
8,202404,202404,중도퇴사,A02,1,"7,500,000","- 620,820",None,None,None,None
9,202404,202404,가 감 계,A10,7,"28,889,000","347,900",None,None,"347,900",None
10,202404,202404,퇴직소득,A22,1,"3,520,000","120,820",None,None,"38,510","82,310"
11,202405,202405,간이세액,A01,8,"26,470,820","1,382,420",None,None,None,"1,382,420"
12,202406,202406,간이세액,A01,8,"21,210,890","1,195,750",None,None,None,"1,195,750"
13,202407,202407,간이세액,A01,8,"21,350,760","1,221,820",None,None,None,"1,221,820"
14,202408,202408,간이세액,A01,8,"23,850,850","890,790",None,None,None,"890,790"
15,202409,202409,간이세액,A01,8,"24,682,440","905,620",None,None,None,"905,620"
16,202410,202410,간이세액,A01,8,"29,720,650","1,110,890",None,None,None,"1,110,890"
17,202411,202411,간이세액,A01,8,"24,901,140","992,750",None,None,None,"992,750"
18,None,202412,간이세액,A01,8,"26,763,380","886,870",None,None,None,None

Page 263 - Table 1 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11
0,귀속 연월,지급 연월,전월 미환급세액의 계산,전월 미환급세액의 계산,전월 미환급세액의 계산,당월 발생 환급세액,당월 발생 환급세액,당월 발생 환급세액,조정대상\n환급세액,당월조정\n환급세액,차월 환급세액,환급\n신청액
1,귀속 연월,지급 연월,전월\n미환급세액,기환급\n세액,차감 잔액,일반 환급,신탁 재산,그밖의\n환급세액,조정대상\n환급세액,당월조정\n환급세액,차월 환급세액,환급\n신청액
2,202401,202401,None,None,-,None,None,-,-,-,-,None
3,202402,202402,None,None,-,"1,446,410",None,None,"1,446,410",-,"1,446,410",None
4,202403,202403,"1,446,410",None,"1,446,410",None,None,None,"1,446,410","1,060,000","386,410",None
5,None,202404,"386,410",None,"386,410",None,None,None,"386,410","386,410",-,None

Page 264 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,...,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,② 귀속연월,② 귀속연월,② 귀속연월,② 귀속연월,② 귀속연월,2025년 2월,2025년 2월,2025년 2월,2025년 2월
1,매월,반기,수정,연말,연말,소득 처분,환급 신청,환급 신청,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,...,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,③ 지급연월,③ 지급연월,③ 지급연월,③ 지급연월,③ 지급연월,2025년 2월,2025년 2월,2025년 2월,2025년 2월
2,원천징수\n의 무 자,원천징수\n의 무 자,법인명(상호),법인명(상호),법인명(상호),한강건설(주),한강건설(주),한강건설(주),한강건설(주),대표자(성명),...,김00,일괄납부 여부,일괄납부 여부,일괄납부 여부,일괄납부 여부,일괄납부 여부,"여, 부","여, 부","여, 부","여, 부"
3,원천징수\n의 무 자,원천징수\n의 무 자,법인명(상호),법인명(상호),법인명(상호),한강건설(주),한강건설(주),한강건설(주),한강건설(주),대표자(성명),...,김00,사업자단위 과세 여부,사업자단위 과세 여부,사업자단위 과세 여부,사업자단위 과세 여부,사업자단위 과세 여부,"여, 부","여, 부","여, 부","여, 부"
4,원천징수\n의 무 자,원천징수\n의 무 자,사업자(주민)\n등록번호,사업자(주민)\n등록번호,사업자(주민)\n등록번호,123-81-*****,123-81-*****,123-81-*****,123-81-*****,사업장 소재지,...,서울 종로 종로5길 1000,전화번호,전화번호,전화번호,전화번호,전화번호,02-0000-0000,02-0000-0000,02-0000-0000,02-0000-0000
5,원천징수\n의 무 자,원천징수\n의 무 자,사업자(주민)\n등록번호,사업자(주민)\n등록번호,사업자(주민)\n등록번호,123-81-*****,123-81-*****,123-81-*****,123-81-*****,사업장 소재지,...,서울 종로 종로5길 1000,전자우편주소,전자우편주소,전자우편주소,전자우편주소,전자우편주소,nhk12@nts.go.kr,nhk12@nts.go.kr,nhk12@nts.go.kr,nhk12@nts.go.kr
6,❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),...,❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원),❶ 원천징수 명세 및 납부세액 (단위：원)
7,소득자 소득구분,소득자 소득구분,소득자 소득구분,소득자 소득구분,소득자 소득구분,소득자 소득구분,코드,코드,원천징수명세,원천징수명세,...,원천징수명세,원천징수명세,원천징수명세,원천징수명세,⑨ 당월 조정\n환급세액,⑨ 당월 조정\n환급세액,납부세액,납부세액,납부세액,납부세액
8,소득자 소득구분,소득자 소득구분,소득자 소득구분,소득자 소득구분,소득자 소득구분,소득자 소득구분,코드,코드,"소득지급(과세 미달,\n일부 비과세 포함)","소득지급(과세 미달,\n일부 비과세 포함)",...,징수세액,징수세액,징수세액,징수세액,⑨ 당월 조정\n환급세액,⑨ 당월 조정\n환급세액,⑩ 소득세 등\n(가산세 포함),⑩ 소득세 등\n(가산세 포함),⑩ 소득세 등\n(가산세 포함),⑪ 농어촌\n특별세
9,소득자 소득구분,소득자 소득구분,소득자 소득구분,소득자 소득구분,소득자 소득구분,소득자 소득구분,코드,코드,④ 인원,④ 인원,...,⑦ 농어촌특별세,⑦ 농어촌특별세,⑧ 가산세,⑧ 가산세,⑨ 당월 조정\n환급세액,⑨ 당월 조정\n환급세액,⑩ 소득세 등\n(가산세 포함),⑩ 소득세 등\n(가산세 포함),⑩ 소득세 등\n(가산세 포함),⑪ 농어촌\n특별세
10,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,근로 소득,간이세액,간이세액,간이세액,간이세액,A01,A01,8,8,...,None,None,None,None,None,None,None,None,None,None
11,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,근로 소득,중도퇴사,중도퇴사,중도퇴사,중도퇴사,A02,A02,None,None,...,None,None,None,None,None,None,None,None,None,None
12,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,근로 소득,일용근로,일용근로,일용근로,일용근로,A03,A03,None,None,...,None,None,None,None,None,None,None,None,None,None
13,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,근로 소득,연말 정산,합계,합계,합계,A04,A04,8,8,...,None,None,None,None,None,None,None,None,None,None
14,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,근로 소득,연말 정산,분납신청,분납신청,분납신청,A05,A05,None,None,...,None,None,None,None,None,None,None,None,None,None
15,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,근로 소득,연말 정산,납부금액,납부금액,납부금액,A06,A06,None,None,...,None,None,None,None,None,None,None,None,None,None
16,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,근로 소득,가감계,가감계,가감계,가감계,A10,A10,16,16,...,None,None,None,None,None,None,None,None,None,None
17,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,퇴직 소득,연금계좌,연금계좌,연금계좌,연금계좌,A21,A21,None,None,...,None,None,None,None,None,None,None,None,None,None
18,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,퇴직 소득,그 외,그 외,그 외,그 외,A22,A22,None,None,...,None,None,None,None,None,None,None,None,None,None
19,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,퇴직 소득,가감계,가감계,가감계,가감계,A20,A20,None,None,...,None,None,None,None,None,None,None,None,None,None
20,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,사업 소득,매월징수,매월징수,매월징수,매월징수,A25,A25,None,None,...,None,None,None,None,None,None,None,None,None,None
21,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,사업 소득,연말정산,연말정산,연말정산,연말정산,A26,A26,None,None,...,None,None,None,None,None,None,None,None,None,None
22,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,사업 소득,가감계,가감계,가감계,가감계,A30,A30,None,None,...,None,None,None,None,None,None,None,None,None,None
23,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,기타 소득,연금계좌,연금계좌,연금계좌,연금계좌,A41,A41,None,None,...,None,None,None,None,None,None,None,None,None,None
24,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,기타 소득,종교인\n소득,매월징수,매월징수,매월징수,A43,A43,None,None,...,None,None,None,None,None,None,None,None,None,None
25,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,기타 소득,종교인\n소득,연말정산,연말정산,연말정산,A44,A44,None,None,...,None,None,None,None,None,None,None,None,None,None
26,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,기타 소득,가상자산,가상자산,가상자산,가상자산,A49,A49,None,None,...,None,None,None,None,None,None,None,None,None,None
27,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,기타 소득,인적용역,인적용역,인적용역,인적용역,A59,A59,None,None,...,None,None,None,None,None,None,None,None,None,None
28,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,기타 소득,그 외,그 외,그 외,그 외,A42,A42,1,1,...,None,None,None,None,None,None,None,None,None,None
29,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,기타 소득,가감계,가감계,가감계,가감계,A40,A40,1,1,...,None,None,None,None,"80,000","80,000",None,None,None,None
30,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,연금 소득,연금계좌,연금계좌,연금계좌,연금계좌,A48,A48,None,None,...,None,None,None,None,None,None,None,None,None,None
31,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,연금 소득,공적연금(매월),공적연금(매월),공적연금(매월),공적연금(매월),A45,A45,None,None,...,None,None,None,None,None,None,None,None,None,None
32,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,연금 소득,연말정산,연말정산,연말정산,연말정산,A46,A46,None,None,...,None,None,None,None,None,None,None,None,None,None
33,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,연금 소득,가감계,가감계,가감계,가감계,A47,A47,None,None,...,None,None,None,None,None,None,None,None,None,None
34,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,이자소득,이자소득,이자소득,이자소득,이자소득,A50,A50,None,None,...,None,None,None,None,None,None,None,None,None,None
35,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,배당소득,배당소득,배당소득,배당소득,배당소득,A60,A60,None,None,...,None,None,None,None,None,None,None,None,None,None
36,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,금융투자소득,금융투자소득,금융투자소득,금융투자소득,금융투자소득,A71,A71,None,None,...,None,None,None,None,None,None,None,None,None,None
37,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,저축해지 추징세액 등,저축해지 추징세액 등,저축해지 추징세액 등,저축해지 추징세액 등,저축해지 추징세액 등,A69,A69,None,None,...,None,None,None,None,None,None,None,None,None,None
38,개 인 ⁀ 거 주 자 · 비 거 주 자 ⌣,비거주자 양도소득,비거주자 양도소득,비거주자 양도소득,비거주자 양도소득,비거주자 양도소득,A70,A70,None,None,...,None,None,None,None,None,None,None,None,None,None
39,법인\n내·외국법인원천,법인\n내·외국법인원천,법인\n내·외국법인원천,법인\n내·외국법인원천,법인\n내·외국법인원천,법인\n내·외국법인원천,A80,A80,None,None,...,None,None,None,None,None,None,None,None,None,None
40,수정신고(세액),수정신고(세액),수정신고(세액),수정신고(세액),수정신고(세액),수정신고(세액),A90,A90,None,None,...,None,None,None,None,None,None,None,None,None,None
41,총 합계,총 합계,총 합계,총 합계,총 합계,총 합계,A99,A99,17,17,...,None,None,None,None,"80,000","80,000",None,None,None,None
42,❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),...,❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원)
43,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,당월 발생 환급세액,당월 발생 환급세액,당월 발생 환급세액,...,￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 당월조정\n환급세액계,￾￾ 당월조정\n환급세액계,￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 환 급 신청액,￾￾ 환 급 신청액
44,⑫ 전월미환급\n세액,⑫ 전월미환급\n세액,⑬ 기환급\n신청세액,⑬ 기환급\n신청세액,⑭ 차감잔액\n(⑫-⑬),⑭ 차감잔액\n(⑫-⑬),⑭ 차감잔액\n(⑫-⑬),⑮ 일반환급,⑮ 일반환급,⑮ 일반환급,...,￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 당월조정\n환급세액계,￾￾ 당월조정\n환급세액계,￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 환 급 신청액,￾￾ 환 급 신청액
45,⑫ 전월미환급\n세액,⑫ 전월미환급\n세액,⑬ 기환급\n신청세액,⑬ 기환급\n신청세액,⑭ 차감잔액\n(⑫-⑬),⑭ 차감잔액\n(⑫-⑬),⑭ 차감잔액\n(⑫-⑬),⑮ 일반환급,⑮ 일반환급,⑮ 일반환급,...,￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 당월조정\n환급세액계,￾￾ 당월조정\n환급세액계,￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 환 급 신청액,￾￾ 환 급 신청액
46,None,None,None,None,None,None,None,"2,702,860","2,702,860","2,702,860",...,"2,702,860","2,702,860","2,702,860","80,000","80,000","2,622,860","2,622,860","2,622,860","2,622,860","2,622,860"
47,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,"신고서 부표 등 작성 여부\n※ 해당란에 ""○"" 표시를 합니다.","신고서 부표 등 작성 여부\n※ 해당란에 ""○"" 표시를 합니다.","신고서 부표 등 작성 여부\n※ 해당란에 ""○"" 표시를 합니다.","신고서 부표 등 작성 여부\n※ 해당란에 ""○"" 표시를 합니다.","신고서 부표 등 작성 여부\n※ 해당란에 ""○"" 표시를 합니다.","신고서 부표 등 작성 여부\n※ 해당란에 ""○"" 표시를 합니다.","신고서 부표 등 작성 여부\n※ 해당란에 ""○"" 표시를 합니다.","신고서 부표 등 작성 여부\n※ 해당란에 ""○"" 표시를 합니다.","신고서 부표 등 작성 여부\n※ 해당란에 ""○"" 표시를 합니다.","신고서 부표 등 작성 여부\n※ 해당란에 ""○"" 표시를 합니다."
48,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,부표(4∼5쪽),부표(4∼5쪽),부표(4∼5쪽),부표(4∼5쪽),환급(7쪽∼9쪽),환급(7쪽∼9쪽),환급(7쪽∼9쪽),승계명세(10쪽),승계명세(10쪽),승계명세(10쪽)
49,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,None,None,None,None,○,○,○,None,None,None
50,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,세무대리인,세무대리인,세무대리인,세무대리인,세무대리인,세무대리인,세무대리인,세무대리인,세무대리인,세무대리인
51,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,성명,성명,성명,성명,성명,None,None,None,None,None
52,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,사업자등록번호,사업자등록번호,사업자등록번호,사업자등록번호,사업자등록번호,None,None,None,None,None
53,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,전화번호,전화번호,전화번호,전화번호,전화번호,None,None,None,None,None
54,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,국세환급금 계좌신고,국세환급금 계좌신고,국세환급금 계좌신고,국세환급금 계좌신고,국세환급금 계좌신고,국세환급금 계좌신고,국세환급금 계좌신고,국세환급금 계좌신고,국세환급금 계좌신고,국세환급금 계좌신고
55,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,예입처,예입처,예입처,예입처,예입처,국세은행,국세은행,국세은행,국세은행,국세은행
56,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,예금종류,예금종류,예금종류,예금종류,예금종류,일 반,일 반,일 반,일 반,일 반
57,"원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...","원천징수의무자는 ｢소득세법 시행령｣ 제185조제1항에 따라 위의 내용을 제출하며,\...",...,계좌번호,계좌번호,계좌번호,계좌번호,계좌번호,121-12-00001,121-12-00001,121-12-00001,121-12-00001,121-12-00001

Page 265 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원),사업자등록번호 123-81-***** ☑원천징수세액환급신청서 부표\n(단위 : 원)
1,소득의\n종류,귀속 연월,지급 연월,코드,인원,소득 지급액,① 결정세액,기납부 원천징수세액,기납부 원천징수세액,기납부 원천징수세액,③ 차감 세액,④ 분납 금액,⑤ 조정환급\n세액,⑥ 환급 신청액
2,소득의\n종류,귀속 연월,지급 연월,코드,인원,소득 지급액,① 결정세액,② 계,기납부세액\n[주(현)],기납부세액\n[종(전)],③ 차감 세액,④ 분납 금액,⑤ 조정환급\n세액,⑥ 환급 신청액
3,근로,202502,202502,A04,8,"323,231,250","10,994,140","14,895,170","12,356,850","2,538,320","-3,901,030",None,"1,278,170","2,622,860"
4,합계,None,None,None,8,"323,231,250","10,994,140","14,895,170","12,356,850","2,538,320","-3,901,030",None,"1,278,170","2,622,860"

Page 266 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원),사업자등록번호 123-81-***** 기납부세액 명세서 (단위 : 원)
1,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황,❶ 원천징수 신고 납부 현황
2,소득의\n구분,귀속연월,귀속연월,귀속연월,지급연월,지급연월,지급연월,코드,코드,코드,인원,인원,총지급액,총지급액,징수세액,징수세액,징수세액,징수세액,징수세액,징수세액
3,소득의\n구분,귀속연월,귀속연월,귀속연월,지급연월,지급연월,지급연월,코드,코드,코드,인원,인원,총지급액,총지급액,①소득세 등,①소득세 등,①소득세 등,②농어촌특별세,②농어촌특별세,가산세
4,None,None,None,None,None,None,None,별,별,별,지,지,참,참,조,조,조,None,None,None
5,합 계,None,None,None,None,None,None,None,None,None,88,88,"294,040,530","294,040,530","12,977,670","12,977,670","12,977,670",None,None,None
6,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황,❷ 지급명세서 기납부세액 현황
7,소득의\n구분,성명,주민등록\n번호,주민등록\n번호,주민등록\n번호,주(현)근무지,주(현)근무지,주(현)근무지,주(현)근무지,주(현)근무지,주(현)근무지,종(전)근무지 결정세액,종(전)근무지 결정세액,종(전)근무지 결정세액,종(전)근무지 결정세액,종(전)근무지 결정세액,종(전)근무지 결정세액,종(전)근무지 결정세액,계,계
8,소득의\n구분,성명,주민등록\n번호,주민등록\n번호,주민등록\n번호,③ 소득세 등,③ 소득세 등,③ 소득세 등,④ 농어촌특별세,④ 농어촌특별세,④ 농어촌특별세,종(전)\n근무지,사업자\n등록번호,소득세 등,소득세 등,소득세 등,농어촌\n특별세,농어촌\n특별세,소득세 등,농어촌\n특별세
9,None,None,None,None,None,None,None,None,별,별,별,지,참,조,조,조,None,None,None,None
10,합계,None,None,None,None,"12,356,850","12,356,850","12,356,850",None,None,None,None,None,"2,538,320","2,538,320","2,538,320",None,None,"14,895,170",None
11,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황,❸ 기납부세액 차이 조정 현황
12,소득세 등,소득세 등,소득세 등,소득세 등,소득세 등,소득세 등,소득세 등,소득세 등,소득세 등,농어촌특별세,농어촌특별세,농어촌특별세,농어촌특별세,농어촌특별세,농어촌특별세,농어촌특별세,농어촌특별세,사 유,사 유,사 유
13,①\n소득세 등 합계,①\n소득세 등 합계,①\n소득세 등 합계,③\n소득세 등 합계,③\n소득세 등 합계,③\n소득세 등 합계,차이금액\n(③ - ①),차이금액\n(③ - ①),차이금액\n(③ - ①),②\n농어촌특별세 합계,②\n농어촌특별세 합계,②\n농어촌특별세 합계,④\n농어촌특별세 합계,④\n농어촌특별세 합계,④\n농어촌특별세 합계,차이금액\n(④ - ②),차이금액\n(④ - ②),사 유,사 유,사 유
14,"12,977,670","12,977,670","12,977,670","12,356,850","12,356,850","12,356,850","- 620,820","- 620,820","- 620,820",-,-,-,-,-,-,-,-,중도퇴사,중도퇴사,중도퇴사

Page 267 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8
0,① 원천징수 신고 납부 현황,① 원천징수 신고 납부 현황,① 원천징수 신고 납부 현황,① 원천징수 신고 납부 현황,① 원천징수 신고 납부 현황,① 원천징수 신고 납부 현황,① 원천징수 신고 납부 현황,① 원천징수 신고 납부 현황,① 원천징수 신고 납부 현황
1,소득의 구분,귀속 연월,지급 연월,코드,인원,총지급액,징수세액,징수세액,징수세액
2,소득의 구분,귀속 연월,지급 연월,코드,인원,총지급액,① 소득세 등,② 농어촌특별세,가산세
3,근로소득,202401,202401,A01,6,"25,300,000","1,225,800",None,None
4,근로소득,202402,202402,A01,6,"24,600,600","1,136,240",None,None
5,근로소득,202403,202403,A01,6,"23,800,000","1,060,000",None,None
6,근로소득,202404,202404,A01,6,"21,389,000","968,720",None,None
7,근로소득,202405,202405,A01,8,"26,470,820","1,382,420",None,None
8,근로소득,202406,202406,A01,8,"21,210,890","1,195,750",None,None
9,근로소득,202407,202407,A01,8,"21,350,760","1,221,820",None,None
10,근로소득,202408,202408,A01,8,"23,850,850","890,790",None,None
11,근로소득,202409,202409,A01,8,"24,682,440","905,620",None,None
12,근로소득,202410,202410,A01,8,"29,720,650","1,110,890",None,None
13,근로소득,202411,202411,A01,8,"24,901,140","992,750",None,None
14,근로소득,202412,202412,A01,8,"26,763,380","886,870",None,None
15,합 계,None,None,None,88,"294,040,530","12,977,670",None,None

Page 267 - Table 1 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10
0,② 지급명세서 기납부세액 현황,② 지급명세서 기납부세액 현황,② 지급명세서 기납부세액 현황,② 지급명세서 기납부세액 현황,② 지급명세서 기납부세액 현황,② 지급명세서 기납부세액 현황,② 지급명세서 기납부세액 현황,② 지급명세서 기납부세액 현황,② 지급명세서 기납부세액 현황,② 지급명세서 기납부세액 현황,② 지급명세서 기납부세액 현황
1,소득의\n구분,성명,주민등록번호,주(현)근무지,주(현)근무지,종(전)근무지 결정세액,종(전)근무지 결정세액,종(전)근무지 결정세액,종(전)근무지 결정세액,계,계
2,소득의\n구분,성명,주민등록번호,③ 소득세\n등,④ 농어촌\n특별세,종(전)\n근무지,사업자\n등록번호,소득세\n등,농어촌\n특별세,소득세\n등,농어촌\n특별세
3,근로소득,김△△,000000-0000000,"855,980",None,None,None,None,None,"855,980",None
4,근로소득,최△△,000000-0000000,"2,500,370",None,None,None,None,None,"2,500,370",None
5,근로소득,박○○,000000-0000000,"676,980",None,㈜00물산,111-81-00010,"895,000",None,"1,571,980",None
6,근로소득,박△△,000000-0000000,"326,470",None,△△백화점,211-03-00007,"675,000",None,"1,001,470",None
7,근로소득,이○○,000000-0000000,"5,900,350",None,None,None,None,None,"5,900,350",None
8,근로소득,정△△,000000-0000000,"312,000",None,None,None,None,None,"312,000",None
9,근로소득,송○○,000000-0000000,"521,900",None,None,None,None,None,"521,900",None
10,근로소득,문○○,000000-0000000,"1,262,800",None,㈜00전자,312-81-00080,"968,320",None,"2,231,120",None
11,합계,None,None,"12,356,850",None,None,None,"2,538,320",None,"14,895,170",None

Page 268 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,...,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,② 귀속연월,② 귀속연월,2025년 2월,2025년 2월,2025년 2월
1,매월,매월,반기,반기,반기,수정,수정,연말,연말,소득처분,...,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n☑ 원천징수세액환급신청서,③ 지급연월,③ 지급연월,2025년 2월,2025년 2월,2025년 2월
2,1. 원천징수 내역 및 납부세액,1. 원천징수 내역 및 납부세액,1. 원천징수 내역 및 납부세액,1. 원천징수 내역 및 납부세액,1. 원천징수 내역 및 납부세액,1. 원천징수 내역 및 납부세액,1. 원천징수 내역 및 납부세액,1. 원천징수 내역 및 납부세액,1. 원천징수 내역 및 납부세액,1. 원천징수 내역 및 납부세액,...,(단위：원),(단위：원),(단위：원),(단위：원),(단위：원),(단위：원),(단위：원),(단위：원),(단위：원),(단위：원)
3,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,코드,코드,...,원천징수내역,원천징수내역,원천징수내역,원천징수내역,⑨ 당월 조정 환급세액,⑨ 당월 조정 환급세액,납부 세액,납부 세액,납부 세액,납부 세액
4,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,코드,코드,...,징수세액,징수세액,징수세액,징수세액,⑨ 당월 조정 환급세액,⑨ 당월 조정 환급세액,⑩ 소득세 등\n(가산세 포함),⑩ 소득세 등\n(가산세 포함),⑩ 소득세 등\n(가산세 포함),⑪ 농어촌\n특별세
5,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,소득자\n소득구분,코드,코드,...,⑦ 농어촌 특별세,⑦ 농어촌 특별세,⑧ 가산세,⑧ 가산세,⑨ 당월 조정 환급세액,⑨ 당월 조정 환급세액,⑩ 소득세 등\n(가산세 포함),⑩ 소득세 등\n(가산세 포함),⑩ 소득세 등\n(가산세 포함),⑪ 농어촌\n특별세
6,근 로 소 득,간이세액,간이세액,간이세액,간이세액,간이세액,간이세액,간이세액,A01,A01,...,None,None,None,None,None,None,None,None,None,None
7,근 로 소 득,연말 정산,연말 정산,연말 정산,합계,합계,합계,합계,A04,A04,...,None,None,None,None,None,None,None,None,None,None
8,근 로 소 득,연말 정산,연말 정산,연말 정산,분납신청,분납신청,분납신청,분납신청,A05,A05,...,None,None,None,None,None,None,None,None,None,None
9,근 로 소 득,연말 정산,연말 정산,연말 정산,납부금액,납부금액,납부금액,납부금액,A06,A06,...,None,None,"0\n18,600","0\n18,600",None,None,None,None,None,None
10,근 로 소 득,가감계,가감계,가감계,가감계,가감계,가감계,가감계,A10,A10,...,None,None,"0\n18,600","0\n18,600","0\n-200,000","0\n-200,000","0\n218,600","0\n218,600","0\n218,600",None
11,기타 소득,가감계,가감계,가감계,가감계,가감계,가감계,가감계,A40,A40,...,None,None,None,None,"80,000\n80,000","80,000\n80,000",None,None,None,None
12,수정신고(세액),수정신고(세액),수정신고(세액),수정신고(세액),수정신고(세액),수정신고(세액),수정신고(세액),수정신고(세액),A90,A90,...,None,None,None,None,None,None,None,None,None,None
13,총합계,총합계,총합계,총합계,총합계,총합계,총합계,총합계,A99,A99,...,None,None,"0\n18,600","0\n18,600","80,000\n-120,000","80,000\n-120,000","0\n218,600","0\n218,600","0\n218,600",None
14,❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),...,❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원),❷ 환급세액 조정\n(단위：원)
15,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,전월 미환급 세액의 계산,당월 발생 환급세액,...,당월 발생 환급세액,￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 당월조정\n환급세액계,￾￾ 당월조정\n환급세액계,￾￾ 당월조정\n환급세액계,￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 환급 신청액,￾￾ 환급 신청액
16,⑫전월\n미환급\n세액,⑫전월\n미환급\n세액,⑫전월\n미환급\n세액,⑬ 기환급\n신청세액,⑬ 기환급\n신청세액,⑬ 기환급\n신청세액,⑭ 차감잔액\n(⑫-⑬),⑭ 차감잔액\n(⑫-⑬),⑭ 차감잔액\n(⑫-⑬),⑮ 일반 환급,...,￾￾ 그밖의 환급세액,￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 당월조정\n환급세액계,￾￾ 당월조정\n환급세액계,￾￾ 당월조정\n환급세액계,￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 환급 신청액,￾￾ 환급 신청액
17,⑫전월\n미환급\n세액,⑫전월\n미환급\n세액,⑫전월\n미환급\n세액,⑬ 기환급\n신청세액,⑬ 기환급\n신청세액,⑬ 기환급\n신청세액,⑭ 차감잔액\n(⑫-⑬),⑭ 차감잔액\n(⑫-⑬),⑭ 차감잔액\n(⑫-⑬),⑮ 일반 환급,...,합병 등,￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 조정대상\n환급세액\n(⑭+￾￾+￾￾+￾￾),￾￾ 당월조정\n환급세액계,￾￾ 당월조정\n환급세액계,￾￾ 당월조정\n환급세액계,￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 차월이월\n환급세액\n(￾￾-￾￾),￾￾ 환급 신청액,￾￾ 환급 신청액
18,None,None,None,None,None,None,None,None,None,"2,702,860\n2,502,860",...,None,"2,702,860\n2,502,860","2,702,860\n2,502,860","80,000\n-120,000","80,000\n-120,000","80,000\n-120,000","2,622,860\n2,622,860","2,622,860\n2,622,860","2,622,860\n2,622,860","2,622,860\n2,622,860"

Page 268 - Table 1 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,① 신고구분,☑ 원천징수이행상황신고서\n□ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n□ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n□ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n□ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n□ 원천징수세액환급신청서,② 귀속연월,② 귀속연월,2025년 9월,2025년 9월
1,매월,반기,수정,수정,연말,연말,소득처분,환급신청,☑ 원천징수이행상황신고서\n□ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n□ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n□ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n□ 원천징수세액환급신청서,☑ 원천징수이행상황신고서\n□ 원천징수세액환급신청서,③ 지급연월,③ 지급연월,2025년 9월,2025년 9월
2,1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원),1. 원천징수 내역 및 납부세액 (단위：원)
3,소득자\n코드\n소득구분,소득자\n코드\n소득구분,소득자\n코드\n소득구분,코드,코드,원천징수내역,원천징수내역,원천징수내역,원천징수내역,원천징수내역,원천징수내역,원천징수내역,⑨ 당월 조정\n환급세액,⑨ 당월 조정\n환급세액,납부 세액,납부 세액,납부 세액
4,소득자\n코드\n소득구분,소득자\n코드\n소득구분,소득자\n코드\n소득구분,코드,코드,"소득지급(과세 미달, 비과세 포함)","소득지급(과세 미달, 비과세 포함)","소득지급(과세 미달, 비과세 포함)","소득지급(과세 미달, 비과세 포함)",징수세액,징수세액,징수세액,⑨ 당월 조정\n환급세액,⑨ 당월 조정\n환급세액,⑩ 소득세 등\n(가산세 포함),⑩ 소득세 등\n(가산세 포함),⑪ 농어촌\n특별세
5,소득자\n코드\n소득구분,소득자\n코드\n소득구분,소득자\n코드\n소득구분,코드,코드,④ 인원,④ 인원,⑤ 총지급액,⑤ 총지급액,⑥ 소득세 등,⑦ 농어촌 특별세,⑧ 가산세,⑨ 당월 조정\n환급세액,⑨ 당월 조정\n환급세액,⑩ 소득세 등\n(가산세 포함),⑩ 소득세 등\n(가산세 포함),⑪ 농어촌\n특별세
6,근 로 소 득,간이세액 A01,간이세액 A01,A01,A01,8,8,"22,230,000","22,230,000","1,198,170",None,None,None,None,None,None,None
7,근 로 소 득,가감계 A10,가감계 A10,A10,A10,8,8,"22,230,000","22,230,000","1,198,170",None,None,None,None,"1,198,170","1,198,170",None
8,수정신고(세액) A90,수정신고(세액) A90,수정신고(세액) A90,A90,A90,None,None,None,None,"200,000",None,"18,600",None,None,"218,600","218,600",None
9,총합계 A99,총합계 A99,총합계 A99,A99,A99,2,2,"6,000,000","6,000,000","1,398,170",None,"18,600",None,None,"1,416,770","1,416,770",None

Page 290 - Table 0 DataFrame:

       0                                                  1                 2
0   None                                            원천징수의무자              None
1  관할세무서                                        원천징수 관할 세무서  주소지 관할 세무서(소득세과)
2   None  ∙ 과세표준 및 세액의 결정(경정)청구서\n∙ 수정 원천징수이행상황신고서\n∙ 근로...              None

Page 291 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9
0,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,처리기간
1,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,과세표준 및 세액의 결정(경정)청구서,2 월
2,청 구 인,① 성명,① 성명,이강모,② 주민등록번호,② 주민등록번호,② 주민등록번호,③ 사업자등록번호,③ 사업자등록번호,③ 사업자등록번호
3,청 구 인,① 성명,① 성명,이강모,800101-1******,800101-1******,800101-1******,None,None,None
4,청 구 인,④ 주소(거소) 또는 영업소,④ 주소(거소) 또는 영업소,서울특별시 종로구 종로3길 1번길,서울특별시 종로구 종로3길 1번길,서울특별시 종로구 종로3길 1번길,서울특별시 종로구 종로3길 1번길,⑤ 전화번호,⑤ 전화번호,⑤ 전화번호
5,청 구 인,⑥ 상호,⑥ 상호,None,None,None,None,None,None,None
6,신 고 내 용,신 고 내 용,신 고 내 용,신 고 내 용,신 고 내 용,신 고 내 용,신 고 내 용,신 고 내 용,신 고 내 용,신 고 내 용
7,⑦ 법정신고일,⑦ 법정신고일,⑦ 법정신고일,2025.03.10. ⑧ 최초신고일 2025.03.10.,2025.03.10. ⑧ 최초신고일 2025.03.10.,2025.03.10. ⑧ 최초신고일 2025.03.10.,2025.03.10. ⑧ 최초신고일 2025.03.10.,2025.03.10. ⑧ 최초신고일 2025.03.10.,2025.03.10. ⑧ 최초신고일 2025.03.10.,2025.03.10. ⑧ 최초신고일 2025.03.10.
8,⑨ 경정(결정)청구이유,⑨ 경정(결정)청구이유,⑨ 경정(결정)청구이유,근로소득 연말정산 시 일반기부금 세액공제 누락,근로소득 연말정산 시 일반기부금 세액공제 누락,근로소득 연말정산 시 일반기부금 세액공제 누락,근로소득 연말정산 시 일반기부금 세액공제 누락,근로소득 연말정산 시 일반기부금 세액공제 누락,근로소득 연말정산 시 일반기부금 세액공제 누락,근로소득 연말정산 시 일반기부금 세액공제 누락
9,구분,구분,구분,최초신고\n경정(결정)청구\n회사에서 발급받은\n누락된 항목을 넣어 재계산한\n원천...,최초신고\n경정(결정)청구\n회사에서 발급받은\n누락된 항목을 넣어 재계산한\n원천...,최초신고\n경정(결정)청구\n회사에서 발급받은\n누락된 항목을 넣어 재계산한\n원천...,최초신고\n경정(결정)청구\n회사에서 발급받은\n누락된 항목을 넣어 재계산한\n원천...,최초신고\n경정(결정)청구\n회사에서 발급받은\n누락된 항목을 넣어 재계산한\n원천...,최초신고\n경정(결정)청구\n회사에서 발급받은\n누락된 항목을 넣어 재계산한\n원천...,최초신고\n경정(결정)청구\n회사에서 발급받은\n누락된 항목을 넣어 재계산한\n원천...
10,⑩ 세목,⑩ 세목,⑩ 세목,근로소득,근로소득,최초신고\n경정(결정)청구\n회사에서 발급받은\n누락된 항목을 넣어 재계산한\n원천...,최초신고\n경정(결정)청구\n회사에서 발급받은\n누락된 항목을 넣어 재계산한\n원천...,최초신고\n경정(결정)청구\n회사에서 발급받은\n누락된 항목을 넣어 재계산한\n원천...,근로소득,근로소득
11,⑪ 과세표준금액,⑪ 과세표준금액,⑪ 과세표준금액,"37,010,000","37,010,000","37,010,000","37,010,000","37,010,000","37,010,000","37,010,000"
12,⑫ 산출세액,⑫ 산출세액,⑫ 산출세액,"4,291,500","4,291,500","4,291,500","4,291,500","4,291,500","4,291,500","4,291,500"
13,⑬ 가산세액,⑬ 가산세액,⑬ 가산세액,None,None,None,None,None,None,None
14,⑭ 공제 및 감면세액,⑭ 공제 및 감면세액,⑭ 공제 및 감면세액,"3,842,518","3,842,518","3,842,518","3,992,518","3,992,518","3,992,518","3,992,518"
15,⑮ 납부할 세액,⑮ 납부할 세액,⑮ 납부할 세액,"448,982","448,982","448,982","298,982","298,982","298,982","298,982"
16,⑯ 국세환급금 계좌신고,⑯ 국세환급금 계좌신고,⑯ 국세환급금 계좌신고,거래은행 국세은행,거래은행 국세은행,거래은행 국세은행,계좌번호 100-200-30000,계좌번호 100-200-30000,계좌번호 100-200-30000,계좌번호 100-200-30000
17,⑰ 환급받을 세액,⑰ 환급받을 세액,⑰ 환급받을 세액,None,None,None,"150,000","150,000","150,000","150,000"
18,"｢국세기본법｣ 제45조의2 및 같은 법 시행령 제25조의3, ｢소득세법｣ 제118조...","｢국세기본법｣ 제45조의2 및 같은 법 시행령 제25조의3, ｢소득세법｣ 제118조...","｢국세기본법｣ 제45조의2 및 같은 법 시행령 제25조의3, ｢소득세법｣ 제118조...","｢국세기본법｣ 제45조의2 및 같은 법 시행령 제25조의3, ｢소득세법｣ 제118조...","｢국세기본법｣ 제45조의2 및 같은 법 시행령 제25조의3, ｢소득세법｣ 제118조...","｢국세기본법｣ 제45조의2 및 같은 법 시행령 제25조의3, ｢소득세법｣ 제118조...","｢국세기본법｣ 제45조의2 및 같은 법 시행령 제25조의3, ｢소득세법｣ 제118조...","｢국세기본법｣ 제45조의2 및 같은 법 시행령 제25조의3, ｢소득세법｣ 제118조...","｢국세기본법｣ 제45조의2 및 같은 법 시행령 제25조의3, ｢소득세법｣ 제118조...","｢국세기본법｣ 제45조의2 및 같은 법 시행령 제25조의3, ｢소득세법｣ 제118조..."
19,첨부서류,첨부서류,결정(경정)청구 사유 증명자료,결정(경정)청구 사유 증명자료,결정(경정)청구 사유 증명자료,결정(경정)청구 사유 증명자료,결정(경정)청구 사유 증명자료,결정(경정)청구 사유 증명자료,결정(경정)청구 사유 증명자료,수수료\n없 음

Page 291 - Table 1 DataFrame:

,0,1,2,3,4,5
0,위임자\n(신청인),대리인,대리인,대리인,대리인,대리인
1,위임자\n(신청인),구분,성명,사업장\n소재지,사업자등록번호\n(전자우편),전화번호\n(휴대전화번호)
2,(서명 또는 인),[ ]세 무 사\n[ ]공인회계사\n[ ]변 호 사,(서명 또는 인),(￾ ),None,None

Page 291 - Table 2 DataFrame:

,0,1,2
0,접수증(과세표준 및 세액의 결정(경정)청구서),접수증(과세표준 및 세액의 결정(경정)청구서),접수증(과세표준 및 세액의 결정(경정)청구서)
1,성명,주소,주소
2,첨부서류,결정(경정)청구사유 증명자료 [ ],접 수 자
3,첨부서류,결정(경정)청구사유 증명자료 [ ],접수일인

Page 292 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...
1,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주지국,거주지국,거주지국,거주지국코드,거주지국코드,거주지국코드,거주지국코드
2,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,내·외국인,내·외국인,내·외국인,내국인1 /외국인9,내국인1 /외국인9,내국인1 /외국인9,내국인1 /외국인9
3,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,외국인단일세율적용,외국인단일세율적용,외국인단일세율적용,외국인단일세율적용,외국인단일세율적용,외국인단일세율적용,여 1 / 부 2
4,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,여 1 / 부 2
5,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,종교관련종사자 여부,종교관련종사자 여부,종교관련종사자 여부,종교관련종사자 여부,종교관련종사자 여부,종교관련종사자 여부,여 1 / 부 2
6,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,국적,국적,국적,국적코드,국적코드,국적코드,국적코드
7,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,세대주 여부,세대주 여부,세대주 여부,"세대주1, 세대원2","세대주1, 세대원2","세대주1, 세대원2","세대주1, 세대원2"
8,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,거주구분 거주자1/비거주자2\n거주지국 거주지국코드\n내·외국인 내국인1 /외국인9...,연말정산 구분,연말정산 구분,연말정산 구분,"계속근로1, 중도퇴사2","계속근로1, 중도퇴사2","계속근로1, 중도퇴사2","계속근로1, 중도퇴사2"
9,징수 의무자,① 법인명(상호) 한강건설(주),① 법인명(상호) 한강건설(주),① 법인명(상호) 한강건설(주),① 법인명(상호) 한강건설(주),① 법인명(상호) 한강건설(주),① 법인명(상호) 한강건설(주),② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0,② 대표자(성명) 김 0 0
10,징수 의무자,③ 사업자등록번호 123-81-*****,③ 사업자등록번호 123-81-*****,③ 사업자등록번호 123-81-*****,③ 사업자등록번호 123-81-*****,③ 사업자등록번호 123-81-*****,③ 사업자등록번호 123-81-*****,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******,④ 주민등록번호 400101-1******
11,징수 의무자,③-1 사업자단위과세자 여부\n여1 / 부2,③-1 사업자단위과세자 여부\n여1 / 부2,③-1 사업자단위과세자 여부\n여1 / 부2,③-1 사업자단위과세자 여부\n여1 / 부2,③-1 사업자단위과세자 여부\n여1 / 부2,③-1 사업자단위과세자 여부\n여1 / 부2,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호,③-2 종사업장 일련번호
12,징수 의무자,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000,⑤ 소재지(주소) 서울특별시 종로구 종로5길 1000
13,소득자,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******,⑥ 성명\n이 강 모\n⑦ 주민등록번호(외국인등록번호) 800101-1******
14,소득자,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길,⑧ 주소\n서울특별시 종로구 종로3길 1번길
15,Ⅰ 근 무 처 별 소 득 명 세,구분,구분,구분,구분,주(현),종(전),종(전),종(전),종(전),종(전),￾￾-1 납세조합,￾￾-1 납세조합,￾￾-1 납세조합,합 계,합 계
16,Ⅰ 근 무 처 별 소 득 명 세,⑨ 근무처명,⑨ 근무처명,⑨ 근무처명,⑨ 근무처명,한강건설(주),None,None,None,None,None,None,None,None,None,None
17,Ⅰ 근 무 처 별 소 득 명 세,⑩ 사업자등록번호,⑩ 사업자등록번호,⑩ 사업자등록번호,⑩ 사업자등록번호,123-81-*****,None,None,None,None,None,None,None,None,None,None
18,Ⅰ 근 무 처 별 소 득 명 세,⑪ 근무기간,⑪ 근무기간,⑪ 근무기간,⑪ 근무기간,24.1.1.~24.12.31.,~,~,~,~,~,~,~,~,24.1.1.~24.12.31.,24.1.1.~24.12.31.
19,Ⅰ 근 무 처 별 소 득 명 세,⑫ 감면기간,⑫ 감면기간,⑫ 감면기간,⑫ 감면기간,~,~,~,~,~,~,~,~,~,~,~
20,Ⅰ 근 무 처 별 소 득 명 세,⑬ 급여,⑬ 급여,⑬ 급여,⑬ 급여,"39,000,000",None,None,None,None,None,None,None,None,"39,000,000","39,000,000"
21,Ⅰ 근 무 처 별 소 득 명 세,⑬ 급여,⑬ 급여,⑬ 급여,⑬ 급여,"39,000,000",None,None,None,None,None,None,None,None,"39,000,000","39,000,000"
22,Ⅰ 근 무 처 별 소 득 명 세,⑭ 상여,⑭ 상여,⑭ 상여,⑭ 상여,"26,400,000",None,None,None,None,None,None,None,None,"26,400,000","26,400,000"
23,Ⅰ 근 무 처 별 소 득 명 세,⑭ 상여,⑭ 상여,⑭ 상여,⑭ 상여,"26,400,000",None,None,None,None,None,None,None,None,"26,400,000","26,400,000"
24,Ⅰ 근 무 처 별 소 득 명 세,⑮ 인정상여,⑮ 인정상여,⑮ 인정상여,⑮ 인정상여,None,None,None,None,None,None,None,None,None,None,None
25,Ⅰ 근 무 처 별 소 득 명 세,⑮-1 주식매수선택권 행사이익,⑮-1 주식매수선택권 행사이익,⑮-1 주식매수선택권 행사이익,⑮-1 주식매수선택권 행사이익,None,None,None,None,None,None,None,None,None,None,None
26,Ⅰ 근 무 처 별 소 득 명 세,⑮-2 우리사주조합인출금,⑮-2 우리사주조합인출금,⑮-2 우리사주조합인출금,⑮-2 우리사주조합인출금,None,None,None,None,None,None,None,None,None,None,None
27,Ⅰ 근 무 처 별 소 득 명 세,⑮-3 임원 퇴직소득금액 한도초과액,⑮-3 임원 퇴직소득금액 한도초과액,⑮-3 임원 퇴직소득금액 한도초과액,⑮-3 임원 퇴직소득금액 한도초과액,None,None,None,None,None,None,None,None,None,None,None
28,Ⅰ 근 무 처 별 소 득 명 세,⑮-4 직무발명보상금,⑮-4 직무발명보상금,⑮-4 직무발명보상금,⑮-4 직무발명보상금,None,None,None,None,None,None,None,None,None,None,None
29,Ⅰ 근 무 처 별 소 득 명 세,￾￾ 계,￾￾ 계,￾￾ 계,￾￾ 계,"65,400,000",None,None,None,None,None,None,None,None,"65,400,000","65,400,000"
30,Ⅰ 근 무 처 별 소 득 명 세,￾￾ 계,￾￾ 계,￾￾ 계,￾￾ 계,"65,400,000",None,None,None,None,None,None,None,None,"65,400,000","65,400,000"
31,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾ 국외근로,￾￾ 국외근로,M0X,M0X,None,None,None,None,None,None,None,None,None,None,None
32,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-1 야간근로수당,￾￾-1 야간근로수당,O0X,O0X,None,None,None,None,None,None,None,None,None,None,None
33,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-2 보육수당,￾￾-2 보육수당,Q0X,Q0X,"2,400,000",None,None,None,None,None,None,None,None,"2,400,000","2,400,000"
34,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-2 보육수당,￾￾-2 보육수당,Q0X,Q0X,"2,400,000",None,None,None,None,None,None,None,None,"2,400,000","2,400,000"
35,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-3 출산지원금,￾￾-3 출산지원금,Q0X,Q0X,"5,000,000",None,None,None,None,None,None,None,None,"5,000,000","5,000,000"
36,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-3 출산지원금,￾￾-3 출산지원금,Q0X,Q0X,"5,000,000",None,None,None,None,None,None,None,None,"5,000,000","5,000,000"
37,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-4 연구보조비,￾￾-4 연구보조비,H0X,H0X,None,None,None,None,None,None,None,None,None,None,None
38,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-5 비과세학자금,￾￾-5 비과세학자금,GO1,GO1,"3,000,000",None,None,None,None,None,None,None,None,"3,000,000","3,000,000"
39,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-5 비과세학자금,￾￾-5 비과세학자금,GO1,GO1,"3,000,000",None,None,None,None,None,None,None,None,"3,000,000","3,000,000"
40,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-6,￾￾-6,None,None,None,None,None,None,None,None,None,None,None,None,None
41,Ⅱ 비 과 세 및 감 면 소 득 명 세,~,~,None,None,None,None,None,None,None,None,None,None,None,None,None
42,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-40 비과세식대,￾￾-40 비과세식대,P01,P01,"2,400,000",None,None,None,None,None,None,None,None,"2,400,000","2,400,000"
43,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-40 비과세식대,￾￾-40 비과세식대,P01,P01,"2,400,000",None,None,None,None,None,None,None,None,"2,400,000","2,400,000"
44,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾ 수련보조수당,￾￾ 수련보조수당,Y22,Y22,None,None,None,None,None,None,None,None,None,None,None
45,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾ 비과세소득 계,￾￾ 비과세소득 계,￾￾ 비과세소득 계,￾￾ 비과세소득 계,"12,800,000",None,None,None,None,None,None,None,None,"12,800,000","12,800,000"
46,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾ 비과세소득 계,￾￾ 비과세소득 계,￾￾ 비과세소득 계,￾￾ 비과세소득 계,"12,800,000",None,None,None,None,None,None,None,None,"12,800,000","12,800,000"
47,Ⅱ 비 과 세 및 감 면 소 득 명 세,￾￾-1 감면소득 계,￾￾-1 감면소득 계,￾￾-1 감면소득 계,￾￾-1 감면소득 계,None,None,None,None,None,None,None,None,None,None,None
48,Ⅲ 세 액 명 세,구분,구분,구분,구분,구분,￾￾ 소득세,￾￾ 소득세,None,None,￾￾ 지방소득세,￾￾ 지방소득세,￾￾ 지방소득세,￾￾ 농어촌특별세,￾￾ 농어촌특별세,￾￾ 농어촌특별세
49,Ⅲ 세 액 명 세,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n(결정세액란의\n기\n등록번호,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n(결정세액란의\n기\n등록번호,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n(결정세액란의\n기\n등록번호,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n(결정세액란의\n기\n등록번호,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n(결정세액란의\n기\n등록번호,"448,982","448,982","448,982","448,982","44,898","44,898","44,898",None,None,None
50,Ⅲ 세 액 명 세,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n(결정세액란의\n기\n등록번호,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n(결정세액란의\n기\n등록번호,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n(결정세액란의\n기\n등록번호,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n(결정세액란의\n기\n등록번호,￾￾ 결정세액\n￾￾ 종(전)근무지\n사업자\n(결정세액란의\n기\n등록번호,"298,982","298,982","298,982","298,982","29,898","29,898","29,898",None,None,None
51,Ⅲ 세 액 명 세,기 납부 세액,￾￾ 주(현)근무지,￾￾ 주(현)근무지,￾￾ 주(현)근무지,￾￾ 주(현)근무지,"1,000,000","1,000,000","1,000,000","1,000,000","100,000","100,000","100,000",None,None,None
52,Ⅲ 세 액 명 세,기 납부 세액,￾￾ 주(현)근무지,￾￾ 주(현)근무지,￾￾ 주(현)근무지,￾￾ 주(현)근무지,"1,000,000","1,000,000","1,000,000","1,000,000","100,000","100,000","100,000",None,None,None
53,Ⅲ 세 액 명 세,￾￾ 납부특례세액,￾￾ 납부특례세액,￾￾ 납부특례세액,￾￾ 납부특례세액,￾￾ 납부특례세액,None,None,None,None,None,None,None,None,None,None
54,Ⅲ 세 액 명 세,￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),"-551,018","-551,018","-551,018","-551,018","-55,102","-55,102","-55,102",None,None,None
55,Ⅲ 세 액 명 세,￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),"-701,018","-701,018","-701,018","-701,018","-70,102","-70,102","-70,102",None,None,None
56,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...,위의 원천징수액(근로소득)을 정히 영수(지급)합니다.\n년\n월\n일\n징수(보고)...

Page 293 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11
0,세 액 감 면\n세,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,None
1,세 액 감 면\n세,￾￾\n￾￾,￾￾\n￾￾,제외)\n｢조세특례제한법｣ 제30조,제외)\n｢조세특례제한법｣ 제30조,제외)\n｢조세특례제한법｣ 제30조,제외)\n｢조세특례제한법｣ 제30조,제외)\n｢조세특례제한법｣ 제30조,제외)\n｢조세특례제한법｣ 제30조,제외)\n｢조세특례제한법｣ 제30조,제외)\n｢조세특례제한법｣ 제30조,None
2,세 액 감 면\n세,￾￾ 조세조약,￾￾ 조세조약,None,None,None,None,None,None,None,None,None
3,세 액 감 면\n세,￾￾ 세액감면\n￾￾ 근로소득\n￾￾\n￾￾ 자녀\n연 금 계 좌,￾￾ 세액감면\n￾￾ 근로소득\n￾￾\n￾￾ 자녀\n연 금 계 좌,계\n결혼세액공제\n공제대상자녀 ( 1 명)\n출산·입양자 ( 1 명)\n｢과학기술...,계\n결혼세액공제\n공제대상자녀 ( 1 명)\n출산·입양자 ( 1 명)\n｢과학기술...,계\n결혼세액공제\n공제대상자녀 ( 1 명)\n출산·입양자 ( 1 명)\n｢과학기술...,계\n결혼세액공제\n공제대상자녀 ( 1 명)\n출산·입양자 ( 1 명)\n｢과학기술...,계\n결혼세액공제\n공제대상자녀 ( 1 명)\n출산·입양자 ( 1 명)\n｢과학기술...,계\n결혼세액공제\n공제대상자녀 ( 1 명)\n출산·입양자 ( 1 명)\n｢과학기술...,계\n결혼세액공제\n공제대상자녀 ( 1 명)\n출산·입양자 ( 1 명)\n｢과학기술...,계\n결혼세액공제\n공제대상자녀 ( 1 명)\n출산·입양자 ( 1 명)\n｢과학기술...,"660,000\n660,000\n150,000\n150,000\n700,000\n7..."
4,세 액 공 제,￾￾ 결혼세액공제\n공제대상자녀 ( 1 명)\n￾￾ 자녀\n출산·입양자 ( 1 명)...,￾￾ 결혼세액공제\n공제대상자녀 ( 1 명)\n￾￾ 자녀\n출산·입양자 ( 1 명)...,￾￾ 결혼세액공제\n공제대상자녀 ( 1 명)\n￾￾ 자녀\n출산·입양자 ( 1 명)...,￾￾ 결혼세액공제\n공제대상자녀 ( 1 명)\n￾￾ 자녀\n출산·입양자 ( 1 명)...,￾￾ 결혼세액공제\n공제대상자녀 ( 1 명)\n￾￾ 자녀\n출산·입양자 ( 1 명)...,￾￾ 결혼세액공제\n공제대상자녀 ( 1 명)\n￾￾ 자녀\n출산·입양자 ( 1 명)...,￾￾ 결혼세액공제\n공제대상자녀 ( 1 명)\n￾￾ 자녀\n출산·입양자 ( 1 명)...,￾￾ 결혼세액공제\n공제대상자녀 ( 1 명)\n￾￾ 자녀\n출산·입양자 ( 1 명)...,￾￾ 결혼세액공제\n공제대상자녀 ( 1 명)\n￾￾ 자녀\n출산·입양자 ( 1 명)...,￾￾ 결혼세액공제\n공제대상자녀 ( 1 명)\n￾￾ 자녀\n출산·입양자 ( 1 명)...,"150,000\n150,000\n700,000\n700,000\n1,000,000\..."
5,세 액 공 제,￾￾ 자녀,￾￾ 자녀,￾￾ 자녀,￾￾ 자녀,출산·입양자 ( 1 명),출산·입양자 ( 1 명),출산·입양자 ( 1 명),출산·입양자 ( 1 명),출산·입양자 ( 1 명),출산·입양자 ( 1 명),"700,000\n700,000"
6,세 액 공 제,연 금 계 좌,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,None,None,None,"1,000,000\n1,000,000\n120,000\n120,000\n2,000,..."
7,세 액 공 제,연 금 계 좌,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,￾￾ ｢과학기술인공제회법｣에 따른\n퇴직연금\n￾￾ ｢근로자퇴직급여 보장법｣에\n따...,None,None,세액공제액\n공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공제대상금액\n세...,"1,000,000\n1,000,000\n120,000\n120,000\n2,000,..."
8,세 액 공 제,연 금 계 좌,￾￾ 연금저축,￾￾ 연금저축,￾￾ 연금저축,￾￾ 연금저축,￾￾ 연금저축,￾￾ 연금저축,세액공제액,세액공제액,세액공제액,"2,000,000\n2,000,000\n240,000"
9,세 액 공 제,연 금 계 좌,￾￾-1 개인종합자산관리계좌 만기 시\n연금계좌 납입액,￾￾-1 개인종합자산관리계좌 만기 시\n연금계좌 납입액,￾￾-1 개인종합자산관리계좌 만기 시\n연금계좌 납입액,￾￾-1 개인종합자산관리계좌 만기 시\n연금계좌 납입액,￾￾-1 개인종합자산관리계좌 만기 시\n연금계좌 납입액,￾￾-1 개인종합자산관리계좌 만기 시\n연금계좌 납입액,None,None,공제대상금액,"240,000"
10,세 액 공 제,특 별 세 액 공 제,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,보장성\n장애인전용보장성,보장성\n장애인전용보장성,공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공...,공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공...,공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공...,"1,000,000\n1,000,000\n120,000\n120,000\n5,338,..."
11,세 액 공 제,특 별 세 액 공 제,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,장애인전용보장성,장애인전용보장성,None,None,공제대상금액,"5,338,000\n5,338,000\n950,700\n950,700\n4,200,..."
12,세 액 공 제,특 별 세 액 공 제,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,￾￾ 보험료\n￾￾ 의료비\n￾￾ 교육비,장애인전용보장성,장애인전용보장성,None,None,세액공제액\n공제대상금액\n세액공제액\n공제대상금액\n세액공제액,"5,338,000\n5,338,000\n950,700\n950,700\n4,200,..."
13,세 액 공 제,특 별 세 액 공 제,￾￾ 의료비,￾￾ 의료비,￾￾ 의료비,￾￾ 의료비,￾￾ 의료비,￾￾ 의료비,세액공제액,세액공제액,세액공제액,"5,338,000\n5,338,000\n950,700\n950,700"
14,세 액 공 제,특 별 세 액 공 제,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,공제대상금액,공제대상금액,공제대상금액,"4,200,000\n4,200,000\n630,000\n630,000"
15,세 액 공 제,특 별 세 액 공 제,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,세액공제액,세액공제액,세액공제액,"4,200,000\n4,200,000\n630,000\n630,000"
16,세 액 공 제,특 별 세 액 공 제,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,￾￾ 교육비,세액공제액,세액공제액,세액공제액,"4,200,000\n4,200,000\n630,000\n630,000"
17,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,10만원 이하,공제대상금액,공제대상금액,공제대상금액,"100,000\n100,000\n90,909\n90,909"
18,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,10만원 이하,공제대상금액,공제대상금액,공제대상금액,"100,000\n100,000\n90,909\n90,909"
19,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,10만원 이하,세액공제액,세액공제액,세액공제액,"100,000\n100,000\n90,909\n90,909"
20,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,10만원 이하,세액공제액,세액공제액,세액공제액,"100,000\n100,000\n90,909\n90,909"
21,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,10만원 이하\n10만원 초과,공제대상금액,공제대상금액,공제대상금액,"100,000\n100,000\n90,909\n90,909\n100,000\n100..."
22,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,㉮ 정치 자금 기부금,10만원 이하\n10만원 초과,공제대상금액\n세액공제액\n공제대상금액\n세액공제액,공제대상금액\n세액공제액\n공제대상금액\n세액공제액,공제대상금액\n세액공제액\n공제대상금액\n세액공제액,"100,000\n100,000\n90,909\n90,909\n100,000\n100..."
23,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,10만원 이하,공제대상금액,공제대상금액,공제대상금액,"100,000\n100,000\n90,909\n90,909"
24,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,10만원 이하,세액공제액,세액공제액,세액공제액,"100,000\n100,000\n90,909\n90,909"
25,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,10만원 이하\n10만원 초과\n10만원 이하\n10만원 초과,공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공...,공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공...,공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공제대상금액\n세액공제액\n공...,"100,000\n100,000\n90,909\n90,909\n100,000\n100..."
26,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,10만원 이하\n10만원 초과\n10만원 이하\n10만원 초과,세액공제액,세액공제액,세액공제액,"100,000\n100,000\n90,909\n90,909\n100,000\n100..."
27,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,㉮ 정치 자금 기부금\n㉯ 고향 사랑 기부금,10만원 이하\n10만원 초과\n10만원 이하\n10만원 초과,세액공제액,세액공제액,세액공제액,"100,000\n100,000\n90,909\n90,909\n100,000\n100..."
28,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉰ 특례기부금,㉰ 특례기부금,㉰ 특례기부금,㉰ 특례기부금,공제대상금액,공제대상금액,공제대상금액,"500,000\n500,000\n75,000\n75,000"
29,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉰ 특례기부금,㉰ 특례기부금,㉰ 특례기부금,㉰ 특례기부금,세액공제액,세액공제액,세액공제액,"500,000\n500,000\n75,000\n75,000"
30,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉱ 우리사주조합 기부금,㉱ 우리사주조합 기부금,㉱ 우리사주조합 기부금,㉱ 우리사주조합 기부금,None,None,공제대상금액,None
31,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉱ 우리사주조합 기부금,㉱ 우리사주조합 기부금,㉱ 우리사주조합 기부금,㉱ 우리사주조합 기부금,None,None,세액공제액,None
32,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉲ 일반기부금(종교단체 외),㉲ 일반기부금(종교단체 외),㉲ 일반기부금(종교단체 외),㉲ 일반기부금(종교단체 외),공제대상금액,공제대상금액,공제대상금액,None
33,세 액 공 제,특 별 세 액 공 제,￾￾ 기 부 금,￾￾ 기 부 금,㉲ 일반기부금(종교단체 외),㉲ 일반기부금(종교단체 외),㉲ 일반기부금(종교단체 외),㉲ 일반기부금(종교단체 외),세액공제액,세액공제액,세액공제액,None
34,세 액 공 제,특 별 세 액 공 제,공제대상금액\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제대상금액\n1...,공제대상금액\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제대상금액\n1...,공제대상금액\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제대상금액\n1...,공제대상금액\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제대상금액\n1...,공제대상금액\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제대상금액\n1...,공제대상금액\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제대상금액\n1...,공제대상금액\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제대상금액\n1...,공제대상금액\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제대상금액\n1...,공제대상금액\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제대상금액\n1...,"100,000\n100,000\n90,909\n90,909\n100,000\n100..."
35,세 액 공 제,￾￾ 납세조합공제,￾￾ 납세조합공제,￾￾ 납세조합공제,￾￾ 납세조합공제,￾￾ 납세조합공제,￾￾ 납세조합공제,￾￾ 납세조합공제,￾￾ 납세조합공제,￾￾ 납세조합공제,￾￾ 납세조합공제,None
36,세 액 공 제,￾￾ 외국납부,￾￾ 외국납부,공제대상금액,공제대상금액,공제대상금액,공제대상금액,공제대상금액,공제대상금액,공제대상금액,공제대상금액,None
37,세 액 공 제,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,￾￾ 월세액,None,None,세액공제액,"3,842,518"
38,세 액 공 제,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,￾￾ 세액공제 계,"3,992,518"
39,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,공제대상금액\n액 공 제\n10만원 이하\n세액공제액\n㉮ 정치 자금 기부금\n공제...,"100,000\n100,000\n90,909\n90,909\n100,000\n100..."

Page 294 - Table 0 DataFrame:

       0                        1                       2
0   None                    서 식 명                    None
1      1               근로소득 지급명세서  소득세법 시행규칙 별지 제24호서식(1)
2      2               퇴직소득 지급명세서  소득세법 시행규칙 별지 제24호서식(2)
3      3          거주자의 사업소득 지급명세서  소득세법 시행규칙 별지 제23호서식(2)
4      4        사업소득 지급명세서(연말정산용)  소득세법 시행규칙 별지 제23호서식(3)
5      5          거주자의 기타소득 지급명세서  소득세법 시행규칙 별지 제23호서식(4)
6      6  비거주자의 사업소득·기타소득 등 지급명세서  소득세법 시행규칙 별지 제23호서식(5)
7      7            이자·배당소득 지급명세서  소득세법 시행규칙 별지 제23호서식(1)
8      8                의료비 지급명세서     소득세법 시행규칙 별지 제43호서식
9      9    비거주자의 유가증권 양도소득 지급명세서  소득세법 시행규칙 별지 제24호서식(7)
10    10          비거주자 양도소득 지급명세서  소득세법 시행규칙 별지 제24호서식(8)
11    11               연금계좌 지급명세서  소득세법 시행규칙 별지 제24호서식(6)
12  None       종교인소득 지급명세서(연말정산용)                    None

Page 303 - Table 0 DataFrame:

   0   1   2   3   4   5   6   7   8   9   10  11  12  13
0   ❸   ❸   ❸   ❸   ❸   ❸   ❸   ❸   ❸   ❸   ❸   ❸   ❸   ❸
1  ❹❹  ❹❹  ❹❹  ❹❹  ❹❹  ❹❹  ❹❹  ❹❹  ❹❹  ❹❹  ❹❹  ❹❹  ❹❹  ❹❹

Page 331 - Table 0 DataFrame:

,0,1,2,3,4,5
0,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03
1,None,None,None,None,None,2025-02\n2025-02\n2025-03
2,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03
3,None,2025-02,2025-02,None,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03
4,None,2025-03,2025-03,None,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03
5,None,None,None,None,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03
6,None,None,None,None,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03
7,None,None,None,None,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03
8,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03
9,None,None,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03
10,None,None,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03
11,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03,2025-02\n2025-02\n2025-03

Page 332 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7
0,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,None,None,None,2025-03-10 14:58:32,2025-03-10 14:58:32,None,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...
1,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,None,None,None,None,None,None,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...
2,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,None,None,None,None,None,None,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...
3,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,None,None,None,None,None,None,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...
4,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...,2025-03-10 14:58:32\n2025년 02월\n2025년 02월\n202...

Page 332 - Table 1 DataFrame:

           0
0  2025년 02월
1  2025년 02월
2  2025년 03월

Page 351 - Table 0 DataFrame:

       0         1         2             3             4
0    구 분     단순경비율     단순경비율  소득률(1-단순경비율)  소득률(1-단순경비율)
1    구 분  4천만원 이하분  4천만원 초과분      4천만원 이하분      4천만원 초과분
2  보험모집인     77.6%     68.6%         22.4%         31.4%
3  방문판매원     75.0%     65.0%         25.0%         35.0%
4   None     80.0%     72.0%         20.0%          None

Page 352 - Table 0 DataFrame:

           0                                       1
0       None                                   해당 내역
1  사업소득 수입금액        사업소득 연말정산대상자가 연간\n지급받은 사업소득 수입금액
2     사업소득금액               연간 수입금액 × 연말정산 사업소득의\n소득률
3     종합소득공제                    기본공제, 추가공제, 연금보험료공제,
4  그 밖의 소득공제             개인연금저축 소득공제\n투자조합 출자 등 소득공제
5   종합소득과세표준            사업소득금액 - 종합소득공제 -\n그 밖의 소득공제
6       산출세액                         종합소득과세표준 × 기본세율
7       세액공제  자녀세액공제, 연금계좌세액공제\n기부금세액공제, 표준세액공제(7만원)
8       결정세액                             산출세액 - 세액공제
9       None                            결정세액 - 기납부세액

Page 355 - Table 0 DataFrame:

                                                   0       1             2
0  [○]사업소득 원천징수영수증(연말정산용)\n관리번호\n[ ]사업소득 지급명세서(연말...  소득자 구분        소득자 구분
1  [○]사업소득 원천징수영수증(연말정산용)\n관리번호\n[ ]사업소득 지급명세서(연말...    거주구분  거주자1 / 비거주자2
2  [○]사업소득 원천징수영수증(연말정산용)\n관리번호\n[ ]사업소득 지급명세서(연말...   내·외국인   내국인1 / 외국인9
3  [○]사업소득 원천징수영수증(연말정산용)\n관리번호\n[ ]사업소득 지급명세서(연말...    거주지국        거주지국코드

Page 355 - Table 1 DataFrame:

       0      1
0   관리번호   None
1  ①귀속연도  2024년

Page 355 - Table 2 DataFrame:

        0                  1
0  징수 의무자  ② 법인명(상호) : OO(주)
1  징수 의무자     ⑤ 주민(법인)등록번호 :

Page 355 - Table 3 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,None,⑬ 발생처\n구분,⑭ 법인명\n(상호),⑮ 사업자등록번호,⑮ 사업자등록번호,⑮ 사업자등록번호,⑮ 사업자등록번호,￾￾ 발생기간 (연·월·일),￾￾ 발생기간 (연·월·일),￾￾ 발생기간 (연·월·일),￾￾ 발생기간 (연·월·일),￾￾ 발생기간 (연·월·일),￾￾ 발생기간 (연·월·일),￾￾ 지급액 (수입금액),￾￾ 지급액 (수입금액)
1,None,주(현),None,－,None,None,－,2024. 1. 1. ~ 2024. 12. 31.,2024. 1. 1. ~ 2024. 12. 31.,2024. 1. 1. ~ 2024. 12. 31.,2024. 1. 1. ~ 2024. 12. 31.,2024. 1. 1. ~ 2024. 12. 31.,2024. 1. 1. ~ 2024. 12. 31.,None,"70,000,000"
2,None,종(전),None,－,None,None,－,. . ~ . .,. . ~ . .,. . ~ . .,. . ~ . .,. . ~ . .,. . ~ . .,None,None
3,None,사업별 수입금액 계,사업별 수입금액 계,보험모집 수입금액 계,보험모집 수입금액 계,보험모집 수입금액 계,보험모집 수입금액 계,보험모집 수입금액 계,보험모집 수입금액 계,보험모집 수입금액 계,보험모집 수입금액 계,보험모집 수입금액 계,보험모집 수입금액 계,None,None
4,None,사업별 수입금액 계,사업별 수입금액 계,방문판매 수입금액 계,방문판매 수입금액 계,방문판매 수입금액 계,방문판매 수입금액 계,방문판매 수입금액 계,방문판매 수입금액 계,방문판매 수입금액 계,방문판매 수입금액 계,방문판매 수입금액 계,방문판매 수입금액 계,None,"70,000,000"
5,None,사업별 수입금액 계,사업별 수입금액 계,음료배달 수입금액 계,음료배달 수입금액 계,음료배달 수입금액 계,음료배달 수입금액 계,음료배달 수입금액 계,음료배달 수입금액 계,음료배달 수입금액 계,음료배달 수입금액 계,음료배달 수입금액 계,음료배달 수입금액 계,None,None
6,None,사업별 수입금액 계,사업별 수입금액 계,합계 (124),합계 (124),합계 (124),합계 (124),합계 (124),합계 (124),합계 (124),합계 (124),합계 (124),합계 (124),None,"70,000,000"
7,None,사업별,￾￾수입금액\n(￾￾),￾￾ 적용소득률,￾￾ 적용소득률,￾￾ 적용소득률,￾￾ 적용소득률,￾￾ 소득금액,￾￾ 소득금액,￾￾ 소득금액,￾￾ 소득금액,￾￾ 소득금액,￾￾ 소득금액,￾￾ 소득금액,￾￾\n비고
8,None,사업별,￾￾수입금액\n(￾￾),4천만원 이하분,4천만원 이하분,4천만원 초과분,4천만원 초과분,4천만원 이하분,4천만원 이하분,4천만원 초과분,4천만원 초과분,4천만원 초과분,합계,합계,￾￾\n비고
9,None,보험모집,None,22.4%,22.4%,31.4%,31.4%,None,None,None,None,None,None,None,None
10,None,방문판매,"70,000,000",25.0%,25.0%,35.0%,35.0%,"10,000,000","10,000,000","10,500,000","10,500,000","10,500,000","20,500,000","20,500,000",None
11,None,음료배달,None,20.0%,20.0%,28.0%,28.0%,None,None,None,None,None,None,None,None
12,None,(124)합계,"70,000,000",None,None,None,None,None,None,None,None,None,None,None,None
13,None,None,"20,500,000",￾￾ 소기업·소상공인 공제부금,￾￾ 소기업·소상공인 공제부금,￾￾ 소기업·소상공인 공제부금,￾￾ 소기업·소상공인 공제부금,구 분,구 분,구 분,소득세,지방소득세,지방소득세,농어촌\n특별세,계
14,기 본 공 제,￾￾ 본인,"1,500,000",￾￾ 투자조합 출자등 소득공제,￾￾ 투자조합 출자등 소득공제,￾￾ 투자조합 출자등 소득공제,￾￾ 투자조합 출자등 소득공제,￾￾ 결정세액,￾￾ 결정세액,￾￾ 결정세액,"456,800","45,680","45,680",None,"502,480"
15,기 본 공 제,￾￾ 배우자,"1,500,000",￾￾청년형 장기집합투자증권\n저축 소득공제,￾￾청년형 장기집합투자증권\n저축 소득공제,￾￾청년형 장기집합투자증권\n저축 소득공제,￾￾청년형 장기집합투자증권\n저축 소득공제,기납부\n세액,￾￾ 종(전)\n근무지,￾￾ 종(전)\n근무지,None,None,None,None,None
16,기 본 공 제,￾￾ 부양가족\n( 2 명),"3,000,000",￾￾ 소득공제 등 종합한도 초과액,￾￾ 소득공제 등 종합한도 초과액,￾￾ 소득공제 등 종합한도 초과액,￾￾ 소득공제 등 종합한도 초과액,기납부\n세액,￾￾ 주(현)\n근무지,￾￾ 주(현)\n근무지,"2,100,000","210,000","210,000",None,"2,310,000"
17,추 가 공 제,￾￾ 경로우대\n( 명)\n￾￾ 장애인\n( 명),None,"￾￾ 종합소득 과세표준 13,780,000","￾￾ 종합소득 과세표준 13,780,000","￾￾ 종합소득 과세표준 13,780,000","￾￾ 종합소득 과세표준 13,780,000",㊼ 차감 납부할\n세액,㊼ 차감 납부할\n세액,㊼ 차감 납부할\n세액,"△1,643,200","△164,320","△164,320",None,"△1,807,520"
18,추 가 공 제,￾￾ 경로우대\n( 명)\n￾￾ 장애인\n( 명),None,"￾￾ 산출세액 826,800\n￾￾ 결혼세액공제","￾￾ 산출세액 826,800\n￾￾ 결혼세액공제","￾￾ 산출세액 826,800\n￾￾ 결혼세액공제","￾￾ 산출세액 826,800\n￾￾ 결혼세액공제",㊼ 차감 납부할\n세액,㊼ 차감 납부할\n세액,㊼ 차감 납부할\n세액,"△1,643,200","△164,320","△164,320",None,"△1,807,520"
19,추 가 공 제,￾￾ 장애인\n( 명)\n￾￾ 부녀자\n￾￾ 한부모가족,None,"￾￾ 결혼세액공제\n공제대상자녀\n￾￾ 자녀 세액 공제\n300,000\n( 2명)...","￾￾ 결혼세액공제\n공제대상자녀\n￾￾ 자녀 세액 공제\n300,000\n( 2명)...","￾￾ 결혼세액공제\n공제대상자녀\n￾￾ 자녀 세액 공제\n300,000\n( 2명)...","￾￾ 결혼세액공제\n공제대상자녀\n￾￾ 자녀 세액 공제\n300,000\n( 2명)...",None,None,None,None,None,None,None,(서명 또는 인)
20,추 가 공 제,￾￾ 부녀자,None,"공제대상자녀\n￾￾ 자녀\n300,000\n( 2명)","공제대상자녀\n￾￾ 자녀\n300,000\n( 2명)","공제대상자녀\n￾￾ 자녀\n300,000\n( 2명)","공제대상자녀\n￾￾ 자녀\n300,000\n( 2명)",None,None,None,None,None,None,None,(서명 또는 인)
21,추 가 공 제,￾￾ 한부모가족,None,세액 공제\n출산·입양자\n( 명),세액 공제\n출산·입양자\n( 명),세액 공제\n출산·입양자\n( 명),세액 공제\n출산·입양자\n( 명),None,None,None,None,None,None,None,(서명 또는 인)
22,None,None,None,￾￾ 연금계좌세액공제,￾￾ 연금계좌세액공제,￾￾ 연금계좌세액공제,￾￾ 연금계좌세액공제,None,None,None,None,None,None,None,(서명 또는 인)
23,None,None,"6,000,000",정치자금,정치자금,정치자금,정치자금,None,None,None,None,None,None,None,(서명 또는 인)
24,None,None,"6,000,000",고향사랑기부금,고향사랑기부금,고향사랑기부금,고향사랑기부금,None,None,None,None,None,None,None,(서명 또는 인)
25,None,None,"6,000,000",￾￾ 기부금\n특례기부금,￾￾ 기부금\n특례기부금,￾￾ 기부금\n특례기부금,￾￾ 기부금\n특례기부금,None,None,None,None,None,None,None,(서명 또는 인)
26,None,None,"6,000,000",세액공제\n우리사주조합,세액공제\n우리사주조합,세액공제\n우리사주조합,세액공제\n우리사주조합,None,None,None,None,None,None,None,(서명 또는 인)
27,None,None,"720,000",일반기부금,일반기부금,일반기부금,일반기부금,None,None,None,None,None,None,None,(서명 또는 인)
28,소득공제,소득공제,"720,000",￾￾ 표준세액공제 70.000,￾￾ 표준세액공제 70.000,￾￾ 표준세액공제 70.000,￾￾ 표준세액공제 70.000,None,None,None,None,None,None,None,None
29,None,None,명세(해당 소득자의,명세(해당 소득자의 기본공제와 추가공제,None,None,명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로,"공제금액 계산명세가 있는 자만 적습니다. 다만, 본인은 표기하지",None,None,None,None,None,None,않습니다)

Page 355 - Table 4 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,None,성 명,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,관계,성 명,주민등록번호,관계,성 명,주민등록번호
1,3,김선이,7,6,0,1,0,1,-,* * *,*,*,*,*,None,None,-,None,None,-
2,4,박서영,1,1,0,1,0,1,-,* * *,*,*,*,*,None,None,-,None,None,-
3,None,박현영,1,2,0,1,0,1,-,* * *,*,*,*,*,None,None,-,None,None,-

Page 367 - Table 0 DataFrame:

       0             1
0   거주구분  거주자1 / 비거주자2
1  내·외국인    내국인1/ 외국인9
2   거주지국        거주지국코드

Page 367 - Table 1 DataFrame:

,0,1,2,3,4
0,징수 의무자,① 법인명,공무원연금공단,② 대표자,None
1,징수 의무자,③ 사업자등록번호,* * * - * * - * * * * *,④ 법인등록번호,* * * * * * - * * * * * * *
2,징수 의무자,⑤ 소재지(주소),None,None,None
3,소득자,⑥ 성명,None,None,500101-1******
4,소득자,⑧ 주소,*** *** *** ***,*** *** *** ***,*** *** *** ***

Page 367 - Table 2 DataFrame:

         0           1                           2               3
0  연금지급 내역    ⑪ 총연금수령액  ⑫ 연금제외소득\n(2001.12.31.이전분)  ⑬ 장애연금등\n비과세연금
1  연금지급 내역  30,000,000                  10,600,000            None

Page 367 - Table 3 DataFrame:

,0,1,2,3,4,5,6,7,8,9
0,⑮ 총연금액(=⑭),⑮ 총연금액(=⑭),⑮ 총연금액(=⑭),⑮ 총연금액(=⑭),"19,400,000",￾￾ 종합소득 과세표준(⑰-￾￾),￾￾ 종합소득 과세표준(⑰-￾￾),￾￾ 종합소득 과세표준(⑰-￾￾),￾￾ 종합소득 과세표준(⑰-￾￾),"7,560,000"
1,⑯,None,None,None,"6,840,000",￾￾ 산출세액,￾￾ 산출세액,￾￾ 산출세액,￾￾ 산출세액,"453,600"
2,None,None,None,None,None,세액 감면,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,￾￾ ｢소득세법｣,None
3,None,None,None,None,None,세액 감면,￾￾ ｢조세특례제한법｣,￾￾ ｢조세특례제한법｣,￾￾ ｢조세특례제한법｣,None
4,⑰,None,None,None,"12,560,000",세액 감면,￾￾ 감면세액 계,￾￾ 감면세액 계,￾￾ 감면세액 계,None
5,종합 소득 공제,기본공제,⑱ 본인\n⑲ 배우자\n⑳ 부양가족( 명)\n￾￾ 경로우대( 2명),⑱ 본인\n⑲ 배우자\n⑳ 부양가족( 명)\n￾￾ 경로우대( 2명),"1,500,000\n1,500,000\n2,000,000",세액 공제,￾￾자녀\n￾￾ 표준세액공제,공제대상자녀 ( 명)\n출산·입양자 ( 명),공제대상자녀 ( 명)\n출산·입양자 ( 명),"70,000"
6,종합 소득 공제,기본공제,⑳ 부양가족( 명),⑳ 부양가족( 명),None,세액 공제,￾￾자녀\n￾￾ 표준세액공제,출산·입양자 ( 명),출산·입양자 ( 명),None
7,종합 소득 공제,추가공제,￾￾ 경로우대( 2명),￾￾ 경로우대( 2명),"2,000,000",세액 공제,￾￾ 표준세액공제,￾￾ 표준세액공제,￾￾ 표준세액공제,"70,000"
8,종합 소득 공제,추가공제,￾￾ 장애인( 명)\n￾￾ 부녀자\n￾￾ 한부모,￾￾ 장애인( 명)\n￾￾ 부녀자\n￾￾ 한부모,None,세액 공제,￾￾ 외국납부\n￾￾ 세액공제 계,￾￾ 외국납부\n￾￾ 세액공제 계,￾￾ 외국납부\n￾￾ 세액공제 계,"70,000"
9,종합 소득 공제,￾￾ 소득공제 계,￾￾ 소득공제 계,￾￾ 소득공제 계,"5,000,000",None,None,None,None,None
10,세액 명세,구 분,구 분,소득세,소득세,지방소득세,지방소득세,지방소득세,농어촌특별세,계
11,세액 명세,￾￾ 결정세액,￾￾ 결정세액,"383,600","383,600","38,360","38,360","38,360",None,"421,960"
12,세액 명세,￾￾ 기납부세액,￾￾ 기납부세액,"1,251,120","1,251,120","125,110","125,110","125,110",None,"1,376,230"
13,세액 명세,￾￾ 차감징수세액,￾￾ 차감징수세액,"△867,520","△867,520","△86,750","△86,750","△86,750",None,None

Page 367 - Table 4 DataFrame:

     0                            1     2     3       4     5     6
0   성명                       주민등록번호    관계    성명  주민등록번호    관계    성명
1  정이이  5 1 0 1 0 1 - 2 2 3 4 5 6 7  None  None       －  None  None

Page 372 - Table 0 DataFrame:

,0,1,2,3
0,분류명,분류명,분류명,설 명
1,소분류,세분류,세세분류,설 명
2,종교 관련 종사자\n(254),성직자\n(2541),목사 (25411),"기독교 종교예식이나 의식을 집행하고 관장하며 신자들에게 정신적, 도덕적\n지도를 하..."
3,종교 관련 종사자\n(254),성직자\n(2541),신부 (25412),"천주교 종교예식이나 의식을 집행하고 관장하며 신자들에게 정신적, 도덕적\n지도를 하..."
4,종교 관련 종사자\n(254),성직자\n(2541),승려 (25413),"불교 종교예식이나 의식을 집행하고 관장하며 신자들에게 정신적, 도덕적 지도를\n하는..."
5,종교 관련 종사자\n(254),성직자\n(2541),교무 (25414),"원불교 종교예식이나 의식을 집행하고 관장하며 신자들에게 정신적, 도덕적\n지도를 하..."
6,종교 관련 종사자\n(254),성직자\n(2541),그 외 성직자\n(25419),상기 세세분류 어느 항목에도 포함되지 않는 기타 종교관련 성직자가 여기에\n분류(전...
7,종교 관련 종사자\n(254),기타 종교 관련 종사원\n(2549),수녀 및 수사\n(25491),"천주교회에서 신부를 보조하여 미사 등의 집전을 보조하며, 신자들에게 신앙 및\n정신..."
8,종교 관련 종사자\n(254),기타 종교 관련 종사원\n(2549),전도사\n(25492),"교회에서 맡은 역할에 따라 청소년이나 신자들의 교육을 담당하거나, 찬양 율동,\n음..."
9,종교 관련 종사자\n(254),기타 종교 관련 종사원\n(2549),그 외 종교관련\n종사원 (25499),None

Page 374 - Table 0 DataFrame:

,0,1,2
0,None,종교인소득(기타소득)\n(종교인소득의 과세체계 적용),근로소득\n(근로소득의 과세체계 적용)
1,과세소득,종교인이 종교활동과 관련하여 소속된 종교단체\n로부터 받은 소득,종교인이 종교활동과 관련하여 소속된 종교단체\n로부터 받은 소득
2,비과세소득,"학자금, 식사·식사대, 실비변상액(종교활동비 포함),\n출산보육수당, 사택제공 이익 등",근로소득의 비과세소득 규정을 적용\n(사실상 동일)
3,필요경비\n또는 근로소득공제,"종교인이 받은금액 필요경비\n2천만원 이하\n80%\n2천만원 초과\n1,600만원...",총 급여액 근로소득공제금액\n500만원 이하\n총급여액의 70%\n500만원 초과\...
4,소득공제,"기본공제, 추가공제, 연금보험료 공제, 벤처투자\n조합 출자 등, 개인연금저축, 청...","(좌동) + 특별소득공제(건보료 등), 주택마련저축\n공제, 신용카드 공제, 장기펀..."
5,세액공제,"자녀세액공제, 기부금공제, 외국납부, 연금계좌\n세액공제, 표준공제(7만원)","(좌동, 표준공제는 13만원) + 월세, 의료비·교육비·\n보험료공제, 근로소득세액공제"
6,None,수급 가능,None

Page 375 - Table 0 DataFrame:

,0,1,2,3,4
0,과세 체계,과세 체계,과세 체계,종교인소득\n(기타소득),근로소득
1,None,None,None,총 수입금액,총 급여액
2,None,None,None,필요경비(20~80%),근로소득공제(2~70%)
3,소득 공제,인적,소득금액\n기본(본인·배우자·부양가족 人당 150만원),○,○
4,소득 공제,인적,"추가(경로 100만원, 장애인 200만원 등)",○,○
5,소득 공제,국민연금 등 공적연금보험료(전액),국민연금 등 공적연금보험료(전액),○,○
6,소득 공제,특별,건강·고용보험료(전액),×,○
7,소득 공제,특별,"주택자금(600∼2,000만원 한도)",×,○
8,소득 공제,조특법,신용카드 등 사용금액 공제,×,○
9,소득 공제,조특법,장기집합투자증권저축,×,○
10,소득 공제,조특법,청년형장기집합투자증권저축,○,○
11,소득 공제,조특법,창업투자조합 출자금 등,○,○
12,소득 공제,조특법,개인연금저축\n과세표준,○,○
13,세액 공제,(×) 세율(6~45%)\n산출세액\n근로소득(20만원∼74만원 한도),(×) 세율(6~45%)\n산출세액\n근로소득(20만원∼74만원 한도),×,○
14,세액 공제,외국납부(국외원천소득비율 한도),외국납부(국외원천소득비율 한도),○,○
15,세액 공제,"자녀(1명 15만원, 2명 35만원, 3명 65만원)","자녀(1명 15만원, 2명 35만원, 3명 65만원)",○,○
16,세액 공제,"연금계좌[15%(12%), 600만원(퇴직연금 포함 900 한도)]\n※ 개인종합자...","연금계좌[15%(12%), 600만원(퇴직연금 포함 900 한도)]\n※ 개인종합자...",○,○
17,세액 공제,특별,"보험료(12%(장애인전용 15%), 100만원 한도)",×,○
18,세액 공제,특별,"의료비(15%(항목별 20%, 30%), 700만원 한도)",×,○
19,세액 공제,특별,"교육비(15%, 300만원(대학 900) 한도)",×,○
20,세액 공제,특별,"기부금(금액별 15%, 30%, 40%)",○,○
21,세액 공제,표준세액공제(근로소득은 특별 소득·세액공제 미신청자),표준세액공제(근로소득은 특별 소득·세액공제 미신청자),○ (7만원),○ (13만원)
22,세액 공제,조특법,"정치자금기부금(금액별 100/110, 15%, 25%)",○,○
23,세액 공제,조특법,"고향사랑기부금(금액별 100/110, 15%)\n결정세액",○,○
24,기납부세액 차감\n차가감 납부(환급)할 세액,기납부세액 차감\n차가감 납부(환급)할 세액,기납부세액 차감\n차가감 납부(환급)할 세액,None,None

Page 379 - Table 0 DataFrame:

                                                   0       1             2
0  [ ]종교인소득 원천징수영수증(연말정산용)\n관리번호\n[✓]종교인소득 지급명세서(...  소득자 구분        소득자 구분
1  [ ]종교인소득 원천징수영수증(연말정산용)\n관리번호\n[✓]종교인소득 지급명세서(...    거주구분  거주자1 / 비거주자2
2  [ ]종교인소득 원천징수영수증(연말정산용)\n관리번호\n[✓]종교인소득 지급명세서(...   내·외국인   내국인1 / 외국인9
3  [ ]종교인소득 원천징수영수증(연말정산용)\n관리번호\n[✓]종교인소득 지급명세서(...    거주지국        거주지국코드

Page 379 - Table 1 DataFrame:

        0      1                                                  2
0    관리번호   None  거주구분 거주자1 / 비거주자2\n[✓]종교인소득 지급명세서(연말정산용)\n내·외국...
1  ① 귀속연도  2024년  거주구분 거주자1 / 비거주자2\n[✓]종교인소득 지급명세서(연말정산용)\n내·외국...

Page 379 - Table 2 DataFrame:

        0                            1
0  징수 의무자                 ② 종교단체명 **교회
1  징수 의무자  ⑤ 주민(법인)등록번호 7*****-*******

Page 379 - Table 3 DataFrame:

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,종교인\n소득,⑩ 발생처\n구분,⑩ 발생처\n구분,⑩ 발생처\n구분,⑩ 발생처\n구분,⑩ 발생처\n구분,⑪ 종교 단체명,⑪ 종교 단체명,⑪ 종교 단체명,⑪ 종교 단체명,...,⑫\n사업자등록(고유)번호,⑫\n사업자등록(고유)번호,⑫\n사업자등록(고유)번호,⑫\n사업자등록(고유)번호,⑬\n발생기간(연·월·일),⑬\n발생기간(연·월·일),⑬\n발생기간(연·월·일),⑭\n지급액(비과세소득 제외),⑭\n지급액(비과세소득 제외),⑭\n지급액(비과세소득 제외)
1,종교인\n소득,주(현),주(현),주(현),주(현),주(현),None,None,None,None,...,None,None,None,None,2024.5.6.~2024.12.31.,2024.5.6.~2024.12.31.,2024.5.6.~2024.12.31.,"16,000,000","16,000,000","16,000,000"
2,종교인\n소득,종(전),종(전),종(전),종(전),종(전),**교회,**교회,**교회,**교회,...,*,*,* *,* *,2024.1.1.~2024.5.5.,2024.1.1.~2024.5.5.,2024.1.1.~2024.5.5.,"6,000,000","6,000,000","6,000,000"
3,소득 금액,⑯ 종교인소득(⑭),⑯ 종교인소득(⑭),⑯ 종교인소득(⑭),⑯ 종교인소득(⑭),⑯ 종교인소득(⑭),⑯ 종교인소득(⑭),⑯ 종교인소득(⑭),⑯ 종교인소득(⑭),⑯ 종교인소득(⑭),...,⑰ 필요경비,⑰ 필요경비,⑰ 필요경비,⑰ 필요경비,⑰ 필요경비,⑰ 필요경비,None,None,⑱,소득금액(⑯-⑰)
4,소득 금액,"22,000,000","22,000,000","22,000,000","22,000,000","22,000,000","22,000,000","22,000,000","22,000,000","22,000,000",...,"17,000,000","17,000,000","17,000,000","17,000,000","17,000,000","17,000,000",None,None,None,"5,000,000"
5,￾￾,None,None,None,None,None,None,None,None,None,...,"5,000,000","5,000,000","5,000,000","5,000,000","5,000,000","5,000,000",구 분,구 분,소득세,지방 소득세\n농어촌\n특별세
6,기본 공제\n인 적 공 제\n추가 공제\n㉗,기본 공제,⑳ 본인,⑳ 본인,⑳ 본인,⑳ 본인,⑳ 본인,⑳ 본인,⑳ 본인,⑳ 본인,...,㉜ 소득공제 등 종합한도 초과액,㉜ 소득공제 등 종합한도 초과액,㉜ 소득공제 등 종합한도 초과액,㉜ 소득공제 등 종합한도 초과액,None,None,㊶ 결정세액,㊶ 결정세액,"50,000","5,000"
7,기본 공제\n인 적 공 제\n추가 공제\n㉗,기본 공제,㉑ 배우자,㉑ 배우자,㉑ 배우자,㉑ 배우자,㉑ 배우자,㉑ 배우자,㉑ 배우자,㉑ 배우자,...,㉝ 종합소득과세표준,㉝ 종합소득과세표준,㉝ 종합소득과세표준,㉝ 종합소득과세표준,"2,000,000","2,000,000",㊷종(전)\n근무지\n기납부,㊷종(전)\n근무지\n기납부,None,None
8,기본 공제\n인 적 공 제\n추가 공제\n㉗,기본 공제,㉒ 부양가족(1명),㉒ 부양가족(1명),㉒ 부양가족(1명),㉒ 부양가족(1명),㉒ 부양가족(1명),㉒ 부양가족(1명),㉒ 부양가족(1명),㉒ 부양가족(1명),...,㉞ 산출세액,㉞ 산출세액,㉞ 산출세액,㉞ 산출세액,"120,000","120,000",㊷종(전)\n근무지\n기납부,㊷종(전)\n근무지\n기납부,None,None
9,기본 공제\n인 적 공 제\n추가 공제\n㉗,None,None,None,None,None,None,None,None,None,...,㉟ 결혼세액공제,㉟ 결혼세액공제,㉟ 결혼세액공제,㉟ 결혼세액공제,None,None,세액\n㊸주(현)\n근무지,세액\n㊸주(현)\n근무지,"31,200","3,120"
10,기본 공제\n인 적 공 제\n추가 공제\n㉗,추가 공제,㉓ 경로우대( 명)\n㉔ 장애인( 명)\n㉕ 부녀자,㉓ 경로우대( 명)\n㉔ 장애인( 명)\n㉕ 부녀자,㉓ 경로우대( 명)\n㉔ 장애인( 명)\n㉕ 부녀자,㉓ 경로우대( 명)\n㉔ 장애인( 명)\n㉕ 부녀자,㉓ 경로우대( 명)\n㉔ 장애인( 명)\n㉕ 부녀자,㉓ 경로우대( 명)\n㉔ 장애인( 명)\n㉕ 부녀자,㉓ 경로우대( 명)\n㉔ 장애인( 명)\n㉕ 부녀자,㉓ 경로우대( 명)\n㉔ 장애인( 명)\n㉕ 부녀자,...,㊱ 자녀 세액 공제 공제대상자녀( 명)\n출산·입양자( 명)\n㊲ 연금계좌 세액공제,㊱ 자녀 세액 공제 공제대상자녀( 명)\n출산·입양자( 명)\n㊲ 연금계좌 세액공제,㊱ 자녀 세액 공제 공제대상자녀( 명)\n출산·입양자( 명)\n㊲ 연금계좌 세액공제,㊱ 자녀 세액 공제 공제대상자녀( 명)\n출산·입양자( 명)\n㊲ 연금계좌 세액공제,None,None,None,None,"㊹ 차감납부할세액 18,800","1,880 20,680"
11,기본 공제\n인 적 공 제\n추가 공제\n㉗,추가 공제,㉖ 한부모가족\n연금보험료공제,㉖ 한부모가족\n연금보험료공제,㉖ 한부모가족\n연금보험료공제,㉖ 한부모가족\n연금보험료공제,㉖ 한부모가족\n연금보험료공제,㉖ 한부모가족\n연금보험료공제,㉖ 한부모가족\n연금보험료공제,㉖ 한부모가족\n연금보험료공제,...,정치자금기부금\n고향사랑기부금,정치자금기부금\n고향사랑기부금,정치자금기부금\n고향사랑기부금,정치자금기부금\n고향사랑기부금,None,None,None,None,위\n2025년 3월,영수(지급)합니다.\n일
12,㉗,None,None,None,None,None,None,None,None,None,...,고향사랑기부금,고향사랑기부금,고향사랑기부금,고향사랑기부금,None,None,None,None,2025년 3월,일
13,㉘,None,None,None,None,None,None,None,None,None,...,특례기부금\n우리사주조합,특례기부금\n우리사주조합,특례기부금\n우리사주조합,특례기부금\n우리사주조합,None,None,None,None,None,None
14,㉘,None,None,None,None,None,None,None,None,None,...,일반기부금,일반기부금,일반기부금,일반기부금,None,None,None,None,징수(보고)의무자,**교회 (서명 또는
15,㉙,None,None,None,None,None,None,None,None,None,...,㊴표준세액공제,㊴표준세액공제,㊴표준세액공제,㊴표준세액공제,"70,000","70,000",None,None,None,None
16,㉚,None,None,None,None,None,None,None,None,None,...,㊵외국납부세액공제,㊵외국납부세액공제,㊵외국납부세액공제,㊵외국납부세액공제,None,None,None,None,** 세무서장 귀하,None
17,㉛ 청년형,None,None,None,None,None,None,None,None,None,...,㊵외국납부세액공제,㊵외국납부세액공제,㊵외국납부세액공제,㊵외국납부세액공제,None,None,None,None,None,None
18,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...,￾￾ 인적공제자 명세(해당 소득자의 기본공제와 추가공제 및 부양 등으로 공제금액 계...
19,관계 성,성 명,성 명,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,...,성 명,주민등록번호,주민등록번호,주민등록번호,주민등록번호,주민등록번호,관계,성 명,성 명,None
20,3,김**,김**,7,*,*,*,*,*,-,...,None,None,None,None,None,-,None,None,None,-
21,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,-,None,None,None,-
22,None,None,None,None,None,None,None,None,None,-,...,None,None,None,None,None,-,None,None,None,-

Page 380 - Table 0 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11
0,"① 법인명\n(상호,성명)",② 사업자(주민)\n등록번호,③ 소재지\n(주소),④ 연간 소득 인원,⑤ 연간 총지급\n건수,⑥ 연간 총지급액\n계,⑦ 비과세\n소득,⑧ 연간 소득금액\n계,⑨ 세액 집계현황,⑨ 세액 집계현황,⑨ 세액 집계현황,⑨ 세액 집계현황
1,"① 법인명\n(상호,성명)",② 사업자(주민)\n등록번호,③ 소재지\n(주소),④ 연간 소득 인원,⑤ 연간 총지급\n건수,⑥ 연간 총지급액\n계,⑦ 비과세\n소득,⑧ 연간 소득금액\n계,⑩ 소득세,⑪ 지방 소득세,⑫ 농어촌\n특별세,⑬ 계
2,None,123-**-*****,서울 종로 종로*가,3,8,"12,000,000","3,500,000","2,400,000",0,0,0,None

Page 380 - Table 1 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,None,⑭ 소득 구분 코드,⑮ 소득자\n성명 (상호),⑯ 주민 (사업자)\n등록번호,⑰ 내·외\n국인,⑱ 지급 연도,⑲ 지급 건수,⑳ (연간)\n지급총액,㉑ 비과세\n소득,㉒ 필요경비,㉓ 소득금액,㉔ 세율,㉕ 소득세,㉖ 지방 소득세,㉗ 농어촌\n특별세
1,1,77,김**,7*****-*******,1,2024,8,"12,000,000","3,500,000","9,600,000","2,400,000",None,0,0,0
2,2,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,3,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,4,None,None,None,None,None,None,None,None,None,None,None,None,None,None
5,5,None,None,None,None,None,None,None,None,None,None,None,None,None,None
6,6,None,None,None,None,None,None,None,None,None,None,None,None,None,None
7,7,None,None,None,None,None,None,None,None,None,None,None,None,None,None
8,8,None,None,None,None,None,None,None,None,None,None,None,None,None,None
9,9,None,None,None,None,None,None,None,None,None,None,None,None,None,None

Page 381 - Table 0 DataFrame:

,0,1,2,3
0,[ ]근로소득 원천징수영수증\n관리 번호\n[✓]근로소득 지급명세서\n([ ]소득자...,거주구분,거주자1/비거주자2,거주자1/비거주자2
1,[ ]근로소득 원천징수영수증\n관리 번호\n[✓]근로소득 지급명세서\n([ ]소득자...,거주지국,거주지국코드,거주지국코드
2,[ ]근로소득 원천징수영수증\n관리 번호\n[✓]근로소득 지급명세서\n([ ]소득자...,내·외국인,내국인1 /외국인9,내국인1 /외국인9
3,[ ]근로소득 원천징수영수증\n관리 번호\n[✓]근로소득 지급명세서\n([ ]소득자...,외국인단일세율적용,외국인단일세율적용,여 1/부 2
4,[ ]근로소득 원천징수영수증\n관리 번호\n[✓]근로소득 지급명세서\n([ ]소득자...,외국법인소속 파견근로자 여부,외국법인소속 파견근로자 여부,여 1/부 2
5,[ ]근로소득 원천징수영수증\n관리 번호\n[✓]근로소득 지급명세서\n([ ]소득자...,종교관련종사자 여부,종교관련종사자 여부,여 1/부 2
6,[ ]근로소득 원천징수영수증\n관리 번호\n[✓]근로소득 지급명세서\n([ ]소득자...,국적,국적코드,국적코드
7,[ ]근로소득 원천징수영수증\n관리 번호\n[✓]근로소득 지급명세서\n([ ]소득자...,세대주 여부,"세대주1, 세대원2","세대주1, 세대원2"
8,[ ]근로소득 원천징수영수증\n관리 번호\n[✓]근로소득 지급명세서\n([ ]소득자...,연말정산 구분,"계속근로1, 중도퇴사2","계속근로1, 중도퇴사2"

Page 381 - Table 1 DataFrame:

                          0                        1
0            ① 법인명(상호) **성당                     None
1    ③ 사업자등록번호 123-**-*****  ④ 주민등록번호 6*****-*******
2  ③-1 사업자단위과세자 여부\n여1 / 부2                     None

Page 381 - Table 2 DataFrame:

,0,1,2,3,4,5,6,7,8,9,10
0,⑧,None,None,None,None,None,None,None,None,None,None
1,구분,구분,구분,구분,주(현),주(현),종(전),종(전),종(전),￾￾-1 납세조합,None
2,⑨ 근무처명,⑨ 근무처명,⑨ 근무처명,⑨ 근무처명,**성당,**성당,**성당,None,None,None,None
3,⑩ 사업자등록번호,⑩ 사업자등록번호,⑩ 사업자등록번호,⑩ 사업자등록번호,123-**-*****,123-**-*****,312-**-*****,None,None,None,None
4,⑪ 근무기간,⑪ 근무기간,⑪ 근무기간,⑪ 근무기간,24.6.1~24.12.31,24.6.1~24.12.31,24.1.1~24.5.31,~,~,~,~
5,⑫ 감면기간,⑫ 감면기간,⑫ 감면기간,⑫ 감면기간,~,~,~,~,~,~,~
6,⑬ 급여,⑬ 급여,⑬ 급여,⑬ 급여,"11,000,000","11,000,000","7,000,000",None,None,None,"18,000,000"
7,⑭ 상여,⑭ 상여,⑭ 상여,⑭ 상여,None,None,None,None,None,None,None
8,⑮ 인정상여,⑮ 인정상여,⑮ 인정상여,⑮ 인정상여,None,None,None,None,None,None,None
9,⑮-1 주식매수선택권 행사이익,⑮-1 주식매수선택권 행사이익,⑮-1 주식매수선택권 행사이익,⑮-1 주식매수선택권 행사이익,None,None,None,None,None,None,None
10,⑮-2 우리사주조합인출금,⑮-2 우리사주조합인출금,⑮-2 우리사주조합인출금,⑮-2 우리사주조합인출금,None,None,None,None,None,None,None
11,⑮-3 임원 퇴직소득금액 한도초과액,⑮-3 임원 퇴직소득금액 한도초과액,⑮-3 임원 퇴직소득금액 한도초과액,⑮-3 임원 퇴직소득금액 한도초과액,None,None,None,None,None,None,None
12,⑮-4 직무발명보상금,⑮-4 직무발명보상금,⑮-4 직무발명보상금,⑮-4 직무발명보상금,None,None,None,None,None,None,None
13,￾￾ 계,￾￾ 계,￾￾ 계,￾￾ 계,None,None,None,None,None,None,None
14,￾￾ 국외근로,￾￾ 국외근로,M0X,M0X,None,None,None,None,None,None,None
15,￾￾-1 야간근로수당,￾￾-1 야간근로수당,O0X,O0X,None,None,None,None,None,None,None
16,￾￾-2 보육수당,￾￾-2 보육수당,Q0X,Q0X,None,None,None,None,None,None,None
17,￾￾-3 출산지원금,￾￾-3 출산지원금,Q0X,Q0X,None,None,None,None,None,None,None
18,￾￾-4 연구보조비,￾￾-4 연구보조비,H0X,H0X,None,None,None,None,None,None,None
19,￾￾-5,￾￾-5,None,None,None,None,None,None,None,None,None
20,종교활동비,종교활동비,None,None,"1,250,000","1,250,000","660,000",None,None,None,"1,910,000"
21,￾￾-40 비과세식대,￾￾-40 비과세식대,P01,P01,None,None,None,None,None,None,None
22,￾￾ 수련보조수당,￾￾ 수련보조수당,Y22,Y22,None,None,None,None,None,None,None
23,￾￾ 비과세소득 계,￾￾ 비과세소득 계,￾￾ 비과세소득 계,￾￾ 비과세소득 계,"1,250,000","1,250,000","660,000",None,None,None,"1,910,000"
24,￾￾-1 감면소득 계,￾￾-1 감면소득 계,￾￾-1 감면소득 계,￾￾-1 감면소득 계,None,None,None,None,None,None,None
25,구분,구분,구분,구분,구분,구분,￾￾ 소득세,￾￾ 소득세,￾￾ 지방소득세 ￾￾,￾￾ 지방소득세 ￾￾,농어촌특별세
26,￾￾ 결정세액,￾￾ 결정세액,￾￾ 결정세액,￾￾ 결정세액,￾￾ 결정세액,￾￾ 결정세액,"11,210","11,210","1,120","1,120",None
27,기 납부 세액,￾￾ 종(전)근무지(결정세액\n란의 세액을 적습니다),￾￾ 종(전)근무지(결정세액\n란의 세액을 적습니다),사업자\n등록 번호,사업자\n등록 번호,312-82-*****,"13,000","13,000","1,300","1,300",None
28,기 납부 세액,번호\n￾￾ 주(현)근무지,번호\n￾￾ 주(현)근무지,번호\n￾￾ 주(현)근무지,번호\n￾￾ 주(현)근무지,번호\n￾￾ 주(현)근무지,"18,100","18,100","1,810","1,810",None
29,￾￾ 납부특례세액,￾￾ 납부특례세액,￾￾ 납부특례세액,￾￾ 납부특례세액,￾￾ 납부특례세액,￾￾ 납부특례세액,None,None,None,None,None
30,￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),￾￾ 차감징수세액(￾￾-￾￾-￾￾-￾￾),"-19,890","-19,890","-1,990","-1,990",None

Page 384 - Table 0 DataFrame:

,0,1
0,연말정산 유형 ❸ 연말정산 간소화 자료를 국세청에서 일괄제공 받고자 하는 회사,연말정산 유형 ❸ 연말정산 간소화 자료를 국세청에서 일괄제공 받고자 하는 회사
1,❏ 이용대상：자체연말정산 시스템이 있는 회사로서 근로자의 연말정산간소화 자료를간소화...,❏ 이용대상：자체연말정산 시스템이 있는 회사로서 근로자의 연말정산간소화 자료를간소화...
2,∙ 지급명세서 전자제출\n연말정산\n국세청\n(직접작성 또는 전산매체)\n관련 서비...,∙ 지급명세서 전자제출\n연말정산\n국세청\n(직접작성 또는 전산매체)\n관련 서비...
3,비고,"간소화자료를 국세청으로부터 온라인으로 일괄제공 받음으로써 연말정산 자료정리, 보관에..."

Page 385 - Table 0 DataFrame:

,0,1,2
0,연말정산 유형 ❹,연말정산 유형 ❹,편리한 연말정산(간편제출)을 이용하여 간소화자료를 온라인으로 제출
1,❏ 이용대상：자체 연말정산 시스템이 있는 회사로서 근로자의 연말정산간소화 자료를 간...,❏ 이용대상：자체 연말정산 시스템이 있는 회사로서 근로자의 연말정산간소화 자료를 간...,❏ 이용대상：자체 연말정산 시스템이 있는 회사로서 근로자의 연말정산간소화 자료를 간...
2,∙ (요건) 세액계산 프로그램 보유 +\n회사\n편리한 연말정산에 근로자 등록\n①...,∙ (요건) 세액계산 프로그램 보유 +\n회사\n편리한 연말정산에 근로자 등록\n①...,∙ (요건) 세액계산 프로그램 보유 +\n회사\n편리한 연말정산에 근로자 등록\n①...
3,비고,"공제서류를 온라인으로 제출받음으로써 연말정산 자료정리, 보관에 소요되는 비용 절감\...","공제서류를 온라인으로 제출받음으로써 연말정산 자료정리, 보관에 소요되는 비용 절감\..."

Page 385 - Table 1 DataFrame:

,0,1,2
0,연말정산 유형 ❺,연말정산 유형 ❺,편리한 연말정산(간편제출)을 이용하여 간소화 자료와 공제신고서를 온라인으로 제출
1,❏ 이용대상：근로자로부터 소득·세액공제신고서를 편리한 연말 정산을 통해 제출받고자 ...,❏ 이용대상：근로자로부터 소득·세액공제신고서를 편리한 연말 정산을 통해 제출받고자 ...,❏ 이용대상：근로자로부터 소득·세액공제신고서를 편리한 연말 정산을 통해 제출받고자 ...
2,∙ (요건) 세액계산 프로그램 보유 +\n회사\n편리한 연말정산에 근로자 등록\n①...,∙ (요건) 세액계산 프로그램 보유 +\n회사\n편리한 연말정산에 근로자 등록\n①...,∙ (요건) 세액계산 프로그램 보유 +\n회사\n편리한 연말정산에 근로자 등록\n①...
3,비고,근로자로부터 공제신고서와 간소화 자료를 온라인으로 제출받음으로써 공제신고서 작성·관...,근로자로부터 공제신고서와 간소화 자료를 온라인으로 제출받음으로써 공제신고서 작성·관...

Page 386 - Table 0 DataFrame:

,0,1
0,"연말정산 유형 ❻ 편리한 연말정산 서비스를 이용하여 자료 수집, 공제신고서 및 지급...","연말정산 유형 ❻ 편리한 연말정산 서비스를 이용하여 자료 수집, 공제신고서 및 지급..."
1,❏ 이용대상：홈택스의 편리한 연말정산에서 공제신고서와 간소화 자료를 간편제출 받고 ...,❏ 이용대상：홈택스의 편리한 연말정산에서 공제신고서와 간소화 자료를 간편제출 받고 ...
2,홈택스에서 연말정산 업무를 모두 처리\n회사\n∙ (요건) 연말정산에 근로자 등록\...,홈택스에서 연말정산 업무를 모두 처리\n회사\n∙ (요건) 연말정산에 근로자 등록\...
3,비고,홈택스에서 연말정산 업무를 모두 처리할 수 있어 연말정산 프로그램 유지·보수 비용을...

Page 396 - Table 0 DataFrame:

,0,1,2,3,4
0,단계,필수 선행절차,기본사항 및\n부양가족 입력,소득·세액공제\n명세 작성,공제신고서 및\n첨부서류 조회
1,내용,연말정산간소화에서 본인\n및 부양가족의 공제대상\n자료 선택,근무처 등 기본 사항과\n부양가족 입력,"간소화 자료 자동 반영,\n추가 수집 자료 직접 입력",공제신고서 및 부속명세서\n내용 확인 후 출력·제출
2,None,부양가족의 자료가 조회되지\n않는 경우 부양가족\n자료제공동의 필요,회사가 근로자 기초자료를\n등록한 경우 근무처 정보\n제공,연말정산간소화 자료 선택분\n미리채움 서비스,None

Page 397 - Table 0 DataFrame:

                0              1     2
0            None    근무처 사업자등록번호  None
1       공제신고서만 작성             선택    선택
2  정확한 공제액과 세액 계산             선택    필수
3            None  필수(회사가 먼저 등록)  None

Page 414 - Table 0 DataFrame:

,0,1,2
0,공제항목,맞벌이 배우자,배우자 외 부양가족
1,기본공제,총급여 500만원(소득금액 100만원)을 초과하는\n맞벌이 부부는 서로에 대해 기본...,직계존속·직계비속·형제자매 등을 부양하는 경우\n부부 중 1인이 공제 가능. (맞벌...
2,추가공제,기본공제 대상이 아닌 배우자는 추가공제 불가능,부양가족에 대해 기본공제를 신청한 근로자가\n추가공제를 적용 받음
3,자녀 세액공제,None,"본인이 기본공제를 받는 자녀(입양자, 위탁아동 포함)\n및 손자녀에 대해서 배우자가..."
4,보험료\n세액공제,본인이 계약자이며 피보험자가 배우자인 경우 서로\n기본공제 대상자에 해당하지 않으므...,본인이 기본공제 받는 자녀의 보험료를 배우자가\n지급하는 경우 부부 모두 보험료공제...
5,의료비\n세액공제,소득이 있는 배우자를 위하여 지출한 의료비는\n지출한 본인이 공제 가능,부부 중 부양가족을 기본공제 받는 근로자가 부양\n가족을 위해 지출한 금액 공제
6,교육비\n세액공제,본인이 배우자를 위하여 지출한 교육비는 공제\n불가능,부부 중 부양가족을 기본공제 받는 근로자가 부양\n가족을 위해 지출한 금액 공제
7,기부금\n세액공제,본인이 지출한 기부금은 배우자가 공제 불가능,부양가족에 대한 기본공제를 받는 근로자가 해당\n부양가족이 지출한 기부금 공제
8,None,가족카드를 사용한 맞벌이 부부는 카드 사용자\n기준으로 각각 공제(결제자 기준이 아님),None

Page 415 - Table 0 DataFrame:

,0,1,2,3
0,None,용어,설 명,None
1,1,주소,"사람의 생활관계의 중심이 되는 장소를 말하는 것으로, 국내에서 생계를\n같이 하는 ...",소령 §2
2,2,거소,주소지 외의 장소 중 상당기간에 걸쳐 거주하는 장소로서 주소와 같이\n밀접한 일반적...,소령 §2
3,3,거주자,국내에 주소를 두거나 183일 이상의 거소를 둔 개인,소법 §1의2
4,4,공제대상가족,거주자의 인적공제대상자를 말함,소령 §106
5,5,국민주택규모의\n주택,주거전용면적이 1호(戶) 또는 1세대당 85제곱미터 이하인 주택(｢수도\n권정비계획...,소령 §112\n조특령 §81
6,6,근로소득\n간이세액표,원천징수의무자가 근로자에게 매월 급여를 지급하는 때에 소득세를\n원천징수해야 하는 ...,소법 §134①\n소령 §194
7,7,근로소득\n경정청구,"근로소득 지급명세서를 기한내에 제출한 자가(원천징수의무자, 근로\n소득자 둘 다 포...",국기법\n§45의2④
8,8,근로소득\n원천징수영수증,근로소득을 지급하는 원천징수의무자가 해당 과세기간의 다음 연도\n2월 말일까지(퇴직...,소법 §143\n소칙 별지24(1)
9,9,근로소득\n원천징수부,"매월분의 근로소득을 지급하는 원천징수의무자가 근로소득의 상세내역\n(총급여, 간이세...",소령 §196\n소칙 별지25(1)
10,None,근로소득\n지급명세서,근로소득을 지급하는 원천징수의무자가 해당 과세기간의 다음 연도\n3월10일까지 원천...,None

Page 416 - Table 0 DataFrame:

,0,1,2
0,None,용어,설 명
1,11,근로소득자\n소득·세액공제\n신고서,"근로소득을 지급받는 자가 당해 근로소득자의 배우자 또는 부양가족에\n대한 인적공제,..."
2,12,기본공제,종합소득이 있는 거주자(자연인만 해당)에 대해서 다음 어느 하나에\n해당하는 사람의...
3,13,납세조합,외국기관 또는 우리나라에 주둔하는 국제연합군(미군은 제외한다)\n으로부터 받는 근로...
4,14,부양가족,주민등록표의 동거가족으로서 해당 거주자의 주소 또는 거소에서 현실적\n으로 생계를 ...
5,15,비거주자,거주자가 아닌 개인
6,16,세대,"거주자와 그 배우자, 거주자와 같은 주소 또는 거소에서 생계를 같이 하는\n거주자와..."
7,None,수입시기\n(귀속시기),과세기간별로 소득금액을 계산하기 위하여 계속적으로 발생하는 수입\n금액을 각 과세기...

Page 417 - Table 0 DataFrame:

,0,1,2
0,구분\n18\n19\n20\n21\n22\n23\n24\n25\n26,용어,설 명
1,구분\n18\n19\n20\n21\n22\n23\n24\n25\n26,실비변상적인\n급여,근로소득자가 업무수행을 위하여 실제로 소요된 경비상당액으로 보상\n받는 부분을 실비...
2,구분\n18\n19\n20\n21\n22\n23\n24\n25\n26,원천징수시기,원천징수대상소득을 지급하는 자가 그 소득을 지급받는 자에게 소득세를\n원천징수하는 ...
3,구분\n18\n19\n20\n21\n22\n23\n24\n25\n26,연말정산\n(근로소득),원천징수의무자가 근로자(일용근로자 제외)의 해당 과세기간 근로소득\n금액 또는 중도...
4,구분\n18\n19\n20\n21\n22\n23\n24\n25\n26,연말정산시기\n(근로소득),근로소득 연말정산을 하는 시기를 말하는 것으로 원천징수의무자는\n해당 과세기간의 다...
5,구분\n18\n19\n20\n21\n22\n23\n24\n25\n26,월정액급여,"매월 직급별로 받는 봉급·급료·보수·임금·수당, 그 밖에 이와 유사한\n성질의 급여..."
6,구분\n18\n19\n20\n21\n22\n23\n24\n25\n26,일용근로자,근로를 제공한 날 또는 시간에 따라 근로대가를 계산하거나 근로를\n제공한 날 또는 ...
7,구분\n18\n19\n20\n21\n22\n23\n24\n25\n26,종합소득,종합소득이란 당해연도에 발생하는 이자소득·배당소득·사업소득·\n근로소득·연금소득과 ...
8,구분\n18\n19\n20\n21\n22\n23\n24\n25\n26,주택 기준시가,｢부동산 가격공시에 관한 법률｣에 따라 공시된 개별주택가격 및 공동\n주택가격을 말...
9,구분\n18\n19\n20\n21\n22\n23\n24\n25\n26,총급여액,"근로를 제공함으로써 받는 봉급·급료, 보수, 세비, 임금, 상여, 수당과\n이와 유..."

Page 418 - Table 0 DataFrame:

      0                 1                                                  2
0  None                용어                                                설 명
1    27              인적공제  ｢소득세법｣상 인적공제는 종합소득이 있는 거주자(자연인에 한한다)의\n소득금액을 계...
2    28              추가공제  기본공제대상자가 다음 어느 하나에 해당하는 경우 추가적으로 공제함\n- 70세 이상...
3    29            특별소득공제  해당 과세기간에 지급한 국민건강보험료와 고용보험료 등, 주택구입\n및 임차비용, 기...
4    30            특별세액공제  해당 과세기간에 지급한 (장애인)보장성보험료, 의료비, 교육비, 기부금에\n대하여 ...
5    31            표준세액공제  근로소득이 있는 거주자로서 특별소득공제·특별세액공제·월세액세액\n공제를 신청하지 아...
6    32  항시 치료를\n요하는 중증환자  지병에 의해 평상시 치료를 요하고 취학·취업이 곤란한 상태에 있는 자를\n말하는 것...
7  None             난임시술비                  ｢모자보건법｣ 제2조제12호에 따른 보조생식술에 소요된 비용

Page 419 - Table 0 DataFrame:

,0,1,2,3,4,5
0,공제항목,공제항목,공제항목,첨부서류,발급처,None
1,인 적 공 제,부양가족 증명,부양가족 증명,주민등록표등본,시·군·구청 또는\n읍·면·동주민센터,None
2,인 적 공 제,부양가족 증명,부양가족 증명,가족관계증명서\n(주민등록표로 가족관계 확인이 어려운 경우),시·군·구청 또는\n읍·면·동주민센터,None
3,인 적 공 제,일시퇴거자,일시퇴거자,일시퇴거자 동거가족 상황표,본인 작성,None
4,인 적 공 제,일시퇴거자,일시퇴거자,재학증명서(취학의 경우),학교,None
5,인 적 공 제,일시퇴거자,일시퇴거자,요양증명서(요양의 경우),요양기관,None
6,인 적 공 제,일시퇴거자,일시퇴거자,재직증명서(재직의 경우),직장,None
7,인 적 공 제,일시퇴거자,일시퇴거자,사업자등록증사본(사업상 형편),본인 보관,None
8,인 적 공 제,입양자,입양자,입양사실확인서 또는 입양증명서,시·군·구청 또는\n입양기관,None
9,인 적 공 제,수급자,수급자,수급자증명서,읍·면·동주민센터,None
10,인 적 공 제,위탁아동,위탁아동,가정위탁보호확인서,시·군·구청,None
11,인 적 공 제,장 애 인,장애인복지법,장애인증명서·장애인등록증(복지카드) 사본,읍·면·동주민센터,국세청
12,인 적 공 제,장 애 인,상이자,상이자증명서 사본,국가보훈처,국세청
13,인 적 공 제,장 애 인,그 외,장애인증명서(소득세법 시행규칙 서식),의료기관,None
14,주 택 자 금,금융회사 등 차입\n주택임차차입금,금융회사 등 차입\n주택임차차입금,주택자금상환등증명서,금융회사 등,국세청
15,주 택 자 금,금융회사 등 차입\n주택임차차입금,금융회사 등 차입\n주택임차차입금,주민등록표등본,읍·면·동주민센터,None
16,주 택 자 금,개인간 차입\n주택임차차입금,개인간 차입\n주택임차차입금,월세액·거주자 간 주택임차차입금\n원리금 상환액 소득·세액공제 명세서,본인 작성,None
17,주 택 자 금,개인간 차입\n주택임차차입금,개인간 차입\n주택임차차입금,주택자금상환등증명서,대주(貸主),None
18,주 택 자 금,개인간 차입\n주택임차차입금,개인간 차입\n주택임차차입금,주민등록표등본,읍·면·동주민센터,None
19,주 택 자 금,개인간 차입\n주택임차차입금,개인간 차입\n주택임차차입금,임대차계약증서 사본,본인 보관,None
20,주 택 자 금,개인간 차입\n주택임차차입금,개인간 차입\n주택임차차입금,금전소비대차계약서 사본,본인 보관,None
21,주 택 자 금,개인간 차입\n주택임차차입금,개인간 차입\n주택임차차입금,원리금 상환 증명서류(계좌이체영수증 및\n무통장입금증 등),본인 보관,None

Page 420 - Table 0 DataFrame:

               0                                     1                2
0           None                                  첨부서류              발급처
1    장기주택\n저당차입금                     장기주택저당차입금 이자상환증명서           금융회사 등
2    장기주택\n저당차입금                               주민등록표등본        읍·면·동주민센터
3    장기주택\n저당차입금                         개별(공동)주택가격확인서           시·군·구청
4    장기주택\n저당차입금                   건물등기부등본 또는 분양계약서 사본       등기소, 본인 보관
5    장기주택\n저당차입금  기존 및 신규차입금의 대출계약서 사본\n(대환, 차환, 연장 시)           금융회사 등
6         개인연금저축                   개인연금저축납입증명서 또는 통장사본  금융회사 등 또는 본인 보관
7     소기업·소상공인공제                             공제부금납입증명서          중소기업중앙회
8         주택마련저축                   주택마련저축납입증명서 또는 통장사본  금융회사 등 또는 본인 보관
9      투자조합 출자공제                          출자 등 소득공제신청서            본인 작성
10     투자조합 출자공제                             출자(투자)확인서        투자조합관리자 등
11    신용카드 등 사용액                       신용카드 등 소득공제 신청서            본인 작성
12    신용카드 등 사용액                       신용카드 등 사용금액 확인서             카드회사
13     우리사주조합출연금                         우리사주조합출연금액확인서           우리사주조합
14    장기집합투자증권저축                      장기집합투자증권저축 납입증명서           금융회사 등
15        퇴직연금계좌                               연금납입확인서          연금계좌취급자
16        연금저축계좌                               연금납입확인서          연금계좌취급자
17         보장성보험                  보험료납입증명서 또는 보험료납입영수증            보험사업자
18        의료비명세서                              의료비지급명세서            본인 작성
19       의료기관·병원                계산서·영수증, 진료비(약제비)납입확인서          병의원, 약국
20         난임시술비                         진료비(약제비)납입확인서          병의원, 약국
21     안경(콘택트렌즈)        사용자의 성명과 시력교정용임을\n안경사가 확인한 영수증              구입처
22  보청기,\n장애인보장구                 사용자의 성명을 판매자가 확인한 영수증              구입처
23          의료기기                      의사·치과의사·한의사의 처방전              병의원
24          의료기기    판매자 또는 임대인이 발행한\n의료기기명이 기재된 의료비영수증              구입처
25        노인장기요양                         장기요양급여비 납부확인서             요양기관

Page 421 - Table 0 DataFrame:

,0,1,2,3
0,공제항목,공제항목,첨부서류,발급처
1,의 료 비\n교 육 비,건강보험산정\n특례 대상자,장애인증명서 등 건강보험 산정특례\n대상자로 등록된 자임을 증명할 수 있는 서류,의료기관 등
2,의 료 비\n교 육 비,산후조리원비용,이용자의 성명과 이용대가를 확인한 영수증,산후조리원
3,의 료 비\n교 육 비,실손의료보험금\n수령액 자료,실손의료보험금 수령액 자료,보험회사 등
4,의 료 비\n교 육 비,"수업료, 등록금 등",교육비납입증명서,교육기관
5,의 료 비\n교 육 비,"수능응시료,\n대학입학전형료",납입을 증명할 수 있는 서류,교육기관
6,의 료 비\n교 육 비,취학전아동 학원비,교육비납입증명서,학원
7,의 료 비\n교 육 비,교복구입비,교육비납입증명서,구입처
8,의 료 비\n교 육 비,학교 외 도서구입비,방과후 학교 수업용 도서 구입 증명서,교육기관
9,의 료 비\n교 육 비,장애인특수교육비,교육비납입증명서,사회복지시설 등
10,의 료 비\n교 육 비,장애인특수교육비,장애인 특수 교육시설 해당 입증 서류,사회복지시설 등
11,의 료 비\n교 육 비,학자금대출\n상환액,교육비납입증명서,한국장학재단 등
12,의 료 비\n교 육 비,국외교육비,교육비 납입을 증명 할 수 있는 서류,국외 교육기관
13,의 료 비\n교 육 비,국외교육비,재학증명서,국외 교육기관
14,의 료 비\n교 육 비,국외교육비,부양가족의 유학자격 입증 서류\n(근로자가 국내 근무하는 경우),교육기관 등
15,의 료 비\n교 육 비,None,기부금명세서,본인 작성
16,의 료 비\n교 육 비,None,정치자금기부금 영수증,중앙선관위 또는 기부처
17,의 료 비\n교 육 비,None,고향사랑기부금 영수증,지방자치단체
18,의 료 비\n교 육 비,None,기부금 영수증,기부처
19,의 료 비\n교 육 비,None,미분양주택확인서\n(근로자는 주택자금이자세액공제 신청서 작성)\n금융기관이 발행한 ...,지방자치단체
20,의 료 비\n교 육 비,None,외국인 기술자의 근로소득세 감면신청서,본인 작성
21,의 료 비\n교 육 비,None,외국인 근로소득세액감면신청서,본인 작성
22,의 료 비\n교 육 비,None,중소기업 취업자 소득세 감면신청서,본인 작성
23,외국납부세액공제,외국납부세액공제,외국납부세액공제(필요경비산입)신청서,본인 작성

Page 422 - Table 0 DataFrame:

,0,1,2,3
0,None,첨부서류,발급처,None
1,월세액,월세액·거주자 간 주택임차차입금\n원리금 상환액 소득·세액공제 명세서,본인 작성,국세청\n(공공주택\n임대사업자)
2,월세액,주민등록표등본,읍·면·동주민센터,None
3,월세액,임대차계약증서 사본,본인 보관,None
4,월세액,"월세액 지급 증명서류(현금영수증,\n계좌이체 영수증, 무통장입금증 등)",본인 보관,국세청
5,중소기업핵심인력\n성과보상기금 수령액에\n대한 소득세 감면,중소기업핵심인력 성과보상기금 수령액에 대한\n소득세 감면신청서,본인 작성,None
6,내국인 우수 인력\n국내복귀 소득세 감면,내국인 우수 인력의 국내복귀에 대한\n소득세 감면신청서,본인 작성,None
7,성과공유 중소기업의\n경영성과급에 대한\n소득세 감면,성과공유 중소기업 경영성과급\n소득세 감면신청서,본인 작성,None
8,외국인근로자 단일세율적용,외국인근로자 단일세율적용신청서,본인 작성,None
9,외국인근로자 등,외국인등록사실증명\n(주민등록표등본에 갈음),출입국관리사무소,None
10,외국인근로자 등,재외국민등록부등본\n(국내 주민등록 없는 재외국민),재외공관,None

Page 423 - Table 0 DataFrame:

      0                   1                     2     3
0    구분                근로소득                  사업소득  연금소득
1  None  모든 근로자\n(일용근로자 제외)  보험모집인, 방문판매원,\n음료배달원  None

Page 423 - Table 1 DataFrame:

,0,1,2,3
0,None,총급여,사업소득 수입금액,None
1,3. 소득금액\n(①),근로소득금액\n(총급여 - 근로소득공제),사업소득금액\n(수입금액 × 소득률),연금소득금액\n(총연금액 - 연금소득공제)
2,4. 종합소득\n공제금액\n(②),"[종합소득공제]\n(기본공제, 추가공제,\n연금보험료공제,\n특별소득공제,\n그 밖...","[종합소득공제]\n(기본공제, 추가공제,\n연금보험료공제)","[종합소득공제]\n(기본공제, 추가공제,"
3,5. 과세표준\n(①-②),근로소득금액 -\n종합소득공제금액,사업소득금액 -\n종합소득공제금액,연금소득금액 -\n종합소득공제금액
4,6. 세율,6~45%,6~45%,6~45%
5,None,과세표준 × 세율,과세표준 × 세율,None

Page 424 - Table 0 DataFrame:

,0,1,2,3,4
0,항목,항목,구분,구분,비고
1,항목,항목,외국인\n거주자,비거주자,비고
2,None,None,국외원천\n소득포함,국내 원천소득,｢소득세법｣ 제3조에 따른 단기거주 외국인은 국외\n원천소득 중 국내에서 지급되거나...
3,None,None,○,○,None
4,인적공제,기본공제,○,본인만 공제,None
5,인적공제,추가공제,○,본인만 공제,None
6,None,None,○,○,본인이 납부하는 국민연금보험료에 한함
7,특별 소득공제,건강·고용보험료 등,○,×,None
8,특별 소득공제,주택자금,○,×,None
9,그 밖의 소득공제,개인연금저축\n소기업 등 공제부금\n투자조합출자\n신용카드 등 사용금액\n고용유지중...,○,×,None
10,그 밖의 소득공제,주택마련저축,×,×,None
11,그 밖의 소득공제,우리사주조합출연금,○,○,우리사주조합에 가입하여 출연한 금액에 한함
12,세액공제,근로소득,○,○,None
13,세액공제,"자녀, 특별세액공제\n(보험료·의료비,\n교육비, 기부금)",○,×,None
14,세액공제,납세조합,○,○,None

In [ ]:
TABLES_BY_PAGE[7][1].df

,0,1,2,3,4,5
0,구 분,구 분,기본공제대상자의 요건,기본공제대상자의 요건,근로기간 지출한\n비용만 공제,비 고
1,구 분,구 분,나이요건 소득요건,나이요건 소득요건,근로기간 지출한\n비용만 공제,비 고
2,특별 소득공제,보 험 료,None,None,None,None
3,특별 소득공제,주택자금공제,None,None,None,None
4,그 밖의 소득공제,개인연금저축,None,None,None,None
5,그 밖의 소득공제,주택마련저축,None,None,None,None
6,그 밖의 소득공제,신용카드 등,×,,,None
7,자녀세액공제 (8세이상),자녀세액공제 (8세이상),,,-,기본공제대상 자녀\n(입양자·위탁아동·손자녀 포함)

pdf 육안 확인 + df로 바꿔보니 여간 복잡한 게 아니다.

1. 병합된 셀이 많다.
2. 특수문자(O) 같은 게 씹히는 경우가 있다.
3. 타이틀을 일일이 달아줘야 할 것 같다.
4. 표에서 확인할 수 있는 정보는 표를 참고하라고 따로 명령해야 할 듯.

큰 제목

내용 1

내용 2

    - 하위 내용 1

    - 하위 내용 2

      - 표 1

...

In [ ]:
"https://huggingface.co/microsoft/tapex-base-finetuned-wikisql"

## RAG 설계

0. 문장 데이터와 표 데이터로 나눈다.
1. 문장 데이터는 OPENAI 모델이 진행.
2. 표 데이터는 https://huggingface.co/microsoft/tapex-base-finetuned-wikisql
3. 허위 정보를 알려줘서는 안 되니, 모르는 건 모른다고 하자.
4. 참고한 페이지 정보를 같이 출력해주어 유저가 더블 체크할 수 있도록 하자.